'\" t
.\"
.TH "\fBMARIADB-IMPORT\fR" "1" "10 February 2025" "MariaDB 11.8" "MariaDB Database System"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.\" mariadb-import
.\" importing: data
.\" data: importing
.\" files: text
.\" text files: importing
.SH "NAME"
mariadb-import \- a data import program (mariadb-import is now a symlink to mariadb-import)
.SH "SYNOPSIS"
.HP \w'\fBmariadb-import\ [\fR\fB\fIoptions\fR\fR\fB]\ \fR\fB\fIdb_name\fR\fR\fB\ \fR\fB\fItextfile1\fR\fR\fB\ \&.\&.\&.\fR\ 'u
\fBmariadb-import [\fR\fB\fIoptions\fR\fR\fB] \fR\fB\fIdb_name\fR\fR\fB \fR\fB\fItextfile1\fR\fR\fB \&.\&.\&.\fR
.SH "DESCRIPTION"
.PP
The
\fBmariadb-import\fR
client provides a command\-line interface to the
LOAD DATA INFILE
SQL statement\&. Most options to
\fBmariadb-import\fR
correspond directly to clauses of
LOAD DATA INFILE
syntax\&.
.PP
Invoke
\fBmariadb-import\fR
like this:
.sp
.if n \{\
.RS 4
.\}
.nf
shell> \fBmariadb-import [\fR\fB\fIoptions\fR\fR\fB] \fR\fB\fIdb_name\fR\fR\fB \fR\fB\fItextfile1\fR\fR\fB [\fR\fB\fItextfile2\fR\fR\fB \&.\&.\&.]\fR
.fi
.if n \{\
.RE
.\}
.PP
For each text file named on the command line,
\fBmariadb-import\fR
strips any extension from the file name and uses the result to determine the name of the table into which to import the file's contents\&. For example, files named
patient\&.txt,
patient\&.text, and
patient
all would be imported into a table named
patient\&.
.PP
.PP
\fBmariadb-import\fR
supports the following options, which can be specified on the command line or in the
[mariadb-import]
and
[client]
option file groups\&.
\fBmariadb-import\fR
also supports the options for processing option files\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: help option
.\" help option: mariadb-import
\fB\-\-help\fR,
\fB\-?\fR
.sp
Display a help message and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: character-sets-dir option
.\" character-sets-dir option: mariadb-import
\fB\-\-character\-sets\-dir=\fR\fB\fIpath\fR\fR
.sp
The directory where character sets are installed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: columns option
.\" columns option: mariadb-import
\fB\-\-columns=\fR\fB\fIcolumn_list\fR\fR,
\fB\-c \fR\fB\fIcolumn_list\fR\fR
.sp
This option takes a comma\-separated list of column names as its value\&. The order of the column names indicates how to match data file columns with table columns\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: compress option
.\" compress option: mariadb-import
\fB\-\-compress\fR,
\fB\-C\fR
.sp
Compress all information sent between the client and the server if both support compression\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: debug option
.\" debug option: mariadb-import
\fB\-\-debug[=\fR\fB\fIdebug_options\fR\fR\fB]\fR,
\fB\-# [\fR\fB\fIdebug_options\fR\fR\fB]\fR
.sp
Write a debugging log\&. A typical
\fIdebug_options\fR
string is 'd:t:o,\fIfile_name\fR'. The default is 'd:t:o'.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: debug-check option
.\" debug-check option: mariadb-import
\fB\-\-debug\-check\fR
.sp
Print some debugging information when the program exits\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: debug-info option
.\" debug-info option: mariadb-import
\fB\-\-debug\-info\fR
.sp
Print debugging information and memory and CPU usage statistics when the program exits\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: default-auth option
.\" default-auth option: mariadb-import
\fB\-\-default\-auth=\fIplugin_name\fR
.sp
Default authentication client-side plugin to use\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: default-character-set option
.\" default-character-set option: mariadb-import
\fB\-\-default\-character\-set=\fR\fB\fIcharset_name\fR\fR
.sp
Use
\fIcharset_name\fR
as the default character set\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: defaults-extra-file option
.\" defaults-extra-file option: mariadb-import
\fB\-\-defaults\-extra\-file=\fR\fB\fIfilename\fR\fR
.sp
Set \fB\fIfilename\fR\fR as the file to read default options from after the global defaults files has been
read\&.  Must be given as first option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: defaults-file option
.\" defaults-file option: mariadb-import
\fB\-\-defaults\-file=\fR\fB\fIfilename\fR\fR
.sp
Set \fB\fIfilename\fR\fR as the file to read default options from, override global defaults files\&.
Must be given as first option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: delete option
.\" delete option: mariadb-import
\fB\-\-delete\fR,
\fB\-d\fR
.sp
Empty the table before importing the text file\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: fields-terminated-by option
.\" fields-terminated-by option: mariadb-import
\fB\-\-fields\-terminated\-by=\&.\&.\&.\fR,
.\" mariadb-import: fields-enclosed-by option
.\" fields-enclosed-by option: mariadb-import
\fB\-\-fields\-enclosed\-by=\&.\&.\&.\fR,
.\" mariadb-import: fields-optionally-enclosed-by option
.\" fields-optionally-enclosed-by option: mariadb-import
\fB\-\-fields\-optionally\-enclosed\-by=\&.\&.\&.\fR,
.\" mariadb-import: fields-escaped-by option
.\" fields-escaped-by option: mariadb-import
\fB\-\-fields\-escaped\-by=\&.\&.\&.\fR
.sp
These options have the same meaning as the corresponding clauses for
LOAD DATA INFILE\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: force option
.\" force option: mariadb-import
\fB\-\-force\fR,
\fB\-f\fR
.sp
Ignore errors\&. For example, if a table for a text file does not exist, continue processing any remaining files\&. Without
\fB\-\-force\fR,
\fBmariadb-import\fR
exits if a table does not exist\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: host option
.\" host option: mariadb-import
\fB\-\-host=\fR\fB\fIhost_name\fR\fR,
\fB\-h \fR\fB\fIhost_name\fR\fR
.sp
Import data to the MariaDB server on the given host\&. The default host is
localhost\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: ignore option
.\" ignore option: mariadb-import
\fB\-\-ignore\fR,
\fB\-i\fR
.sp
See the description for the
\fB\-\-replace\fR
option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: ignore-foreign-keys option
.\" ignore-foreign-keys option: mariadb-import
\fB\-\-ignore\-foreign\-keys\fR,
\fB\-k\fR
.sp
Disable foreign key checks while importing the data\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: ignore-lines option
.\" ignore-lines option: mariadb-import
\fB\-\-ignore\-lines=\fR\fB\fIN\fR\fR
.sp
Ignore the first
\fIN\fR
lines of the data file\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: innodb-optimize-keys option
.\" innodb-optimize-keys option: mariadb-import
\fB\-\-innodb\-optimize\-keys\fR
.sp
Create secondary indexes after data load, which speeds up loading (InnoDB only)\&. Defaults to on; use --skip-innodb-optimize-keys to disable\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: lines-terminated-by option
.\" lines-terminated-by option: mariadb-import
\fB\-\-lines\-terminated\-by=\&.\&.\&.\fR
.sp
This option has the same meaning as the corresponding clause for
LOAD DATA INFILE\&. For example, to import Windows files that have lines terminated with carriage return/linefeed pairs, use
\fB\-\-lines\-terminated\-by="\er\en"\fR\&. (You might have to double the backslashes, depending on the escaping conventions of your command interpreter\&.)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: local option
.\" local option: mariadb-import
\fB\-\-local\fR,
\fB\-L\fR
.sp
Read input files locally from the client host\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: lock-tables option
.\" lock-tables option: mariadb-import
\fB\-\-lock\-tables\fR,
\fB\-l\fR
.sp
Lock
\fIall\fR
tables for writing before processing any text files\&. This ensures that all tables are synchronized on the server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: low-priority option
.\" low-priority option: mariadb-import
\fB\-\-low\-priority\fR
.sp
Use
LOW_PRIORITY
when loading the table\&. This affects only storage engines that use only table\-level locking (such as
MyISAM,
MEMORY, and
MERGE)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: no-defaults option
.\" no-defaults option: mariadb-import
\fB\-\-no\-defaults\fR
.sp
Do not read default options from any option file\&. This must be given as the
first argument\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: parallel option
.\" parallel option: mariadb-import
\fB\-\-parallel=\fR\fB\fIN\fR\fR,
\fB\-j \fR\fB\fIN\fR\fR\fR
.sp
Number of LOAD DATA jobs executed in parallel. \-\-use-threads is a synonym\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: password option
.\" password option: mariadb-import
\fB\-\-password[=\fR\fB\fIpassword\fR\fR\fB]\fR,
\fB\-p[\fR\fB\fIpassword\fR\fR\fB]\fR
.sp
The password to use when connecting to the server\&. If you use the short option form (\fB\-p\fR), you
\fIcannot\fR
have a space between the option and the password\&. If you omit the
\fIpassword\fR
value following the
\fB\-\-password\fR
or
\fB\-p\fR
option on the command line,
\fBmariadb-import\fR
prompts for one\&.
.sp
Specifying a password on the command line should be considered insecure\&. You can use an option file to avoid giving the password on the command line\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: pipe option
.\" pipe option: mariadb-import
\fB\-\-pipe\fR,
\fB\-W\fR
.sp
On Windows, connect to the server via a named pipe\&. This option applies only if the server supports named\-pipe connections\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: plugin-dir option
.\" plugin-dir option: mariadb-import
\fB\-\-plugin\-dir=\fR\fB\fIname\fR\fR
.sp
 Directory for client-side plugins\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: port option
.\" port option: mariadb-import
\fB\-\-port=\fR\fB\fIport_num\fR\fR,
\fB\-P \fR\fB\fIport_num\fR\fR
.sp
The TCP/IP port number to use for the connection\&.
Forces --protocol=tcp when specified on the command line without other connection properties\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: protocol option
.\" protocol option: mariadb-import
\fB\-\-protocol={TCP|SOCKET|PIPE|MEMORY}\fR
.sp
The connection protocol to use for connecting to the server\&. It is useful when the other connection parameters normally would cause a protocol to be used other than the one you want\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: print-defaults option
.\" print-defaults option: mariadb-import
\fB\-\-print\-defaults\fR
.sp
Print the program argument list and exit\&.
This must be given as the first argument\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: replace option
.\" replace option: mariadb-import
\fB\-\-replace\fR,
\fB\-r\fR
.sp
The
\fB\-\-replace\fR
and
\fB\-\-ignore\fR
options control handling of input rows that duplicate existing rows on unique key values\&. If you specify
\fB\-\-replace\fR, new rows replace existing rows that have the same unique key value\&. If you specify
\fB\-\-ignore\fR, input rows that duplicate an existing row on a unique key value are skipped\&. If you do not specify either option, an error occurs when a duplicate key value is found, and the rest of the text file is ignored\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: silent option
.\" silent option: mariadb-import
\fB\-\-silent\fR,
\fB\-s\fR
.sp
Silent mode\&. Produce output only when errors occur\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: socket option
.\" socket option: mariadb-import
\fB\-\-socket=\fR\fB\fIpath\fR\fR,
\fB\-S \fR\fB\fIpath\fR\fR
.sp
For connections to
localhost, the Unix socket file to use, or, on Windows, the name of the named pipe to use\&.
Forces --protocol=socket when specified on the command line without other connection properties; on Windows, forces --protocol=pipe\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL options
.\" SSL options: mariadb-import
\fB\-\-ssl\fR
.sp
Enable SSL for connection (automatically enabled with other flags). Disable with
\fB\-\-skip-ssl\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL CA option
.\" SSL CA option: mariadb-import
\fB\-\-ssl\-ca=\fIname\fR
.sp
CA file in PEM format (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL CA Path option
.\" SSL CA Path option: mariadb-import
\fB\-\-ssl\-capath=\fIname\fR
.sp
CA directory (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL Cert option
.\" SSL Cert option: mariadb-import
\fB\-\-ssl\-cert=\fIname\fR
.sp
X509 cert in PEM format (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL Cipher option
.\" SSL Cipher option: mariadb-import
\fB\-\-ssl\-cipher=\fIname\fR
.sp
SSL cipher to use (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL Key option
.\" SSL Key option: mariadb-import
\fB\-\-ssl\-key=\fIname\fR
.sp
X509 key in PEM format (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL Crl option
.\" SSL CRL option: mariadb-import
\fB\-\-ssl\-crl=\fIname\fR
.sp
Certificate revocation list (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL Crlpath option
.\" SSL Crlpath option: mariadb-import
\fB\-\-ssl\-crlpath=\fIname\fR
.sp
Certificate revocation list path (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: SSL Verify Server Cert option
.\" SSL Verify Server Cert option: mariadb-import
\fB\-\-ssl\-verify\-server\-cert\fR
.sp
Verify server's "Common Name" in its cert against hostname used when connecting. This option is disabled by default\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: user option
.\" user option: mariadb-import
\fB\-\-user=\fR\fB\fIuser_name\fR\fR,
\fB\-u \fR\fB\fIuser_name\fR\fR
.sp
The MariaDB user name to use when connecting to the server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: use-threads option
.\" use-threads option: mariadb-import
\fB\-\-use\-threads=\fR\fB\fIN\fR\fR
.sp
Load files in parallel using
\fIN\fR
threads\&. Synonym for \-j, \-\-parallel=num
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: verbose option
.\" verbose option: mariadb-import
\fB\-\-verbose\fR,
\fB\-v\fR
.sp
Verbose mode\&. Print more information about what the program does\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-import: version option
.\" version option: mariadb-import
\fB\-\-version\fR,
\fB\-V\fR
.sp
Display version information and exit\&.
.RE
.PP
Here is a sample session that demonstrates use of
\fBmariadb-import\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
shell> \fBmariadb \-e 'CREATE TABLE imptest(id INT, n VARCHAR(30))' test\fR
shell> \fBed\fR
a
100     Max Sydow
101     Count Dracula
\&.
w imptest\&.txt
32
q
shell> \fBod \-c imptest\&.txt\fR
0000000   1   0   0  \et   M   a   x       S   y   d   o   w  \en   1   0
0000020   1  \et   C   o   u   n   t       D   r   a   c   u   l   a  \en
0000040
shell> \fBmariadb-import \-\-local test imptest\&.txt\fR
test\&.imptest: Records: 2  Deleted: 0  Skipped: 0  Warnings: 0
shell> \fBmariadb \-e 'SELECT * FROM imptest' test\fR
+\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| id   | n             |
+\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
|  100 | Max Sydow     |
|  101 | Count Dracula |
+\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
.fi
.if n \{\
.RE
.\}
.SH "COPYRIGHT"
.br
.PP
Copyright 2007-2008 MySQL AB, 2008-2010 Sun Microsystems, Inc., 2010-2025 MariaDB Foundation
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335 USA or see http://www.gnu.org/licenses/.
.sp
.SH "SEE ALSO"
For more information, please refer to the MariaDB Knowledge Base, available online at https://mariadb.com/docs/
.SH AUTHOR
MariaDB Foundation (http://www.mariadb.org/).
