'\" t
.\"
.TH "\FBMARIADB-CONV" "1" "15 May 2020" "MariaDB 10\&.6" "MariaDB Database System"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.\" mariadb\-conv
.SH "NAME"
mariadb\-conv \- character set conversion utility for MariaDB
.SH "SYNOPSIS"
.HP \w'\fBmariadb\-conv\ [\fR\fB\fIOPTION...\fR\fR\fB]\ [\fR\fB\fIFILE...\fR\fR\fB]\  'u
\fBmariadb\-conv [\fR\fB\fIOPTION...\fR\fR\fB] [\fR\fB\fIFILE...\fR\fR\fB] \fR
.SH "DESCRIPTION"
.PP
\fBmariadb\-conv\fR
is a character set conversion utility for MariaDB\&.
.PP
\fBmariadb-conv\fR
supports the following options\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-conv: from option
.\" from option: mariadb-conv
\fB\-\-from=\fR\fB\fIname\fR\fR,
\fB\-f \fR\fB\fIname\fR\fR
.sp
Specifies the encoding of the input\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-conv: to option
.\" to option: mariadb-conv
\fB\-\-to=\fR\fB\fIname\fR\fR,
\fB\-t \fR\fB\fIname\fR\fR
.sp
Specifies the encoding of the output\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-conv: continue option
.\" continue option: mariadb-conv
\fB\-\-continue\fR,
\fB\-c \fR
.sp
Silently ignore conversion errors\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-conv: continue option
.\" continue option: mariadb-conv
\fB\-\-delimiter=\fR\fB\fIname\fR\fR,
.sp
Treat the specified characters as delimiters\&.
.RE
.SH "COPYRIGHT"
.br
.PP
Copyright 2020 MariaDB Foundation
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335 USA or see http://www.gnu.org/licenses/.
.sp
.SH "SEE ALSO"
For more information, please refer to the MariaDB Knowledge Base, available online at https://mariadb.com/kb/en/mariadb-conv/
.SH AUTHOR
MariaDB Foundation (http://www.mariadb.org/).
