'\" t
.\"
.TH "\fBMARIADB-ADMIN\fR" "1" "3 September 2024" "MariaDB 11.4" "MariaDB Database System"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.\" mariadb-admin
.\" administration: server
.\" server administration
.SH "NAME"
mariadb-admin \- client for administering a MariaDB server (mariadb-admin is now a symlink to mariadb-admin)
.SH "SYNOPSIS"
.HP \w'\fBmariadb-admin\ [\fR\fB\fIoptions\fR\fR\fB]\ \fR\fB\fIcommand\fR\fR\fB\ [\fR\fB\fIcommand\-arg\fR\fR\fB]\ [\fR\fB\fIcommand\fR\fR\fB\ [\fR\fB\fIcommand\-arg\fR\fR\fB]]\ \&.\&.\&.\fR\ 'u
\fBmariadb-admin [\fR\fB\fIoptions\fR\fR\fB] \fR\fB\fIcommand\fR\fR\fB [\fR\fB\fIcommand\-arg\fR\fR\fB] [\fR\fB\fIcommand\fR\fR\fB [\fR\fB\fIcommand\-arg\fR\fR\fB]] \&.\&.\&.\fR
.SH "DESCRIPTION"
.PP
\fBmariadb-admin\fR
is a client for performing administrative operations\&. You can use it to check the server's configuration and current status, to create and drop databases, and more\&.
.PP
Invoke
\fBmariadb-admin\fR
like this:
.sp
.if n \{\
.RS 4
.\}
.nf
shell> \fBmariadb-admin [\fR\fB\fIoptions\fR\fR\fB] \fR\fB\fIcommand\fR\fR\fB [\fR\fB\fIcommand\-arg\fR\fR\fB] [\fR\fB\fIcommand\fR\fR\fB [\fR\fB\fIcommand\-arg\fR\fR\fB]] \&.\&.\&.\fR
.fi
.if n \{\
.RE
.\}
.PP
\fBmariadb-admin\fR
supports the following commands\&. Some of the commands take an argument following the command name\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
create \fIdb_name\fR
.sp
Create a new database named
\fIdb_name\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
debug
.sp
Tell the server to write debug information to the error log\&.
.sp
This also includes information about the Event Scheduler\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
drop \fIdb_name\fR
.sp
Delete the database named
\fIdb_name\fR
and all its tables\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
extended\-status
.sp
Display the server status variables and their values\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-all\-statistics
.sp
Flush all statistics tables\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-all\-status
.sp
Flush all status and statistics\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-binary\-log
.sp
Flush the binary log\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-client\-statistics
.sp
Flush client statistics\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-engine\-log
.sp
Flush engine log\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-error\-log
.sp
Flush error log\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-general\-log
.sp
Flush general query log\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-hosts
.sp
Flush all information in the host cache\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-index\-statistics
.sp
Flush index statistics\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-logs
.sp
Flush all logs\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-privileges
.sp
Reload the grant tables (same as
reload)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-relay\-log
.sp
Flush relay log\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-slow\-log
.sp
Flush slow query log\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-ssl
.sp
Flush SSL certificates\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-status
.sp
Clear status variables\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-table\-statistics
.sp
Flush table statistics\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-tables
.sp
Flush all tables\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-threads
.sp
Flush the thread cache\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flush\-user\-resources
.sp
Flush user resources\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
kill \fIid\fR,\fIid\fR,\&.\&.\&.
.sp
Kill server threads\&. If multiple thread ID values are given, there must be no spaces in the list\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
old\-password \fInew\-password\fR
.sp
This is like the
password
command but stores the password using the old (pre MySQL 4\&.1) password\-hashing format\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
password \fInew\-password\fR
.sp
Set a new password\&. This changes the password to
\fInew\-password\fR
for the account that you use with
\fBmariadb-admin\fR
for connecting to the server\&. Thus, the next time you invoke
\fBmariadb-admin\fR
(or any other client program) using the same account, you will need to specify the new password\&.
.sp
If the
\fInew\-password\fR
value contains spaces or other characters that are special to your command interpreter, you need to enclose it within quotes\&. On Windows, be sure to use double quotes rather than single quotes; single quotes are not stripped from the password, but rather are interpreted as part of the password\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
shell> \fBmariadb-admin password "my new password"\fR
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBCaution\fR
.ps -1
.br
Do not use this command used if the server was started with the
\fB\-\-skip\-grant\-tables\fR
option\&. No password change will be applied\&. This is true even if you precede the
password
command with
flush\-privileges
on the same command line to re\-enable the grant tables because the flush operation occurs after you connect\&. However, you can use
\fBmariadb-admin flush\-privileges\fR
to re\-enable the grant table and then use a separate
\fBmariadb-admin password\fR
command to change the password\&.
.sp .5v
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ping
.sp
Check whether the server is alive\&. The return status from
\fBmariadb-admin\fR
is 0 if the server is running, 1 if it is not\&. This is 0 even in case of an error such as
Access denied, because this means that the server is running but refused the connection, which is different from the server not running\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
processlist
.sp
Show a list of active server threads\&. This is like the output of the
SHOW PROCESSLIST
statement\&. If the
\fB\-\-verbose\fR
option is given, the output is like that of
SHOW FULL PROCESSLIST\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
reload
.sp
Reload the grant tables\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
refresh
.sp
Flush all tables and close and open log files\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
shutdown
.sp
Stop the server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
start\-all\-slaves
.sp
Start all slaves\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
start\-slave
.sp
Start replication on a slave server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
status
.sp
Display a short server status message\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
stop\-all\-slaves
.sp
Stop all slaves\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
stop\-slave
.sp
Stop replication on a slave server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
variables
.sp
Display the server system variables and their values\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
version
.sp
Display version information from the server\&.
.RE
.PP
All commands can be shortened to any unique prefix\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
shell> \fBmariadb-admin proc stat\fR
+\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| Id | User  | Host      | db | Command | Time | State | Info             |
+\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| 51 | monty | localhost |    | Query   | 0    |       | show processlist |
+\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
Uptime: 1473624  Threads: 1  Questions: 39487
Slow queries: 0  Opens: 541  Flush tables: 1
Open tables: 19  Queries per second avg: 0\&.0268
.fi
.if n \{\
.RE
.\}
.sp
.\" status command: results
.PP
The
\fBmariadb-admin status\fR
command result displays the following values:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" uptime
Uptime
.sp
The number of seconds the MariaDB server has been running\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" threads
Threads
.sp
The number of active threads (clients)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" questions
Questions
.sp
The number of questions (queries) from clients since the server was started\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" slow queries
Slow queries
.sp
The number of queries that have taken more than
log_slow_query_time
seconds\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" opens
Opens
.sp
The number of tables the server has opened\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" flush tables
.\" tables: flush
Flush tables
.sp
The number of
flush\-*,
refresh, and
reload
commands the server has executed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" open tables
Open tables
.sp
The number of tables that currently are open\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" memory use
Memory in use
.sp
The amount of memory allocated directly by
\fBmariadbd\fR\&. This value is displayed only when MariaDB has been compiled with
\fB\-\-with\-debug=full\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" maximum memory used
Maximum memory used
.sp
The maximum amount of memory allocated directly by
\fBmariadbd\fR\&. This value is displayed only when MariaDB has been compiled with
\fB\-\-with\-debug=full\fR\&.
.RE
.PP
If you execute
\fBmariadb-admin shutdown\fR
when connecting to a local server using a Unix socket file,
\fBmariadb-admin\fR
waits until the server's process ID file has been removed, to ensure that the server has stopped properly\&.
.\" mariadb-admin command options
.\" command options: mariadb-admin
.\" options: command-line: mariadb-admin
.\" startup parameters: mariadb-admin
.PP
\fBmariadb-admin\fR
supports the following options, which can be specified on the command line or in the
[mariadb-admin]
and
[client]
option file groups\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: help option
.\" help option: mariadb-admin
\fB\-\-help\fR,
\fB\-?\fR
.sp
Display help and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: character-sets-dir option
.\" character-sets-dir option: mariadb-admin
\fB\-\-character\-sets\-dir=\fR\fB\fIpath\fR\fR
.sp
The directory where character sets are installed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: compress option
.\" compress option: mariadb-admin
\fB\-\-compress\fR,
\fB\-C\fR
.sp
Compress all information sent between the client and the server if both support compression\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: connect-timeout option
.\" connect-timeout option: mariadb-admin
\fB\-\-connect-timeout=\fR\fB\fItimeout\fR\fR
.sp
Equivalent to \fB\-\-connect_timeout\fR, see the end of this section\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: count option
.\" count option: mariadb-admin
\fB\-\-count=\fR\fB\fIN\fR\fR,
\fB\-c \fR\fB\fIN\fR\fR
.sp
The number of iterations to make for repeated command execution if the
\fB\-\-sleep\fR
option is given\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: debug option
.\" debug option: mariadb-admin
\fB\-\-debug[=\fR\fB\fIdebug_options\fR\fR\fB]\fR,
\fB\-# [\fR\fB\fIdebug_options\fR\fR\fB]\fR
.sp
Write a debugging log\&. A typical
\fIdebug_options\fR
string is 'd:t:o,\fIfile_name\fR'. The default is 'd:t:o,/tmp/mariadb-admin.trace'.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: debug-check option
.\" debug-check option: mariadb-admin
\fB\-\-debug\-check\fR
.sp
Check memory and open file usage at exit.\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: debug-info option
.\" debug-info option: mariadb-admin
\fB\-\-debug\-info\fR
.sp
Print debugging information and memory and CPU usage statistics when the program exits\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: default-auth option
.\" default-auth option: mariadb-admin
\fB\-\-default\-auth\fR
.sp
Default authentication client-side plugin to use\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: default-character-set option
.\" default-character-set option: mariadb-admin
\fB\-\-default\-character\-set=\fR\fB\fIcharset_name\fR\fR
.sp
Use
\fIcharset_name\fR
as the default character set\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: defaults-extra-file option
.\" defaults-extra-file option: mariadb-admin
\fB\-\-defaults\-extra\-file=\fR\fB\fIfilename\fR\fR
.sp
Set \fB\fIfilename\fR\fR as the file to read default options from after the global defaults files has been read\&.
Must be given as first option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: defaults-file option
.\" defaults-file option: mariadb-admin
\fB\-\-defaults\-file=\fR\fB\fIfilename\fR\fR
.sp
Set \fB\fIfilename\fR\fR as the file to read default options from, override global defaults files\&. Must be given as first option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: force option
.\" force option: mariadb-admin
\fB\-\-force\fR,
\fB\-f\fR
.sp
Do not ask for confirmation for the
drop \fIdb_name\fR
command\&. With multiple commands, continue even if an error occurs\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: host option
.\" host option: mariadb-admin
\fB\-\-host=\fR\fB\fIhost_name\fR\fR,
\fB\-h \fR\fB\fIhost_name\fR\fR
.sp
Connect to the MariaDB server on the given host\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: local option
.\" local option: mariadb-admin
\fB\-\-local\fR,
\fB\-l\fR
.sp
Suppress the SQL command(s) from being written to the binary log by using FLUSH LOCAL or enabling sql_log_bin=0 for the session\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.\" mariadb-admin: no-beep option
.\" no-beep option: mariadb-admin
\fB\-\-no\-beep\fR,
\fB\-b\fR
.sp
Suppress the warning beep that is emitted by default for errors such as a failure to connect to the server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: no-defaults option
.\" no-defaults option: mariadb-admin
\fB\-\-no\-defaults\fR
.sp
Do not read default options from any option file\&. This must be given as the first argument\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: password option
.\" password option: mariadb-admin
\fB\-\-password[=\fR\fB\fIpassword\fR\fR\fB]\fR,
\fB\-p[\fR\fB\fIpassword\fR\fR\fB]\fR
.sp
The password to use when connecting to the server\&. If you use the short option form (\fB\-p\fR), you
\fIcannot\fR
have a space between the option and the password\&. If you omit the
\fIpassword\fR
value following the
\fB\-\-password\fR
or
\fB\-p\fR
option on the command line,
\fBmariadb-admin\fR
prompts for one\&.
.sp
Specifying a password on the command line should be considered insecure\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: pipe option
.\" pipe option: mariadb-admin
\fB\-\-pipe\fR,
\fB\-W\fR
.sp
On Windows, connect to the server via a named pipe\&. This option applies only if the server supports named\-pipe connections\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: port option
.\" port option: mariadb-admin
\fB\-\-port=\fR\fB\fIport_num\fR\fR,
\fB\-P \fR\fB\fIport_num\fR\fR
.sp
The TCP/IP port number to use for the connection or 0 for default to,
in order of preference, my.cnf, $MYSQL_TCP_PORT, /etc/services, built-in default (3306)\&.
Forces --protocol=tcp when specified on the command line without other connection properties\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: print-defaults option
.\" print-defaults option: mariadb-admin
\fB\-\-print\-defaults\fR
.sp
Print the program argument list and exit\&. This must be given as the first argument\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: protocol option
.\" protocol option: mariadb-admin
\fB\-\-protocol={TCP|SOCKET|PIPE|MEMORY}\fR
.sp
The connection protocol to use for connecting to the server\&. It is useful when the other connection parameters normally would cause a protocol to be used other than the one you want\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: relative option
.\" relative option: mariadb-admin
\fB\-\-relative\fR,
\fB\-r\fR
.sp
Show the difference between the current and previous values when used with the
\fB\-\-sleep\fR
option\&. Currently, this option works only with the
extended\-status
command\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: shutdown-timeout option
.\" shutdown-timeout option: mariadb-admin
\fB\-\-shutdown\-timeout\fR\fB\fItimeout\fR\fR
.sp
Equivalent of \fB\-\-shutdown_timeout\fR, see the end of this section\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: silent option
.\" silent option: mariadb-admin
\fB\-\-silent\fR,
\fB\-s\fR
.sp
Exit silently if a connection to the server cannot be established\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: sleep option
.\" sleep option: mariadb-admin
\fB\-\-sleep=\fR\fB\fIdelay\fR\fR,
\fB\-i \fR\fB\fIdelay\fR\fR
.sp
Execute commands repeatedly, sleeping for
\fIdelay\fR
seconds in between\&. The
\fB\-\-count\fR
option determines the number of iterations\&. If
\fB\-\-count\fR
is not given,
\fBmariadb-admin\fR
executes commands indefinitely until interrupted\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: socket option
.\" socket option: mariadb-admin
\fB\-\-socket=\fR\fB\fIpath\fR\fR,
\fB\-S \fR\fB\fIpath\fR\fR
.sp
For connections to
localhost, the Unix socket file to use, or, on Windows, the name of the named pipe to use\&.
Forces --protocol=socket when specified on the command line without other connection properties; on Windows, forces --protocol=pipe\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL options
.\" SSL options: mariadb-admin
\fB\-\-ssl\fR
.sp
Enable SSL for connection (automatically enabled with other flags). Disable with
\fB\-\-skip-ssl\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL CA option
.\" SSL CA option: mariadb-admin
\fB\-\-ssl\-ca=\fIname\fR
.sp
CA file in PEM format (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL CA Path option
.\" SSL CA Path option: mariadb-admin
\fB\-\-ssl\-capath=\fIname\fR
.sp
CA directory (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL Cert option
.\" SSL Cert option: mariadb-admin
\fB\-\-ssl\-cert=\fIname\fR
.sp
X509 cert in PEM format (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL Cipher option
.\" SSL Cipher option: mariadb-admin
\fB\-\-ssl\-cipher=\fIname\fR
.sp
SSL cipher to use (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL Key option
.\" SSL Key option: mariadb-admin
\fB\-\-ssl\-key=\fIname\fR
.sp
X509 key in PEM format (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL Crl option
.\" SSL CRL option: mariadb-admin
\fB\-\-ssl\-crl=\fIname\fR
.sp
Certificate revocation list (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL Crlpath option
.\" SSL Crlpath option: mariadb-admin
\fB\-\-ssl\-crlpath=\fIname\fR
.sp
Certificate revocation list path (check OpenSSL docs, implies
\fB\-\-ssl\fR)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: SSL Verify Server Cert option
.\" SSL Verify Server Cert option: mariadb-admin
\fB\-\-ssl\-verify\-server\-cert\fR
.sp
Verify server's "Common Name" in its cert against hostname used when connecting. This option is disabled by default\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: TLS Version option
.\" TLS Version option: mariadb-admin
\fB\-\-tls\-version=\fR\fB\fIname\fR\fR,
.sp
Accepts a comma-separated list of TLS protocol versions\&. A TLS protocol version will only be enabled if it
is present in this list\&. All other TLS protocol versions will not be permitted\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: user option
.\" user option: mariadb-admin
\fB\-\-user=\fR\fB\fIuser_name\fR\fR,
\fB\-u \fR\fB\fIuser_name\fR\fR
.sp
The MariaDB user name to use when connecting to the server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: verbose option
.\" verbose option: mariadb-admin
\fB\-\-verbose\fR,
\fB\-v\fR
.sp
Verbose mode\&. Print more information about what the program does\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: version option
.\" version option: mariadb-admin
\fB\-\-version\fR,
\fB\-V\fR
.sp
Display version information and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: vertical option
.\" vertical option: mariadb-admin
\fB\-\-vertical\fR,
\fB\-E\fR
.sp
Print output vertically\&. This is similar to
\fB\-\-relative\fR, but prints output vertically\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: wait option
.\" wait option: mariadb-admin
\fB\-\-wait[=\fR\fB\fIcount\fR\fR\fB]\fR,
\fB\-w[\fR\fB\fIcount\fR\fR\fB]\fR
.sp
If the connection cannot be established, wait and retry instead of aborting\&. If a
\fIcount\fR
value is given, it indicates the number of times to retry\&. The default is one time\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" mariadb-admin: --wait-for-all-slaves option
.\" --wait-for-all-slaves option: mariadb-admin
\fB\-\-wait\-for\-all\-slaves\fR
.sp
Wait for the last binlog event to be sent to all connected slaves before shutting down\&.
This option is off by default\&.
.RE
.PP
You can also set the following variables by using
\fB\-\-\fR\fB\fIvar_name\fR\fR\fB=\fR\fB\fIvalue\fR\fR
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" connect_timeout variable
.\" timeout: connect_timeout variable
connect_timeout
.sp
The maximum number of seconds before connection timeout\&. The default value is 43200 (12 hours)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.\" shutdown_timeout variable
.\" timeout: shutdown_timeout variable
shutdown_timeout
.sp
The maximum number of seconds to wait for server shutdown\&. The default value is 3600 (1 hour)\&.
.RE
.SH "COPYRIGHT"
.br
.PP
Copyright 2007-2008 MySQL AB, 2008-2010 Sun Microsystems, Inc., 2010-2024 MariaDB Foundation
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335 USA or see http://www.gnu.org/licenses/.
.sp
.SH "SEE ALSO"
For more information, please refer to the MariaDB Knowledge Base, available online at https://mariadb.com/kb/
.SH AUTHOR
MariaDB Foundation (http://www.mariadb.org/).
