'\" t
.\"
.TH "\FBTOKUFT_LOGPRINT\FR" "1" "29 March 2019" "MariaDB 10\&.2" "MariaDB Database System"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH NAME
tokuft_logprint \- Dump the log from stdin to stdout 
.SH DESCRIPTION
Use: Dump the log from stdin to stdout\. Use \fBtokuft_logprint \-\-help\fR for details on usage\. 
.PP
For more information, please refer to the MariaDB Knowledge Base, available online at https://mariadb.com/kb/
