#define MSG_ACCESS_VIOLATN  "Access violation"
#define MSG_ACT_ALLOC_FAIL  "PlugInitLang: Activity allocation failed"
#define MSG_ADDVAL_ERROR    "Error %d in AddValue"
#define MSG_ADD_BAD_TYPE    "Array add value type mismatch (%s -> %s)"
#define MSG_ADD_NULL_DOM    "Adding string %s to a null domain"
#define MSG_ADPOS_IN_DICTP  "ADPOS to work in User_Dictp"
#define MSG_AFTER           " after: "
#define MSG_ALG_CHOICE_AUTO "Best algorithm choice is automatic"
#define MSG_ALG_CHOICE_BAD  "Bad algorithm choice value, reset to AUTO"
#define MSG_ALG_CHOICE_QRY  "Using Query algorithm"
#define MSG_ALG_CURLY_BRK   "Algorithm choice depends on outer curly brackets"
#define MSG_ALLOC_ERROR     "Error allocating %s"
#define MSG_ALL_DELETED     "All lines deleted in %.2lf sec"
#define MSG_ALTER_DB_ERR    "Cannot find the DB to alter"
#define MSG_AMBIG_COL_QUAL  "Ambiguous qualifier %s for column %s"
#define MSG_AMBIG_CORREL    "Select %s.* refers more than one table"
#define MSG_AMBIG_SPEC_COL  "Ambiguous special column %s"
#define MSG_ANSWER_TYPE     "Answer of type"
#define MSG_API_CONF_ERROR  "SQL Error: API_CONFORMANCE"
#define MSG_APPL_ACCESSIBLE "Application %s accessible"
#define MSG_APPL_ACTIVE     "Application %s still active"
#define MSG_APPL_BAD_SAVE   "Application %s may be incorrectly saved"
#define MSG_APPL_CREATED    "Application %s created"
#define MSG_APPL_IS_ACTIVE  "Application already active"
#define MSG_APPL_NOT_INIT   "Application not initialized"
#define MSG_APPL_NOT_LOADED "Application not loaded"
#define MSG_APPL_QUIT       "Application %s quit"
#define MSG_APPL_SAVED      "Application %s saved"
#define MSG_APP_STILL_ACTIV "Application of language %s still active (not freed)"
#define MSG_AREAFILE_NOTFND "Area file not found"
#define MSG_ARGS_SYNTAX_ERR "?SetArgs syntax error: unexpected %s after %s"
#define MSG_ARG_ALREADY_SET "Argument %d already set"
#define MSG_ARG_NOT_AN_ATTR "Argument is not an attribute (wrong pos-type %d)"
#define MSG_ARG_OUT_CONTEXT "@-type argument used out of context"
#define MSG_ARG_OUT_RANGE   "Phrase argument of value %d is out of range"
#define MSG_ARG_PTR_NOSEM   "Argument of value %d points to a nonterm having no Sem"
#define MSG_ARG_PTR_NOSEMS  "Argument of value %d points to a nonterm having no semantics"
#define MSG_ARG_REF_LOOP    "?Looping argument cross references"
#define MSG_ARG_TWO_CONST   "2nd argument of %s must be a constant"
#define MSG_ARRAY_ALLOC_ERR "Memory allocation error in ARRAY"
#define MSG_ARRAY_BNDS_EXCD "Array bounds exceeded"
#define MSG_ARRAY_ERROR     "Error while making array k=%d n=%d"
#define MSG_ATTRIBUTE_ERROR "Error rule %u attribute %s: "
#define MSG_ATT_NOT_CASE    "Attribute has wrong value %d (not a casevalue)"
#define MSG_ATT_POSCODE_BIG "Attribute poscode %d is too big (max=%d)"
#define MSG_AVGLEN_ERROR    "avglen should be between %d and %d"
#define MSG_BAD_AGGREG_FUNC "Unsupported aggregate function %d"
#define MSG_BAD_ARGTYPES    "Argument type invalid for %s"
#define MSG_BAD_ARGUMENTS   "Argument not attached for %s"
#define MSG_BAD_ARG_NUM     "Invalid number of arguments %d"
#define MSG_BAD_ARG_TYPE    "Bad argument type %d"
#define MSG_BAD_ARRAY_OPER  "Arrays must be used with the IN operator"
#define MSG_BAD_ARRAY_TYPE  "Illegal array type %d"
#define MSG_BAD_ARRAY_VAL   "Arrays must have the same number of values"
#define MSG_BAD_BIN_FMT     "Invalid format %c for the %s BIN column"
#define MSG_BAD_BLK_ESTIM   "Number of blocks exceeds estimate"
#define MSG_BAD_BLK_SIZE    "No match in block %d size"
#define MSG_BAD_BYTE_NUM    "bad number of bytes written"
#define MSG_BAD_BYTE_READ   "bad number of bytes read"
#define MSG_BAD_CARDINALITY "Invalid Cardinality call for multiple table"
#define MSG_BAD_CASE_SPEC   "Wrong case specification %c, enter new one: "
#define MSG_BAD_CHAR_SPEC   "Invalid character specification:'%s'"
#define MSG_BAD_CHECK_TYPE  "Invalid CheckColumn subtype %d"
#define MSG_BAD_CHECK_VAL   "Bad check setting '%s'"
#define MSG_BAD_COLCRT_ARG  "Bad COLCRT argument (type=%hd, domain=%hd)"
#define MSG_BAD_COLDEF_TYPE "Coldefs: wrong type %d"
#define MSG_BAD_COLIST_ITEM "Incorrect colist item"
#define MSG_BAD_COLIST_TYPE "Bad Colist type=%d"
#define MSG_BAD_COLSIZE     "Colsize %d is too small for this database"
#define MSG_BAD_COL_ENTRY   "Invalid entry for column %s"
#define MSG_BAD_COL_FORMAT  "Invalid column format type %d"
#define MSG_BAD_COL_IN_FILT "Incorrect column in filter"
#define MSG_BAD_COL_QUALIF  "Bad qualifier %s for column %s"
#define MSG_BAD_COL_TYPE    "Invalid type %s for column %s"
#define MSG_BAD_COL_XPATH   "Invalid Xpath in column %s for HTML table %s"
#define MSG_BAD_COMPARE_OP  "Bad compare op %d"
#define MSG_BAD_CONST_TYPE  "Bad constant type=%d"
#define MSG_BAD_CONV_TYPE   "Invalid convert type %d"
#define MSG_BAD_CORREL      "Select %s.* correlation refers no tables"
#define MSG_BAD_DATETIME    "Invalid datetime value"
#define MSG_BAD_DATE_OPER   "Unexpected date operator %d"
#define MSG_BAD_DBF_FILE    "DBF file %s is corrupted"
#define MSG_BAD_DBF_REC     "DBF file %s corrupted at record %d"
#define MSG_BAD_DBF_TYPE    "Unsupported DBF type %c"
#define MSG_BAD_DEF_ARG     "Bad INDEXDEF argument (type=%hd, domain=%hd)"
#define MSG_BAD_DEF_READ    "Unexpected EOF in deferred Read"
#define MSG_BAD_DEF_TYPE    "Invalid column definition type"
#define MSG_BAD_DIRECTORY   "Bad directory %s: %s"
#define MSG_BAD_DIST_JN_FIL "Invalid Distinct Join filter"
#define MSG_BAD_DIST_JOIN   "Invalid Distinct Join specification"
#define MSG_BAD_DOM_COL_DEF "Invalid column definitions for a domain"
#define MSG_BAD_DOM_VALUE   "%d is not a valid domain value"
#define MSG_BAD_EDIT_INIT   "Coparm: edition %s not properly initialized"
#define MSG_BAD_EVAL_TYPE   "Bad scalar function eval type=%d"
#define MSG_BAD_EXEC_MODE   "Bad execution mode '%s'"
#define MSG_BAD_EXP_ARGTYPE "Invalid expression argument type=%d"
#define MSG_BAD_EXP_OPER    "Bad expression operator=%d"
#define MSG_BAD_FETCH_RC    "Unexpected Fetch return code %d"
#define MSG_BAD_FIELD_FMT   "Invalid field format %c for %s"
#define MSG_BAD_FIELD_RANK  "Invalid field rank %d for column %s"
#define MSG_BAD_FIELD_TYPE  "Bad type field %s"
#define MSG_BAD_FILE_HANDLE "Invalid File Handle: %s"
#define MSG_BAD_FILE_LIST   "Bad Filelist section"
#define MSG_BAD_FILTER      "Bad filter: Opc=%d B_T=%d %d Type=%d %d"
#define MSG_BAD_FILTER_CONV "Bad filter conversion, B_T=%d,%d"
#define MSG_BAD_FILTER_LINK "Bad filter link operator %d"
#define MSG_BAD_FILTER_OP   "Invalid filter operator %d"
#define MSG_BAD_FILTEST_OP  "Invalid operator %d %d for FilTest"
#define MSG_BAD_FLD_FORMAT  "Bad format for field %d of %s"
#define MSG_BAD_FLD_LENGTH  "Field %s too long (%s --> %d) line %d of %s"
#define MSG_BAD_FLOAT_CONV  "Invalid convert of float array"
#define MSG_BAD_FPARM_NEXT  "Coparm: FPARM with non-null Next"
#define MSG_BAD_FREQ_SET    "Bad frequency setting for column %s"
#define MSG_BAD_FUNC_ARG    "Funcarg of type %d not implemented"
#define MSG_BAD_FUNC_ARGTYP "Bad Function argument type=%d"
#define MSG_BAD_FUNC_MODE   "%s: invalid mode %d"
#define MSG_BAD_GENRE       "Genre is invalid"
#define MSG_BAD_GETVIEW_RET "GetView: invalid return type %d"
#define MSG_BAD_HANDLE_VAL  "Invalid handle value"
#define MSG_BAD_HAV_FILTER  "Having filter found in a Vanilla query"
#define MSG_BAD_HAV_FILTYPE "Bad filter type for Having Clause"
#define MSG_BAD_HEADER      "File %s: Header corrupted"
#define MSG_BAD_HEADER_VAL  "Invalid header value %d"
#define MSG_BAD_HEAD_END    "Can't read end of header"
#define MSG_BAD_INDEX_COL   "Bad column %s for index %s"
#define MSG_BAD_INDEX_DEF   "Bad index definition for %s"
#define MSG_BAD_INDEX_FILE  "Wrong index file %s"
#define MSG_BAD_INDEX_PART  "Bad index part for %s"
#define MSG_BAD_INPUT       "Incorrect input"
#define MSG_BAD_IN_ARGTYPE  "Bad argument type for IN operator"
#define MSG_BAD_IN_ENDING   "Error: wrong end of IN string"
#define MSG_BAD_IN_STRING   "IN string begins or ends with invalid char %c ... %c"
#define MSG_BAD_JCOL_TYPE   "Logical JCT error: Unmatched column types"
#define MSG_BAD_JOIN_EXP    "Invalid expression used in join"
#define MSG_BAD_JOIN_FILTER "Improper join filter"
#define MSG_BAD_JOIN_OP     "Bad join operator %d"
#define MSG_BAD_LANG_SIZE   "Wrong Language file size %d"
#define MSG_BAD_LINEFLD_FMT "Bad format line %d field %d of %s"
#define MSG_BAD_LINE_LEN    "Line length not equal to Lrecl"
#define MSG_BAD_LIST_TYPE   "Invalid list type=%d"
#define MSG_BAD_LOCALE      "Invalid locale %s"
#define MSG_BAD_LOCDFON_ARG "Bad parameter for LOCDFON"
#define MSG_BAD_LOCNODE_USE "Unexpected use of LOCNODE"
#define MSG_BAD_LRECL       "Table/File lrecl mismatch (%d,%hd)"
#define MSG_BAD_MAX_HAVING  "MAXTMP value too small for Having"
#define MSG_BAD_MAX_NREC    "MaxRec=%d doesn't match MaxBlk=%d Nrec=%d"
#define MSG_BAD_MAX_PARAM   "Bad parameters for setting max value"
#define MSG_BAD_MAX_SETTING "Bad max setting '%c'"
#define MSG_BAD_MERGE_TYPE  "Type %d cannot be merged"
#define MSG_BAD_NODE_TYPE   "Bad type %d for table node"
#define MSG_BAD_OFFSET_VAL  "Invalid null offset value for a CSV table"
#define MSG_BAD_OPEN_MODE   "Invalid open mode %d"
#define MSG_BAD_OPERATOR    "Invalid operator %s"
#define MSG_BAD_ORDER_MODE  "Bad ordering mode %c"
#define MSG_BAD_ORDER_TYPE  "Type=%d invalid for order item"
#define MSG_BAD_OUTER_JOIN  "Invalid outer join on child table"
#define MSG_BAD_PAD_ARGTYP  "Bad argument type for Pad or Justify"
#define MSG_BAD_PARAMETERS  "%.8s: Bad parameters"
#define MSG_BAD_PARAM_TYPE  "%.8s: Bad parameter type=%d"
#define MSG_BAD_PARM_COUNT  "Parameter count mismatch"
#define MSG_BAD_PHASE_NUM   "Out of range phrase number %d"
#define MSG_BAD_PHRASE_NB   "out of range phrase number %d rc=%d\n"
#define MSG_BAD_POS_CODE    "Invalid POS code %d"
#define MSG_BAD_POS_TYPE    "Invalid POS code type %d"
#define MSG_BAD_PROJNUM     "Bad projnum %d for column %s"
#define MSG_BAD_QUERY_OPEN  "Query open invalid mode %d"
#define MSG_BAD_QUERY_TYPE  "Invalid query type %d for %s"
#define MSG_BAD_QUOTE_FIELD "Missing ending quote in %s field %d line %d"
#define MSG_BAD_READ_NUMBER "Wrong number %d of values read from %s"
#define MSG_BAD_RECFM       "Invalid recfm type %d for DOSCOL"
#define MSG_BAD_RECFM_VAL   "Bad Recfm value %d"
#define MSG_BAD_RESULT_TYPE "Bad result type %d for %s"
#define MSG_BAD_RETURN_TYPE "Bad returned type %d"
#define MSG_BAD_ROW_VALIST  "Invalid ROW list of values"
#define MSG_BAD_ROW_VALNB   "Number of values in list mismatch"
#define MSG_BAD_SCF_ARGTYPE "Argument %d type=%s invalid for %s"
#define MSG_BAD_SEM_DOMAIN  "Invalid domain .%d"
#define MSG_BAD_SETTINGS    "Some settings do not match table type"
#define MSG_BAD_SET_CASE    "Cannot set sensitive an insensitive array"
#define MSG_BAD_SET_STRING  "Invalid SetValue from string"
#define MSG_BAD_SET_TYPE    "Bad set type %hd"
#define MSG_BAD_SPECIAL_CMD "Ill formed special command"
#define MSG_BAD_SPECIAL_COL "Bad special column %s"
#define MSG_BAD_SPEC_COLUMN "Special column invalid for this table type"
#define MSG_BAD_SQL_PARAM   "Invalid SQL parameter for FindColblk"
#define MSG_BAD_SUBLST_TYPE "Coparm: bad sub-list type %d"
#define MSG_BAD_SUBSEL_IN_X "Bad sub-select in expression"
#define MSG_BAD_SUBSEL_TYPE "Bad Sub-Select returned type %d"
#define MSG_BAD_SUB_RESULT  "Undefined Sub-Select function result"
#define MSG_BAD_SUB_SELECT  "Bad sub-select in function argument"
#define MSG_BAD_TABLE_LINE  "Illegal or truncated line '%s' in Tables section"
#define MSG_BAD_TABLE_LIST  "Table %s not found in table list"
#define MSG_BAD_TABLE_TYPE  "Bad type %s for table %s"
#define MSG_BAD_TEST_TYPE   "Array BlockTest type mismatch %s %s"
#define MSG_BAD_TRIM_ARGTYP "Bad argument type for Trim"
#define MSG_BAD_TYPE_FOR_IN "Arg type mismatch for IN function"
#define MSG_BAD_TYPE_FOR_S  "Incorrect type %d for %s(%d)"
#define MSG_BAD_TYPE_LIKE   "Bad operand(%d) type=%d for LIKE"
#define MSG_BAD_UPD_COR     "Qualifier %s of column %s not related to the updated table %s"
#define MSG_BAD_USERBLK_LEN "User block write length error"
#define MSG_BAD_USETEMP     "Bad usetemp setting '%s'"
#define MSG_BAD_USETEMP_VAL "Bad Usetemp value %d"
#define MSG_BAD_VALBLK_INDX "Out of range valblock index value"
#define MSG_BAD_VALBLK_TYPE "Invalid value block type %d"
#define MSG_BAD_VALNODE     "Bad type %d for column %s value node"
#define MSG_BAD_VALUE_TYPE  "Invalid value type %d"
#define MSG_BAD_VAL_UPDATE  "Don't know which %s value to update"
#define MSG_BAD_VIEW_OPEN   "View open invalid mode %d"
#define MSG_BAD_XMODE_VAL   "Bad execution mode %d"
#define MSG_BAD_XOBJ_TYPE   "Bad Xobject type %d"
#define MSG_BAS_NS_LIST     "Invalid namespaces list format"
#define MSG_BIN_F_TOO_LONG  "Value too long for field %s (%d --> %d)"
#define MSG_BIN_MODE_FAIL   "Set binary mode failed: %s"
#define MSG_BLKTYPLEN_MISM  "Non matching block types/lengths in SetValue"
#define MSG_BLK_IS_NULL     "Blk is NULL"
#define MSG_BLOCK_NO_MATCH  "Non matching block"
#define MSG_BREAKPOINT      "Breakpoint"
#define MSG_BUFF_TOO_SMALL  "GetColData: Buffer is too small"
#define MSG_BUFSIZE_ERROR   "Error getting screen buffer size"
#define MSG_BUILDING_GROUPS "Building groups"
#define MSG_BUILD_DIST_GRPS "Building groups distinct"
#define MSG_BUILD_INDEX     "Building index %s on %s"
#define MSG_BXP_NULL        "Bxp NULL in PUTFON"
#define MSG_CANNOT_OPEN     "Cannot open %s"
#define MSG_CD_ONE_STEP     "Count Distinct must be processed in one step"
#define MSG_CD_ORDER_ERROR  "Ordering error in Count Distinct"
#define MSG_CHECKING_ROWS   "Checking rows to update"
#define MSG_CHECK_LEVEL     "Checking level reset to %u"
#define MSG_CHSIZE_ERROR    "chsize error: %s"
#define MSG_CLN_NOT_IN_JOIN "Column C%d not found in join"
#define MSG_CNTDIS_COL_LOST "Count Distinct column lost"
#define MSG_COLIST_BAD_TYPE "Invalid Colist element type=%d"
#define MSG_COLNAM_TOO_LONG "Column name too long"
#define MSG_COLSEC_TOO_BIG  "Column section too big in table %s (%d)"
#define MSG_COLS_REDUCED    " (reduced by Maxcol)"
#define MSG_COLUMN_ERROR    "Column error"
#define MSG_COLUMN_MISMATCH "Column %s mismatch"
#define MSG_COLUMN_NOT_KEY  "Join column R%d.%s is not a key"
#define MSG_COL_ALLOC_ERR   "Cannot allocate column node"
#define MSG_COL_ALLOC_ERROR "Memory allocation error for column %d"
#define MSG_COL_HAS_NO_DEF  "Column %s has no definition"
#define MSG_COL_INVAL_TABLE "Column %s.%s not found in table %s alias %s"
#define MSG_COL_ISNOT_TABLE "Column %s is not in table %s"
#define MSG_COL_NB_MISM     "Number of columns mismatch"
#define MSG_COL_NOTIN_GRPBY "Column %s not in Group By list"
#define MSG_COL_NOTIN_TABLE "Column %s is not in any table"
#define MSG_COL_NOTIN_UPDT  "%s does not belong to the updated table %s"
#define MSG_COL_NOT_CODED   "Column %s is not coded"
#define MSG_COL_NOT_EXIST   "Column %s is not in table %s"
#define MSG_COL_NOT_FOUND   "Column %s does not exist in %s"
#define MSG_COL_NOT_IN_DB   "Column %s of table %s not in DB"
#define MSG_COL_NOT_IN_JOIN "Column %s not found in join"
#define MSG_COL_NOT_SORTED  "Column %s of table %s is not sorted"
#define MSG_COL_NUM_MISM    "Number of columns mismatch"
#define MSG_COL_USED_TWICE  "Column %s linked twice ???"
#define MSG_COMPUTE_ERROR   "Error in Compute, op=%d"
#define MSG_COMPUTE_NIY     "Compute not implemented for token strings"
#define MSG_COMPUTING       "Computing"
#define MSG_COMPUTING_DIST  "Computing Distinct"
#define MSG_COMPUTING_FUNC  "Computing function(s)"
#define MSG_COM_ERROR       "Com error"
#define MSG_CONCAT_SUBNODE  "Cannot concatenate sub-nodes"
#define MSG_CONNECTED       "Connected"
#define MSG_CONNECT_CANCEL  "Connection cancelled by user"
#define MSG_CONNECT_ERROR   "Error %d connecting to %s"
#define MSG_CONN_CLOSED     "%s(%d) closed"
#define MSG_CONN_CREATED    "Connection %s created"
#define MSG_CONN_DROPPED    "Connection %s dropped"
#define MSG_CONN_OPEN       "%s(%d) open (%s)"
#define MSG_CONN_SUC_OPEN   "%s(%d) successfully open"
#define MSG_CONTROL_C_EXIT  "Control C exit"
#define MSG_COPY_BAD_PHASE  "List copy invalid in phase %d"
#define MSG_COPY_INV_TYPE   "Coparm: type not supported %d"
#define MSG_CORREL_NO_QRY   "Correlated subqueries cannot be of QRY type"
#define MSG_CREATED_PLUGDB  " Created by PlugDB %s "
#define MSG_CURSOR_SET      "Cursor set to %d"
#define MSG_DATABASE_ACTIVE "Database %s activated"
#define MSG_DATABASE_LOADED "Database %s loaded"
#define MSG_DATA_IS_NULL    "ExecSpecialCmd: data is NULL"
#define MSG_DATA_MISALIGN   "Datatype misalignment"
#define MSG_DBASE_FILE      "dBASE dbf file: "
#define MSG_DB_ALREADY_DEF  "Database %s already defined"
#define MSG_DB_ALTERED      "Database altered"
#define MSG_DB_CREATED      "Database %s created"
#define MSG_DB_NOT_SPEC     "Database not specified"
#define MSG_DB_REMOVED      "Database %s removed from DB list"
#define MSG_DB_SORT_ERROR   "Error in DB sort"
#define MSG_DB_STOPPED      "Database %s stopped"
#define MSG_DEBUG_NOT_ACTIV "Debug is not active"
#define MSG_DEBUG_SET_INV   "Invalid Debug set %c"
#define MSG_DEF_ALLOC_ERROR "Error allocating %s DEF class"
#define MSG_DELETING_ROWS   "Deleting rows"
#define MSG_DEL_FILE_ERR    "Error deleting %s"
#define MSG_DEL_READ_ERROR  "Delete: read error req=%d len=%d"
#define MSG_DEL_WRITE_ERROR "Delete: write error: %s"
#define MSG_DEPREC_FLAG     "Deprecated option Flag, use Coltype"
#define MSG_DICTIONARY      "Dictionary "
#define MSG_DIRECT_VARTOK   "Direct access of variable token rules not implemented"
#define MSG_DISCONNECTED    "Disonnected"
#define MSG_DISTINCT_ERROR  "More than one DISTINCT functional item"
#define MSG_DISTINCT_ROWS   "Selecting distinct rows"
#define MSG_DISTINCT_VALUES "Retrieving distinct values"
#define MSG_DIS_NOHEAD_JOIN "Distinct join on not heading table"
#define MSG_DLL_LOAD_ERROR  "Error %d loading module %s"
#define MSG_DOMAIN_EMPTY    "Domain %s is empty"
#define MSG_DOMAIN_ERROR    "Column %s domain(%s)/value(%s) mismatch"
#define MSG_DOMAIN_FULL     "Domain %s is full (max=%d)"
#define MSG_DOM_FILE_ERROR  "Domain file %s not found"
#define MSG_DOM_NOT_SUPP    "MS-DOM not supported by this version"
#define MSG_DOM_OPEN_ERROR  "Domain open error: %s"
#define MSG_DOM_READ_ERROR  "Domain read error %d: %s"
#define MSG_DOM_READ_ONLY   "Domain table %s is read only"
#define MSG_DOM_WRITE_ERROR "Domain write error %d: %s"
#define MSG_DONE            "Done, rc=%d"
#define MSG_DOSALMEM_NOMEM  "Memory Allocation failed, not enough memory"
#define MSG_DROP_DB_ERR     "Drop database %s failed"
#define MSG_DSORT_LOG_ERROR "Logical error in Kindex distinct Sort"
#define MSG_DUMMY_NO_COLS   "Dummy tables must have no columns"
#define MSG_DUPLICAT_COUNT  "Count on more than one column"
#define MSG_DUP_COL_NAME    "Duplicate column name %s"
#define MSG_DUP_PROJNUM     "Duplicated projnum %d for column %s"
#define MSG_DVAL_NOTIN_LIST "Value %s not found in distinct values list of column %s"
#define MSG_EMPTY_DOC       "Empty document"
#define MSG_EMPTY_FILE      "%s empty file %s: "
#define MSG_ENDSTR_MISMATCH "No match between end of string and end of node"
#define MSG_END_OF_DELETE   "%d line(s) deleted in %.2lf sec"
#define MSG_END_OF_INSERT   "%d line(s) inserted in %.2lf sec"
#define MSG_END_OF_QUERY    "%d line(s) retrieved in %.2lf sec"
#define MSG_END_OF_UPDATE   "%d line(s) updated in %.2lf sec"
#define MSG_EOF_AFTER_LINE  "EOF after line %d"
#define MSG_EOF_INDEX_FILE  "EOF while reading index file"
#define MSG_ERASED          " and erased"
#define MSG_ERASE_FAILED    " (erase failed)"
#define MSG_ERROR           "Error"
#define MSG_ERROR_IN_LSK    "Error %d in lseek64"
#define MSG_ERROR_IN_SFP    "Error %d in SetFilePointer"
#define MSG_ERROR_NO_PARM   "No parameter (valid only with %.8s.1 and %.8s.5)"
#define MSG_ERROR_OPENING   "Error opening: "
#define MSG_ERR_NUM_GT_MAX  "Error: Numval (%d) greater than Maxnum (%d)"
#define MSG_ERR_READING_REC "Error reading record %d of %s"
#define MSG_ERR_RET_RULE    "error return, rule=%u"
#define MSG_ERR_RET_TYPE    "error return, type=%d"
#define MSG_EVAL_EXPIRED    "Evaluation version expired"
#define MSG_EVAL_ONLY       "I agree to use this Dll for evaluation purpose only"
#define MSG_EXECUTING       "Executing"
#define MSG_EXECUTION_ERROR "Execution error"
#define MSG_EXEC_MODE_IS    "Execution mode is %s"
#define MSG_EXEC_MODE_RESET ". Mode reset to Execute"
#define MSG_EXEC_MODE_SET   "Execution mode set to %s"
#define MSG_EXIT_EVAL_ERR   "Error evaluating Exit"
#define MSG_EXIT_FROM_LANG  "Exit from language %s version %d.%d"
#define MSG_FAIL_ADD_NODE   "Failed to add %s table node"
#define MSG_FETCHING_DATA   "Fetching data"
#define MSG_FETCHING_ROWS   "Fetching rows"
#define MSG_FETCH_NO_RES    "Fetch: No Result Set"
#define MSG_FIELD_TOO_LONG  "Value too long for field %d line %d"
#define MSG_FILELEN_ERROR   "Error in %s for %s"
#define MSG_FILE_CLOSE_ERR  "Error %d occurred closing the file"
#define MSG_FILE_IS_EMPTY   "File %s is empty"
#define MSG_FILE_MAP_ERR    "File mapping error"
#define MSG_FILE_MAP_ERROR  "CreateFileMapping %s error rc=%d"
#define MSG_FILE_NOT_FOUND  "File %s cannot be found"
#define MSG_FILE_OPEN_YET   "File %s already open"
#define MSG_FILE_UNFOUND    "File %s not found"
#define MSG_FILGRP_NO_TABLE "Missing table %d for a filter group"
#define MSG_FILTER_ATTACH   "Filter passed to Attach"
#define MSG_FILTER_NO_TABLE "Missing first table for a filter"
#define MSG_FIND_BAD_TYPE   "Array Find type mismatch %s %s"
#define MSG_FIX_OVFLW_ADD   "Fixed Overflow on add"
#define MSG_FIX_OVFLW_TIMES "Fixed Overflow on times"
#define MSG_FIX_UNFLW_ADD   "Fixed Underflow on add"
#define MSG_FIX_UNFLW_TIMES "Fixed Underflow on times"
#define MSG_FLD_TOO_LNG_FOR "Field %d too long for %s line %d of %s"
#define MSG_FLTST_NO_CORREL "FilTest should be called only for correlated subqueries"
#define MSG_FLT_BAD_RESULT  "Float inexact result"
#define MSG_FLT_DENORMAL_OP "Float denormal operand"
#define MSG_FLT_INVALID_OP  "Float invalid operation"
#define MSG_FLT_OVERFLOW    "Float overflow"
#define MSG_FLT_STACK_CHECK "Float stack check"
#define MSG_FLT_UNDERFLOW   "Float underflow"
#define MSG_FLT_ZERO_DIVIDE "Float divide by zero"
#define MSG_FMT_WRITE_NIY   "Writing %s files is not implemented yet"
#define MSG_FNC_NOTIN_SLIST "Order aggregate function not in select list"
#define MSG_FORMAT_ERROR    "Formating error"
#define MSG_FOXPRO_FILE     "FoxPro file: "
#define MSG_FPUTS_ERROR     "fputs error: %s"
#define MSG_FSBPARP_NULL    "PUTFON: fsbparp is NULL"
#define MSG_FSEEK_ERROR     "fseek error: %s"
#define MSG_FSETPOS_ERROR   "fseek error for i=%d"
#define MSG_FTELL_ERROR     "ftell error for recd=%d: %s"
#define MSG_FUNCTION_ERROR  "%s error: %d"
#define MSG_FUNC_ERRNO      "Error %d in %s"
#define MSG_FUNC_ERROR      "Error in %s"
#define MSG_FUNC_ERR_S      "%s error: %s"
#define MSG_FUNC_REF_DEL    "Reference to a defined function (rule %d) which has been deleted"
#define MSG_FWRITE_ERROR    "fwrite error: %s"
#define MSG_GETCWD_ERR_NO   "?getcwd %s errno=%d"
#define MSG_GETFILESIZE_ERR "Error %d in GetFileSize"
#define MSG_GET_DIST_VALS   "Retrieving distinct values from "
#define MSG_GET_ERROR       "Error in %s (column %d)"
#define MSG_GET_FUNC_ERR    "Error getting function %s: %s"
#define MSG_GET_NAME_ERR    "Error getting SYS table names"
#define MSG_GLOBAL_ERROR    "Cannot allocate Global (size=%d)\n"
#define MSG_GRAM_ALLOC_ERR  "Allocation error in Grammar Up"
#define MSG_GRAM_MISMATCH   "Warning: GRAMMAR version mismatch (saved under GRAMMAR v%u)"
#define MSG_GRAM_SUBSET_ERR "Grammar dictionary Subset error"
#define MSG_GRBY_TAB_NOTIMP "Group by filtered joined table not implemented"
#define MSG_GROUPBY_NOT_ALL "Group By must include all non-functional select items"
#define MSG_GROUP_ON_FUNC   "Invalid group by on functional column"
#define MSG_GRP_COL_MISM    "Column mismatch in groups"
#define MSG_GRP_LIST_MISMAT "Grouping does not match select list"
#define MSG_GUARD_PAGE      "Guard page violation"
#define MSG_GZOPEN_ERROR    "gzopen %s error %d on %s"
#define MSG_GZPUTS_ERROR    "gzputs error: %s"
#define MSG_HANDLE_IS_NULL  "%s is NULL: last error: %d"
#define MSG_HARRY_COMP_NIY  "Compute not implemented for coded strings"
#define MSG_HAVING_FILTER   "Filtering by Having"
#define MSG_HBUF_TOO_SMALL  "Buffer(%d) too small for header(%d)"
#define MSG_HEAD_OPEN_ERROR "Error opening header file %s"
#define MSG_HEAD_READ_ERROR "Error reading header file %s"
#define MSG_HEAD_WRITE_ERR  "Error writing header file %s"
#define MSG_HI_OFFSET_ERR   "High offet is not 0"
#define MSG_HUGE_DEFAULT    "Huge defaults to %d"
#define MSG_HUGE_WARNING_1  "Huge memory not 16-bit compatible for %d\n"
#define MSG_HUGE_WARNING_2  "Unpredictable results may occur\n"
#define MSG_IDLE            "Idle"
#define MSG_ILLEGAL_INSTR   "Illegal instruction"
#define MSG_ILL_FILTER_CONV "Filtering implies an illegal conversion"
#define MSG_INDEX_CREATED   "Index %s created on %s"
#define MSG_INDEX_DEF_ERR   "Error storing index definition for %s"
#define MSG_INDEX_DROPPED   "Index %s dropped from %s"
#define MSG_INDEX_INIT_ERR  "Cannot initialize index %s"
#define MSG_INDEX_NOT_DEF   "Index %s has no definition"
#define MSG_INDEX_NOT_UNIQ  "Index is not unique"
#define MSG_INDEX_ONE_SAVE  "Indexes are saved in one unique file"
#define MSG_INDEX_SEP_SAVE  "Indexes are saved in separate files"
#define MSG_INDEX_YET_ON    "Index %s already exists on %s"
#define MSG_INDX_ALL_DROP   "All indexes dropped from %s"
#define MSG_INDX_COL_NOTIN  "Index column %s is not in table %s"
#define MSG_INDX_EXIST_YET  "Index entry already exists"
#define MSG_INIT_ERROR      "Error initializing %s"
#define MSG_INIT_FAILED     "Failed to initialize %s processing"
#define MSG_INPUT           "Input: "
#define MSG_INPUT_KEYBD_YET "Input already from keyboard"
#define MSG_INSERTING       "Inserting: "
#define MSG_INSERT_ERROR    "Insert error: file %s in use"
#define MSG_INSERT_MISMATCH "Column/Value list mismatch"
#define MSG_INTERNAL        "internal"
#define MSG_INT_COL_ERROR   "Internal error for index column %s"
#define MSG_INT_OVERFLOW    "Integer overflow"
#define MSG_INT_ZERO_DIVIDE "Integer divide by zero"
#define MSG_INVALID_BIP     "Invalid Bip .%d"
#define MSG_INVALID_DISP    "Invalid disposition"
#define MSG_INVALID_FTYPE   "SBV: invalid Ftype %d"
#define MSG_INVALID_HANDLE  "Invalid handle"
#define MSG_INVALID_OPER    "Invalid operator %d for %s"
#define MSG_INVALID_OPTION  "Invalid option %s"
#define MSG_INV_COLUMN_TYPE "Invalid type %d for column %s"
#define MSG_INV_COL_DATATYP "Invalid Data Type %d for column %d"
#define MSG_INV_COL_NUM     "Invalid column %d"
#define MSG_INV_COL_TYPE    "Invalid column type %s"
#define MSG_INV_CONC_BIP    "Invalid bip (only valid are : %.8s.0  .1 and .5)"
#define MSG_INV_DATA_PATH   "Invalid database path %s"
#define MSG_INV_DEF_READ    "Invalid deferred Read rc=%d"
#define MSG_INV_DIRCOL_OFST "Invalid DIRCOL offset %d"
#define MSG_INV_DOMAIN_TYPE "Invalid type %d"
#define MSG_INV_FILTER      "Filter met in %s"
#define MSG_INV_FNC_BUFTYPE "FNC: invalid argument type %d for %s"
#define MSG_INV_INFO_TYPE   "Invalid catalog info type %d"
#define MSG_INV_INIPATH     "Invalid inipath "
#define MSG_INV_MAP_POS     "Invalid map position"
#define MSG_INV_OPERATOR    "invalid operator %d\n"
#define MSG_INV_PARAMETER   "Invalid parameter %s"
#define MSG_INV_PARM_TYPE   "Invalid parameter type"
#define MSG_INV_QUALIFIER   "Invalid qualifier '%s'"
#define MSG_INV_QUERY_TYPE  "Invalid query type %d"
#define MSG_INV_RAND_ACC    "Invalid random access to non optimized table"
#define MSG_INV_REC_POS     "Invalid record position"
#define MSG_INV_RESULT_TYPE "Invalid result type %s"
#define MSG_INV_SET_SUBTYPE "Invalid SetFormat subtype %d"
#define MSG_INV_SPECIAL_CMD "%s: Invalid special command"
#define MSG_INV_SUBTYPE     "Invalid subtype %s"
#define MSG_INV_TOK_DOMAIN  "Invalid token domain %s"
#define MSG_INV_TOPSEM_CMD  "Invalid TopSem command %c"
#define MSG_INV_TRANSF_USE  "Invalid use in transformation rule"
#define MSG_INV_TYPE_SPEC   "Invalid type specification (%.8s.%d)"
#define MSG_INV_UPDT_TABLE  "Table %s invalid for update"
#define MSG_INV_VALUE_LIST  "Invalid Insert value list"
#define MSG_INV_WHERE_JOIN  "Invalid where clause in join query"
#define MSG_INV_WORK_PATH   "Invalid work path %s"
#define MSG_IN_ARGTYPE_MISM "Argument type mismatch for IN expression"
#define MSG_IN_USE          " and in use"
#define MSG_IN_WITHOUT_SUB  "IN or EXISTS without array or subquery"
#define MSG_IS_NOT_CONN     "%s is not a connection definition"
#define MSG_JCT_MISS_COLS   "Missing columns for a JCT table"
#define MSG_JCT_MISS_TABLE  "Missing joined table for JCT"
#define MSG_JCT_NO_FILTER   "Virtual JCT tables cannot be filtered"
#define MSG_JCT_NO_KEY      "Logical JCT error: no key"
#define MSG_JOIN_KEY_NO_COL "Join key is not a column"
#define MSG_KEY_ALLOC_ERR   "Error allocating Key offset block"
#define MSG_KEY_ALLOC_ERROR "Memory allocation error, Klen=%d n=%d"
#define MSG_LANGUAGE_QUIT   "%s quit"
#define MSG_LANG_ACTIVE     "Language %s active"
#define MSG_LANG_ALLOC_FAIL "PlugInitLang: Lang block allocation failed"
#define MSG_LANG_ALREADY_UP "Edited language is already there"
#define MSG_LANG_BAD_SAVE   "Language %s may be incorrectly saved"
#define MSG_LANG_NOT_FREED  "Language %s cannot be freed (not in main chain)"
#define MSG_LANG_SAVED      "Language %s saved"
#define MSG_LANG_WR_LEN_ERR "Lang block write length error"
#define MSG_LDF_ALLOC_ERROR "LdfBlock allocation error"
#define MSG_LDF_RN_MISMATCH "LDF rule number mismatch"
#define MSG_LDF_WLEN_ERROR  "LdfData write length error"
#define MSG_LDF_W_LEN_ERROR "LdfData write length error"
#define MSG_LIC_NO_MYSQL    "Your current license does not enable using the MySQL table type"
#define MSG_LINEAR_ERROR    "Linearization error"
#define MSG_LINE_LENGTH     "Output line length reset to %d"
#define MSG_LINE_MAXLIN     "Max number of work lines reset to %d"
#define MSG_LINE_MAXRES     "Max number of output lines reset to %d"
#define MSG_LINE_MAXTMP     "Max number of intermediate lines reset to %d"
#define MSG_LINE_TOO_LONG   "New line is too long"
#define MSG_LINJOINDB_ERROR "System error: incorrect call to LinJoinDB"
#define MSG_LIST            "--List--"
#define MSG_LNG_NOT_IN_LIST "Language %s not found in attached list"
#define MSG_LOADING_DB      "Loading DB Description"
#define MSG_LOADING_FAILED  "Loading of %s failed"
#define MSG_LOAD_CDLL_ERROR "Error loading ConnDll: rc=%d"
#define MSG_LOCSTRG_TOO_BIG "LOCSTRG: n too big ? (%d)\n"
#define MSG_LOGICAL_ERROR   "%s: Logical error"
#define MSG_LRECL_TOO_SMALL "Lrecl too small (headlen = %d)"
#define MSG_MAC_NO_DELETE   "Delete not enabled for MAC tables"
#define MSG_MAC_NO_INDEX    "No direct access to MAC tables"
#define MSG_MAC_READ_ONLY   "MAC tables are read only"
#define MSG_MAC_WIN_ONLY    "MAC tables are Windows only"
#define MSG_MAKE_EMPTY_FILE "Making empty file %s: %s"
#define MSG_MAKING          "Making"
#define MSG_MAKING_DISTINCT "Making distinct groups"
#define MSG_MALLOC_ERROR    "Memory allocation failed: %s returned Null"
#define MSG_MALLOC_NULL     "malloc returned Null"
#define MSG_MAP_NO_MORE     "Type %s no more supported"
#define MSG_MAP_OBJ_ERR     "Error %d occurred closing the mapping object"
#define MSG_MAP_VEC_ONLY    "MAP Insert is for VEC Estimate tables only"
#define MSG_MAP_VIEW_ERROR  "MapViewOfFile %s error rc=%d"
#define MSG_MAXSIZE_ERROR   "Cannot calculate max size on open table"
#define MSG_MAXTMP_TRUNCATE "Intermediate results truncated by maxtmp=%d"
#define MSG_MAX_BITMAP      "Max opt bitmap size reset to %d"
#define MSG_MEMSIZE_TOO_BIG "Error: memsize (%d) too big for length (%d)"
#define MSG_MEM_ALLOC_ERR   "Memory allocation error, %s size=%d"
#define MSG_MEM_ALLOC_ERROR "Memory allocation error"
#define MSG_MEM_ALLOC_YET   "Memory already allocated"
#define MSG_METAFILE_NOTFND "Grammar Meta file not found"
#define MSG_MISPLACED_QUOTE "Misplaced quote in line %d"
#define MSG_MISSING         "Missing: Value=%p Argval=%p Builtin=%d"
#define MSG_MISSING_ARG     "Missing argument for operator %d"
#define MSG_MISSING_COL_DEF "Missing column definition"
#define MSG_MISSING_CONNECT "Missing connect string"
#define MSG_MISSING_EOL     "Missing endline character in %s"
#define MSG_MISSING_FIELD   "Missing field %d in %s line %d"
#define MSG_MISSING_FNAME   "Missing file name"
#define MSG_MISSING_NODE    "Missing %s node in %s"
#define MSG_MISSING_POS     "Missing POS code"
#define MSG_MISSING_ROWNODE "Can't find RowNode for row %d"
#define MSG_MISSING_SERV_DB "Missing server and/or database string"
#define MSG_MISS_LEAD_COL   "Missing leading index column %s"
#define MSG_MISS_NAME_LRECL "Missing file name and/or lrecl"
#define MSG_MISS_TABLE_LIST "Missing table list"
#define MSG_MISS_VCT_ELMT   "Missing VCT block size (Elements)"
#define MSG_MIS_TAG_LIST    "Missing column tag list"
#define MSG_MKEMPTY_NIY     "MakeEmptyFile: not yet implemented for Huge and Unix"
#define MSG_MOVE_INV_TYPE   "MOVPARM: Invalid parameter type %d"
#define MSG_MULT_DISTINCT   "Distinct is specified more than once"
#define MSG_MULT_KEY_ERROR  "Multiple key error k=%d n=%d"
#define MSG_MUL_MAKECOL_ERR "Tabmul MakeCol logical error"
#define MSG_MYSQL_CNC_OFF   "MySQL connection is closed"
#define MSG_MYSQL_CNC_ON    "MySQL connection is established"
#define MSG_MYSQL_NOT_SUP   "MySQL not supported by this version"
#define MSG_MY_CNC_ALREADY  "MySQL connection already active"
#define MSG_NAME_CONV_ERR   "Error converting node name"
#define MSG_NAME_IS_USED    "Name %s already in use"
#define MSG_NCOL_GT_MAXCOL  "Too many columns (%d > %d max)"
#define MSG_NEW_CHAR_NULL   "new char(%d) returned Null"
#define MSG_NEW_DOC_FAILED  "Cannot create new document"
#define MSG_NEW_RETURN_NULL "New returned Null in PlugEvalLike"
#define MSG_NEW_TABLE_ERR   "Unable to retrieve new table %s"
#define MSG_NEXT_FILE_ERROR "Couldn't find next file. rc=%d"
#define MSG_NODEF_FROM_VIEW "Cannot define a table from a view"
#define MSG_NODE_FOR_CHAR   "Node %s found when looking for character"
#define MSG_NODE_SUBSET_ERR "Node %d Subset error"
#define MSG_NONCONT_EXCEPT  "Noncontinuable exception"
#define MSG_NON_DUP_HAVING  "Having clause in non/dup functional query"
#define MSG_NON_EVAL_SEM    "Sem not evaluated: p_no=%d"
#define MSG_NOP_ZLIB_INDEX  "Cannot do indexing on non optimized zlib table"
#define MSG_NOT_A_DBF_FILE  "Not a dBASE dbf file "
#define MSG_NOT_ENOUGH_COLS "Not enough columns in %s"
#define MSG_NOT_ENOUGH_MEM  "Not enough memory to perform this operation"
#define MSG_NOT_FIXED_LEN   "File %s is not fixed length, len=%d lrecl=%d"
#define MSG_NOT_IMPLEMENTED "Not implemented: %.8s"
#define MSG_NOT_IMPL_JOIN   "Not implemented for Join"
#define MSG_NOT_IMPL_SET    "Not implemented for set operators"
#define MSG_NOT_IMPL_YET    "Not implemented yet"
#define MSG_NOT_LINEARIZED  "Table tree was not linearized"
#define MSG_NOT_MODIFIABLE  " (not modifiable)"
#define MSG_NO_0DH_HEAD     "No 0Dh at end of header (dbc=%d)"
#define MSG_NO_ACTIVE_APPL  "No active application"
#define MSG_NO_ACTIVE_DB    "No active database"
#define MSG_NO_ACTIVE_UDIC  "No active user dictionary"
#define MSG_NO_AGGR_FUNC    "Aggregated function %d not allowed here"
#define MSG_NO_AREA_FILE    "Area file not found"
#define MSG_NO_AVAIL_RESULT "No result available"
#define MSG_NO_BIG_DELETE   "Partial delete not yet implemented for Huge files"
#define MSG_NO_CHAR_FROM    "Cannot return char value from type %d"
#define MSG_NO_CLUSTER_COL  "No clustered columns"
#define MSG_NO_COL_ADDING   "Cannot add new column(s) to old definition"
#define MSG_NO_COL_DEF_AS   "Column definitions cannot be used with AS Select"
#define MSG_NO_COL_FOUND    "No column found in section %s"
#define MSG_NO_COL_IN_TABLE "Column %d not in table %s"
#define MSG_NO_COL_SECTION  "Missing column section for table %s"
#define MSG_NO_CONNECT_ADDR "No connexion address provided"
#define MSG_NO_CONST_FILTER "Constant filters not implemented"
#define MSG_NO_CURLY_BRKT   "No closing curly bracket"
#define MSG_NO_DATABASE     "Database %s not found"
#define MSG_NO_DATE_FMT     "No date format for valblock of type %d"
#define MSG_NO_DBF_INSERT   "Insert not supported yet for GDF files"
#define MSG_NO_DEF_FNCCOL   "Cannot find default function column"
#define MSG_NO_DEF_PIVOTCOL "Cannot find default pivot column"
#define MSG_NO_DIR_INDX_RD  "No direct access of %s tables"
#define MSG_NO_DMY_DIR_ACC  "No direct access of virtual DUMMY tables"
#define MSG_NO_DOM_DELETE   "Partial delete not yet implemented for domains"
#define MSG_NO_DOM_MATCH    "Unmatched string %.8s... in domain %s"
#define MSG_NO_EDITED_LANG  "Coparm: No active edited language"
#define MSG_NO_EXP_LINK     "Cannot use expression to link a JCT table"
#define MSG_NO_EXT_FILTER   "Filtering cannot refer to another table"
#define MSG_NO_EXT_UPDATE   "Cannot update with reference to another table"
#define MSG_NO_FEAT_SUPPORT "No %s support in this version"
#define MSG_NO_FILE_LIST    "Table %s has no file list"
#define MSG_NO_FLD_FORMAT   "Missing format for field %d of %s"
#define MSG_NO_FORMAT_COL   "Cannot format the type COLUMN"
#define MSG_NO_FORMAT_TYPE  "Cannot set format from type %d"
#define MSG_NO_FULL_JOIN    "Only Equi-join on key(s) is allowed by check setting"
#define MSG_NO_FUL_OUT_JOIN "Full outer joins are not supported"
#define MSG_NO_FUNC_ORDER   "Unsupported ordering on functional item"
#define MSG_NO_HEAD_JOIN    "Join on not heading table"
#define MSG_NO_HQL_CONV     "Conversion to HQL not available"
#define MSG_NO_INDEX        "No indexes on table %s"
#define MSG_NO_INDEX_GBX    "No or improper index for SQLGBX"
#define MSG_NO_INDEX_IN     "No indexes found in %s"
#define MSG_NO_INDEX_READ   "No indexed read for multiple tables"
#define MSG_NO_INIT_LANG    "No initial language"
#define MSG_NO_JOIN_TO_EXP  "No join to expressions"
#define MSG_NO_JOIN_UPDEL   "Update/Delete on MySQL table cannot be joined"
#define MSG_NO_KEY_COL      "No key columns found"
#define MSG_NO_KEY_UPDATE   "Cannot update key names"
#define MSG_NO_LANGUAGE     "No language in operation\n"
#define MSG_NO_LANG_TO_QUIT "No next language to quit"
#define MSG_NO_LISTVAL_HERE "LSTBLK: List of values used out of context"
#define MSG_NO_MAP_INSERT   "MAP incompatible with Insert"
#define MSG_NO_MATCHING_COL "No matching column %s in %s"
#define MSG_NO_MATCH_COL    "Cannot find matching column"
#define MSG_NO_MEMORY       "No memory"
#define MSG_NO_MEM_CORR_SUB "In memory correlated subquery not implemented yet"
#define MSG_NO_MODE_PADDED  "Mode not supported for padded files"
#define MSG_NO_MORE_COL     "Column %s no more in pivot table"
#define MSG_NO_MORE_LANG    "No more language, exit from %s\n"
#define MSG_NO_MORE_VAR     "VAR files no more supported"
#define MSG_NO_MULCOL_JOIN  "No join yet on muticolumn index"
#define MSG_NO_MULT_HAVING  "Multiple having clauses not implemented"
#define MSG_NO_MUL_DIR_ACC  "Direct access of multiple tables not implemented yet"
#define MSG_NO_MUL_VCT      "VCT tables cannot be multiple"
#define MSG_NO_MYSQL_CONN   "No open MySQL connection"
#define MSG_NO_MYSQL_DELETE "Delete should not be called for MySQL tables"
#define MSG_NO_NBCOL        "No NBcol"
#define MSG_NO_NBLIN        "No NBlin, MaxSize or Continued"
#define MSG_NO_NBLIN_CONT   "Fetch: No NBlin or Continued"
#define MSG_NO_NULL_CONST   "Cannot handle <null> constant"
#define MSG_NO_ODBC_COL     "Automatic ODBC columns not supported in this version"
#define MSG_NO_ODBC_DELETE  "Delete should not be called for ODBC tables"
#define MSG_NO_ODBC_DIRECT  "Direct access of ODBC tables not implemented yet"
#define MSG_NO_ODBC_MUL     "Multiple(2) not supported for ODBC tables"
#define MSG_NO_ODBC_SPECOL  "No ODBC special columns"
#define MSG_NO_OPT_COLUMN   "Not optimizable or no optimized columns"
#define MSG_NO_OP_MODIF     "Modificators do not apply to %s"
#define MSG_NO_PARAMETER    "No parameter"
#define MSG_NO_PART_DEL     "No partial delete of %s files"
#define MSG_NO_PART_MAP     "Partial mapping not implemented for this OS"
#define MSG_NO_PAR_BLK_INS  "Cannot insert partial block yet"
#define MSG_NO_PIV_DIR_ACC  "No direct access to PIVOT tables"
#define MSG_NO_POS_ADDED    "No Pos_code added"
#define MSG_NO_PROMPTING    "Cannot handle prompting for distributed tables"
#define MSG_NO_QRY_DELETE   "Delete cannot be used for QRY views"
#define MSG_NO_QUERY_ARRAY  "Array from QUERY not implemented yet"
#define MSG_NO_RCUR_DSK_YET "Recursive use of DISK not implemented yet"
#define MSG_NO_READ_32      "Can't read 32 bytes"
#define MSG_NO_RECOV_SPACE  "Cannot recover space in index file"
#define MSG_NO_REF_DELETE   "Cannot delete with reference to another table"
#define MSG_NO_REF_UPDATE   "Cannot update with reference to another table"
#define MSG_NO_REMOTE_FNC   "Cannot process some functions remotely"
#define MSG_NO_ROWID_FOR_AM "Can't get RowID in direct access for tables of type %s"
#define MSG_NO_ROW_NODE     "Row node name is not defined"
#define MSG_NO_SECTION_NAME "Missing section name"
#define MSG_NO_SEC_UPDATE   "Cannot update section names"
#define MSG_NO_SELECTED_DB  "No selected database"
#define MSG_NO_SELF_PIVOT   "Cannot pivot oneself!"
#define MSG_NO_SERVER_FOUND "No server found"
#define MSG_NO_SETPOS_YET   "%s SetPos not implemented yet"
#define MSG_NO_SFEXIT_UNIX  "Function %s not available on Unix"
#define MSG_NO_SOURCE       " (no source)"
#define MSG_NO_SPEC_COL     "No MySQL special columns"
#define MSG_NO_SQL_DELETE   "Delete cannot be currently used for SQL views"
#define MSG_NO_SUB_VAL      "No sub value for array of type %d"
#define MSG_NO_SUCH_INDEX   "No indexes %s on table %s"
#define MSG_NO_SUCH_SERVER  "cannot find the server %s"
#define MSG_NO_SUCH_TABLE   "Table %s not in DB"
#define MSG_NO_TABCOL_DATA  "No data found for table %s column %s"
#define MSG_NO_TABLE_COL    "No columns found for %s"
#define MSG_NO_TABLE_DEL    "Delete not enabled for %s tables   "
#define MSG_NO_TABLE_DESC   "No Table Description Block"
#define MSG_NO_TABLE_INDEX  "Table %s has no index"
#define MSG_NO_TABLE_LIST   "No table list"
#define MSG_NO_TAB_DATA     "No data found for table %s"
#define MSG_NO_TERM_IN_TOK  "Non terminal cannot be used in token rules"
#define MSG_NO_TOKEN_DB     "Cannot find DB for Token column %s"
#define MSG_NO_UNIX_CATINFO "No catalog info under Unix"
#define MSG_NO_UPDEL_JOIN   "Update/Delete on ODBC table cannot be joined"
#define MSG_NO_VCT_DELETE   "Partial delete not yet implemented for VCT files"
#define MSG_NO_VIEW_COLDEF  "No coldefs available for views"
#define MSG_NO_VIEW_SORT    "Cannot sort/join SQL functional view %s"
#define MSG_NO_ZIP_DELETE   "Delete Zip files not implemented yet"
#define MSG_NO_ZIP_DIR_ACC  "Direct access of ZDOS tables not implemented yet"
#define MSG_NULL_COL_VALUE  "Column Value block is NULL"
#define MSG_NULL_ENTRY      "InitLang, null entry %d %s"
#define MSG_NULL_QUERY      "Null query"
#define MSG_NUMVAL_NOMATCH  "Numval mismatch for %s"
#define MSG_N_FULL_PARSES   "%d full parses"
#define MSG_ODBC_READ_ONLY  "ODBC is currently read only"
#define MSG_OFFSET_NOT_SUPP "Offset not implemented for this type of sub query"
#define MSG_ONE_LANG_YET    "Already one language in edition"
#define MSG_ONE_PARAM_ONLY  "Only one parameter allowed"
#define MSG_ONLY_LOG10_IMPL "Only Log10 is implemented"
#define MSG_ON_LANGUAGE     "Language %.8s version %d.%d loaded for editing"
#define MSG_OPENING         "Opening"
#define MSG_OPENING_QUERY   "Opening query"
#define MSG_OPEN_EMPTY_FILE "Opening empty file %s: %s"
#define MSG_OPEN_ERROR      "Open error %d in mode %d on %s: "
#define MSG_OPEN_ERROR_IS   "Open error on %s: %s"
#define MSG_OPEN_ERROR_ON   "Open error on %s"
#define MSG_OPEN_MODE_ERROR "Open(%s) error %d on %s"
#define MSG_OPEN_SORT_ERROR "Logical sort error in QUERY Open"
#define MSG_OPEN_STRERROR   "open error: %s"
#define MSG_OPEN_W_ERROR    "Couldn't open %s for writing"
#define MSG_OPTBLK_RD_ERR   "Error reading opt block values: %s"
#define MSG_OPTBLK_WR_ERR   "Error writing opt block values: %s"
#define MSG_OPTIMIZING      "Optimizing "
#define MSG_OPT_BMAP_RD_ERR "Error reading opt bitmaps: %s"
#define MSG_OPT_BMAP_WR_ERR "Error writing opt bitmaps: %s"
#define MSG_OPT_CANCELLED   "Optimize cancelled by User"
#define MSG_OPT_DVAL_RD_ERR "Error reading distinct values: %s"
#define MSG_OPT_DVAL_WR_ERR "Error writing distinct values: %s"
#define MSG_OPT_HEAD_RD_ERR "Error reading opt file header: %s"
#define MSG_OPT_HEAD_WR_ERR "Error writing opt file header: %s"
#define MSG_OPT_INIT        "Optimization initialized"
#define MSG_OPT_LOGIC_ERR   "Logical error in SetBitmap, i=%d"
#define MSG_OPT_MAX_RD_ERR  "Error reading opt max values: %s"
#define MSG_OPT_MAX_WR_ERR  "Error writing opt max values: %s"
#define MSG_OPT_MIN_RD_ERR  "Error reading opt min values: %s"
#define MSG_OPT_MIN_WR_ERR  "Error writing opt min values: %s"
#define MSG_OPT_NOT_MATCH   "Non-matching opt file %s"
#define MSG_OP_RES_TOO_LONG "Result too long for operator=%d"
#define MSG_ORDER_OUT_RANGE "Order %d out of range"
#define MSG_ORDER_TWICE     "Ordering twice the same select item"
#define MSG_PAGE_ERROR      "In page error"
#define MSG_PARM_CNT_MISS   "Parameter count mismatch"
#define MSG_PARSE_NULL_SEM  "Parse with null semantics"
#define MSG_PARSING_QUERY   "Parsing query"
#define MSG_PIX_ERROR       "Pix %s error Rule_no=%u\n"
#define MSG_PIX_TEST_ERROR  "Rule=%u: pix-TEST not in first node\n"
#define MSG_PLG_READ_ONLY   "PLG is currently Read Only"
#define MSG_PLM_NULL_SFP    "TABPLM ReadDB: Sfp is NULL"
#define MSG_PLUG_NOT_INIT   "Plug was not initialized\n"
#define MSG_PLUG_NOT_RUN    "Plug is not running"
#define MSG_PNODE_RULE      "(P_node %d rule %d) "
#define MSG_POS_TOO_LONG    "%s too long (>%d)"
#define MSG_PREC_VBLP_NULL  "ARRAY SetPrecision: Vblp is NULL"
#define MSG_PRIV_INSTR      "Privileged instruction"
#define MSG_PROCADD_ERROR   "Error %d getting address of %s"
#define MSG_PROCESS_SUBQRY  "Processing Sub-Query"
#define MSG_PROC_WOULD_LOOP "Process would loop (maxres=%d maxlin=%d)"
#define MSG_PROGRESS_INFO   "Progress Information"
#define MSG_PROMPT_CANCEL   "Prompt was cancelled"
#define MSG_PROMPT_NIY      "Prompt not implemented for this configuration"
#define MSG_PTR_NOT_FOUND   "Pointer not found Num=%d ti1=%d"
#define MSG_PXDEF_IS_NULL   "Pxdef is NULL"
#define MSG_QRY_READ_ONLY   "QRY views are read only"
#define MSG_QUERY_CANCELLED "Query Cancelled by User"
#define MSG_QUERY_NOT_EXEC  "Query not executed"
#define MSG_QUERY_SAVED     "Query %s saved"
#define MSG_QUOTE_IN_QUOTE  "Quote char inside quoted field in line %d"
#define MSG_RANGE_NIY       "Range NIY for %s"
#define MSG_RANGE_NO_JOIN   "Range is not meant for join index"
#define MSG_RC_READING      "rc=%d reading table %s"
#define MSG_READB_BAD_INIT  "%s ReadDB called with Init=0"
#define MSG_READCOL_ERROR   "SQLCOL ReadColumn error"
#define MSG_READING         "Reading"
#define MSG_READING_FROM    "Reading from %s"
#define MSG_READING_RECORD  "Error reading record %d of %s"
#define MSG_READY           "Ready"
#define MSG_READ_ERROR      "Error reading %s: %s"
#define MSG_READ_ERROR_RC   "Read error, rc=%d"
#define MSG_READ_MEM_ERROR  "Reading memory %d: size=%d"
#define MSG_READ_ONLY       "Cannot modify this read/only protected table"
#define MSG_READ_SEEK_ERROR "Read seek error: %s"
#define MSG_READ_SEG_ERROR  "Reading segment %d: size=%d"
#define MSG_RECEIVED        "Received %c\n"
#define MSG_RECORD_ERROR    "Error reading record %d of %s"
#define MSG_RECORD_NO_SEP   "Record with no separator"
#define MSG_REC_SKIPPED     " (%d bad records skipped by MaxErr setting)"
#define MSG_REDUCE_INDEX    "Reducing index"
#define MSG_REGISTER_ERR    "Unable to register NS with prefix='%s' and href='%s'"
#define MSG_REMOTE_CONN_ERR "Remote connection failed"
#define MSG_REMOVE_ERROR    "Error removing %s: %s"
#define MSG_REMOVE_NOT_IMPL "Remove not implemented for non-table TDB"
#define MSG_RENAME_ERROR    "Error renaming %s to %s: %s"
#define MSG_RENUM_RULES     "Renumber rules and enter ADD again (rule saved in buffer)"
#define MSG_REORDER_INDEX   "Reordering index"
#define MSG_REQU_ARG_NUM    "Function %s requires %d arguments"
#define MSG_RESET_TO        "%s reset to %d"
#define MSG_RES_NOT_UNIQUE  "Result is not a unique value"
#define MSG_RET_FROM_LANG   "Return to language %s version %d.%d from language %s version %d.%d"
#define MSG_ROWID_NOT_IMPL  "RowNumber not implemented for tables of type %s"
#define MSG_ROWS_SELECTED   "%d rows selected in %.2lf sec"
#define MSG_ROWS_TRUNCATED  " (truncated by MAXRES, LIMIT, FREQ or AreaSize setting)"
#define MSG_ROW_ARGNB_ERR   "ROW arg number mismatch (%d,%d)"
#define MSG_RPC_SERVER_ERR  "RPC error, server not responding"
#define MSG_RSC_ALLOC_ERROR "Memory allocation error in Rescol %s"
#define MSG_RULE_ENTERED    "Rule %d entered"
#define MSG_RULE_SUBSET_ERR "Rules Subset error"
#define MSG_SAVING_INDEX    "Saving index file"
#define MSG_SCAN_NOT_IMP    "Scan not implemented"
#define MSG_SEC_KEY_FIRST   "Section and key names must come first on Insert"
#define MSG_SEC_NAME_FIRST  "Section name must come first on Insert"
#define MSG_SEC_NOT_FOUND   "Section %s not found in %s"
#define MSG_SEEK_ERROR      "Seek error in CopyHeader"
#define MSG_SEMANTIC_TREE   "Semantic Tree"
#define MSG_SEM_BAD_REF     "Sem name @%d refers to an argument of type not 0 or 1"
#define MSG_SEM_UNKNOWN     "unknown, rc=%d"
#define MSG_SEP_IN_FIELD    "Field %d contains the separator character"
#define MSG_SEQUENCE_ERROR  "Sequence error on statement allocation"
#define MSG_SETEOF_ERROR    "Error %d in SetEndOfFile"
#define MSG_SETRECPOS_NIY   "SetRecpos not implemented for this table type"
#define MSG_SET_LOCALE      "Locale set to %s"
#define MSG_SET_NULL_DOM    "Setting value %d to a null domain"
#define MSG_SET_OP_NOT_IMPL "sorry - set operators not implemented"
#define MSG_SET_STR_TRUNC   "SetValue: String would be truncated"
#define MSG_SEVERAL_TREES   "Some tables are not properly joined"
#define MSG_SFP_ERROR       "SetFilePointer error: %s"
#define MSG_SFUNC_NOT_IMPL  "Scalar Function %s not implemented"
#define MSG_SHARED_LIB_ERR  "Error loading shared library %s: %s"
#define MSG_SINGLE_STEP     "Single step"
#define MSG_SLEEP           "I slept %d milliseconds"
#define MSG_SMART_SORTING   "Retrieving sorted rows (pass %d of %d)"
#define MSG_SMART_SORT_ERR  "Logical Smart Sort Error 1"
#define MSG_SORTING         "Sorting"
#define MSG_SORTING_INDEX   "Sorting index"
#define MSG_SORTING_VAL     "Sorting %d values"
#define MSG_SORT_JOIN_INDEX "Sorting join index"
#define MSG_SPCOL_READONLY  "Special column %s is Read Only"
#define MSG_SPEC_CMD_SEP    "Special commands must be executed separately"
#define MSG_SQL_BAD_TYPE    "RephraseSQL: type %d not supported"
#define MSG_SQL_BLOCK_MISM  "CheckColumn: SQL current blocks mismatch"
#define MSG_SQL_CONF_ERROR  "SQL Error: SQL_CONFORMANCE"
#define MSG_SQL_READ_ONLY   "SQL views are currently read only"
#define MSG_SRCH_CLOSE_ERR  "Couldn't close search handle"
#define MSG_SRC_TABLE_UNDEF "Source table is not defined"
#define MSG_STACK_ERROR     "stack error, i=%d\n"
#define MSG_STACK_OVERFLOW  "Parser: Stack overflow\n"
#define MSG_STRG_NOT_FOUND  "String not found"
#define MSG_STRING_INV_LIST "List invalid for SemString"
#define MSG_STRING_TOO_BIG  "String too big for domain %s"
#define MSG_SUBALLOC_ERROR  "Not enough memory in area %p for request of %d (used=%d free=%d)"
#define MSG_SUBAL_HUGE_ERR  "Not enough memory in huge %p for request of %d"
#define MSG_SUBARG_NOSEM    "@ or sub-phrase arg of level %d points to a meaningless argument"
#define MSG_SUBARG_OUTRANGE "Out of range @ or sub-phrase argument of level %d"
#define MSG_SUBQRY_ONEITEM  "Sub-Query must have exactly one select item"
#define MSG_SUBSET_ERROR    "SubSet error in LoadDB"
#define MSG_SUB_OPEN_YET    "Subquery already open"
#define MSG_SUB_RES_TOO_LNG "Result too long for SUBSTR"
#define MSG_SYNTAX_ERROR    "Syntax error"
#define MSG_SYSTEM_ERROR    "System error %d"
#define MSG_S_ACCESS_DENIED "%s: access denied"
#define MSG_S_ERROR         "%s error"
#define MSG_S_ERROR_NUM     "%s: error=%d"
#define MSG_S_INTRUPT_ERROR "%s: interrupt error"
#define MSG_S_INVALID_PARM  "%s: invalid parameter"
#define MSG_S_INV_ADDRESS   "%s: invalid address"
#define MSG_S_UNKNOWN_ERROR "%s: unknown error code %u"
#define MSG_TABDIR_READONLY "DIR tables are read/only"
#define MSG_TABLE_ALREADY   "Table %s already exists"
#define MSG_TABLE_ALTERED   "%s table %s altered"
#define MSG_TABLE_CREATED   "%s table %s created"
#define MSG_TABLE_DROPPED   "Table %s dropped"
#define MSG_TABLE_MULT_JOIN "Table %s used more than once for join"
#define MSG_TABLE_NOT_IN_DB "Table %s does not exist in %s"
#define MSG_TABLE_NOT_OPT   "Not an optimizable table"
#define MSG_TABLE_NO_INDEX  "Table %s cannot be indexed"
#define MSG_TABLE_NO_OPT    "Table %s does not exist or type is not optimizable"
#define MSG_TABLE_READ_ONLY "%s tables are read only   "
#define MSG_TABMUL_READONLY "Multiple tables are read/only"
#define MSG_TAB_NOT_LOADED  " (some tables could not be loaded)"
#define MSG_TAB_NOT_SPEC    "No table specified"
#define MSG_TB_VW_NOTIN_DB  "Table or view %s not in DB"
#define MSG_TDB_NXT_NOT_NUL "Tdb.Next not NULL"
#define MSG_TDB_USE_ERROR   "Error, Tdbp->Use=%d"
#define MSG_TOO_MANY_COLS   "Too many columns"
#define MSG_TOO_MANY_COLTAB "Too many columns in %s (%d)"
#define MSG_TOO_MANY_FIELDS "Too many fields line %d of %s"
#define MSG_TOO_MANY_JUMPS  "Too many jump levels"
#define MSG_TOO_MANY_KEYS   "Too many keys (%d)"
#define MSG_TOO_MANY_POS    "Too many pos_codes"
#define MSG_TOO_MANY_TABLES "Too many tables (%d)"
#define MSG_TOPSEM_ERROR    "Unknown error in TopSem"
#define MSG_TO_BLK_IS_NULL  "To Blk is NULL"
#define MSG_TO_FTR_NOT_NULL "Set.To_Ftr is not null"
#define MSG_TO_PIX_NOT_NULL "Set.To_Pix is not null"
#define MSG_TO_SEM_NOT_NULL "Set.To_Sem is not null"
#define MSG_TRUNCATE_ERROR  "truncate error: %s"
#define MSG_TRUNC_BY_ESTIM  "truncated by Estimate"
#define MSG_TYPES_ERROR     "Error on Types(%d)"
#define MSG_TYPE_CONV_ERROR "Type cannot be converted in expression"
#define MSG_TYPE_DEF_MISM   "type and definition do not match"
#define MSG_TYPE_MISMATCH   "Key and source are not of the same type"
#define MSG_TYPE_RECFM_MISM "Type and Recfm mismatch"
#define MSG_TYPE_TO_VERIFY  "Type to verify: %d"
#define MSG_TYPE_VALUE_ERR  "Column %s type(%s)/value(%s) mismatch"
#define MSG_UNBALANCE_QUOTE "Unbalanced quote in line %d"
#define MSG_UNDEFINED_AM    "COLBLK %s: undefined Access Method"
#define MSG_UNDEFINED_PATH  "Undefined Plgcnx.ini path"
#define MSG_UNDEF_COL_COUNT "Count on undefined column"
#define MSG_UNKNOWN_DOMAIN  "Unknown domain %s"
#define MSG_UNKNOWN_ERROR   "Unknown error"
#define MSG_UNKNOWN_EXCPT   "Unknown exception"
#define MSG_UNKNOWN_NAME    "Unknown name: %.8s"
#define MSG_UNKNOWN_PATH    "Unknown Plgcnx.ini path"
#define MSG_UNKNOWN_POS     "Unknown pos name: %s"
#define MSG_UNKNOWN_SEM     "Unknown Sem %.8s, rc=%d"
#define MSG_UNKNOWN_SYNONYM "Unknown synonym"
#define MSG_UNKNW_QRY_TYPE  "ReadDB: unknown query type"
#define MSG_UNKN_ERR_CODE   "Unknown error code %d"
#define MSG_UNLOADABLE      " unloadable: "
#define MSG_UNLOADABLE_PRM  "%s unloadable: %s"
#define MSG_UNMATCH_FIL_ARG "Unmatched filter argument"
#define MSG_UNQ_COL_SEV_TAB "Unqualified column %s is in several tables"
#define MSG_UNRESOLVED_ARG  "?Unresolved argument %s at %d line %d"
#define MSG_UPDATE_ERROR    "Error updating %s"
#define MSG_UPDATING_ROWS   "Updating rows"
#define MSG_UPD_ZIP_NOT_IMP "Updating ZDOS tables not implemented yet"
#define MSG_UP_LANGUAGE     "Block language %.8s version %d level %d loaded"
#define MSG_USED_FREE_MEM   "%d used in sarea, %d free"
#define MSG_USETEMP_IS      "UseTemp is %s"
#define MSG_USETEMP_RESET   ". Usetemp reset to Auto"
#define MSG_USETEMP_SET     "UseTemp set to %s"
#define MSG_USE_NO_MATCH    "Use do not match : Use=%d, ti2=%d, ti3=%d"
#define MSG_USING_INDEX     " (Using index"
#define MSG_VALIST_MISMATCH "List of values mismatch"
#define MSG_VALSTR_TOO_LONG "Value %s too long for string of length %d"
#define MSG_VALTYPE_NOMATCH "Non matching Value types"
#define MSG_VALUE_ERROR     "Column %s: value is null"
#define MSG_VALUE_NOT_ALLOC "Value not allocated for column R%d %s"
#define MSG_VALUE_TOO_BIG   "Value %lld too big for column %s"
#define MSG_VALUE_TOO_LONG  "Value %s too long for column %s of length %d"
#define MSG_VAL_ALLOC_ERR   "Cannot allocate value node"
#define MSG_VAL_TOO_LONG    "Value field %s too long for %s"
#define MSG_VIEW_ALREADY    "View %s already exists"
#define MSG_VIEW_CREATED    "%s view %s created"
#define MSG_VIEW_DROPPED    "View %s dropped"
#define MSG_VIEW_NOT_IN_DB  "View %s does not exist in %s"
#define MSG_VIR_NO_DELETE   "Delete not allowed for %s tables"
#define MSG_VIR_READ_ONLY   "Virtual %s tables are read only"
#define MSG_VM_LANG         "Language has VM format, not supported"
#define MSG_VOID_FIRST_ARG  "First argument should not be void"
#define MSG_VOID_IN_STRING  "Error: void IN string"
#define MSG_VOID_ORDER_LIST "Null ordering list, system error ?"
#define MSG_VOID_POS_DICT   "Void Pos dictionary"
#define MSG_VOID_QUERY      "Void query %s"
#define MSG_WORK_AREA       "Work area: %s"
#define MSG_WORK_TOO_SMALL  "Work area too small, increase AreaSize"
#define MSG_WRITE_ERROR     "Error writing to %s"
#define MSG_WRITE_SEEK_ERR  "Write seek error: %s"
#define MSG_WRITE_STRERROR  "Error writing %s: %s"
#define MSG_WRITING         "Writing"
#define MSG_WRITING_ERROR   "Error writing to %s: %s"
#define MSG_WRITING_QUERY   "Writing query: "
#define MSG_WRONG_ARG_NUM   "Function %s does not take %d arguments"
#define MSG_WRONG_COL_NUM   "Column number %d out of range in %s"
#define MSG_WRONG_DB_LIST   "Wrong or nul database list"
#define MSG_WRONG_FUNCTION  "Wrong function %d"
#define MSG_WRONG_OP_PARM   "Wrong operator or parameters for %s"
#define MSG_WRONG_PARMS     "Wrong parameters for %s"
#define MSG_WRONG_PASSWORD  "Illegal password for %s"
#define MSG_WRONG_TYPE      "unsupported type"
#define MSG_WRONG_USERFILE  "Wrong Userfile size=%d"
#define MSG_WS_CONV_ERR     "Error converting %s to WS"
#define MSG_XCOL_MISMATCH   "Column %s mismatch in index"
#define MSG_XDB_DEL_ERROR   "Error while deleting entries from XDB file"
#define MSG_XFILE_READERR   "Error %d reading index file"
#define MSG_XFILE_TOO_SMALL "Index file is smaller than index length"
#define MSG_XFILE_WRITERR   "Error writing index file: %s"
#define MSG_XMLTAB_INIT_ERR "Error initializing XML table"
#define MSG_XML_INIT_ERROR  "Error initializing new XML file"
#define MSG_XPATH_CNTX_ERR  "Unable to create new XPath context"
#define MSG_XPATH_EVAL_ERR  "Unable to evaluate xpath location '%s'"
#define MSG_XPATH_NOT_SUPP  "Unsupported Xpath for column %s"
#define MSG_X_ARG_ADDED     "%d arguments have been added"
#define MSG_X_ARG_SET       "%d arguments have been set"
#define MSG_X_ON_TAB        " %s on %s("
#define MSG_ZERO_DIVIDE     "Zero divide in expression"
