/* The non-ASCII literal strings in this file are encoded in the iso-8859-1 / latin-1 character set
 * (https://en.wikipedia.org/wiki/ISO/IEC_8859-1) */
#define MSG_ACCESS_VIOLATN  "Violation acc\xe8s m\xe9moire"
#define MSG_ACT_ALLOC_FAIL  "PlugInitLang: Erreur d'allocation du bloc Activity"
#define MSG_ADDVAL_ERROR    "Erreur %d dans AddValue"
#define MSG_ADD_BAD_TYPE    "Ajout d'une valeur de type %s non conforme dans un tableau %s"
#define MSG_ADD_NULL_DOM    "Ajout de la cha\xeene %s \xe0 un domaine nul"
#define MSG_ADPOS_IN_DICTP  "ADPOS au travail dans User_Dictp"
#define MSG_AFTER           " apr\xe8s: "
#define MSG_ALG_CHOICE_AUTO "Le choix du meilleur algorithme est automatique"
#define MSG_ALG_CHOICE_BAD  "Choix d'algorithme invalide, remis \xe0 AUTO"
#define MSG_ALG_CHOICE_QRY  "Utilise l'algorithme 'Query'"
#define MSG_ALG_CURLY_BRK   "Le choix de l'algorithme d\xe9pend des accolades externes"
#define MSG_ALLOC_ERROR     "Erreur d'allocation de %s"
#define MSG_ALL_DELETED     "Toutes les lignes enlev\xe9""es en %.2lf sec"
#define MSG_ALTER_DB_ERR    "Impossible de d\xe9terminer la base de donn\xe9""es \xe0 modifier"
#define MSG_AMBIG_COL_QUAL  "Qualificateur ambigu %s pour la colonne %s"
#define MSG_AMBIG_CORREL    "Select %s.* corr\xe9lation ambigue"
#define MSG_AMBIG_SPEC_COL  "Colonne sp\xe9""ciale ambigu\xeb %s"
#define MSG_ANSWER_TYPE     "R\xe9ponse de type"
#define MSG_API_CONF_ERROR  "Erreur SQL: API_CONFORMANCE"
#define MSG_APPL_ACCESSIBLE "Application %s accessible"
#define MSG_APPL_ACTIVE     "Application %s encore active"
#define MSG_APPL_BAD_SAVE   "Application %s partiellement sauvegard\xe9""e"
#define MSG_APPL_CREATED    "Application %s cr\xe9""e"
#define MSG_APPL_IS_ACTIVE  "Application d\xe9j\xe0 active"
#define MSG_APPL_NOT_INIT   "Application non initialis\xe9""e"
#define MSG_APPL_NOT_LOADED "Application non charg\xe9""e"
#define MSG_APPL_QUIT       "Fin de l'application %s"
#define MSG_APPL_SAVED      "Application %s sauvegard\xe9""e"
#define MSG_APP_STILL_ACTIV "Application du langage %s encore active (non lib\xe9rable)"
#define MSG_AREAFILE_NOTFND "Fichier Area introuvable"
#define MSG_ARGS_SYNTAX_ERR "?SetArgs erreur de syntaxe: %s inattendu apr\xe8s %s"
#define MSG_ARG_ALREADY_SET "Argument %d d\xe9j\xe0 allou\xe9"
#define MSG_ARG_NOT_AN_ATTR "L'argument n'est pas un attribut (type %d erron\xe9)"
#define MSG_ARG_OUT_CONTEXT "Argument de type @ utilis\xe9 hors contexte"
#define MSG_ARG_OUT_RANGE   "Argument de phrase valant %d hors limite"
#define MSG_ARG_PTR_NOSEM   "Argument valant %d pointe sur un noeud sans Sem"
#define MSG_ARG_PTR_NOSEMS  "Argument valant %d pointe sur un noeud sans s\xe9mantique"
#define MSG_ARG_REF_LOOP    "?Bouclage entre r\xe9""f\xe9rences crois\xe9""es des arguments"
#define MSG_ARG_TWO_CONST   "Le 2\xe8me argument de %s doit \xeatre constant"
#define MSG_ARRAY_ALLOC_ERR "Erreur d'allocation m\xe9moire dans ARRAY"
#define MSG_ARRAY_BNDS_EXCD "Hors limite de tableau"
#define MSG_ARRAY_ERROR     "Erreur de fonctionnement k=%d n=%d"
#define MSG_ATTRIBUTE_ERROR "Erreur r\xe8gle %u attribut %s: "
#define MSG_ATT_NOT_CASE    "Mauvaise valeur %d pour attribut (pas une CaseValue)"
#define MSG_ATT_POSCODE_BIG "Code attribut %d trop grand (max=%d)"
#define MSG_AVGLEN_ERROR    "avglen doit \xeatre entre %d et %d"
#define MSG_BAD_AGGREG_FUNC "Fonction aggr\xe9g\xe9""e %d non support\xe9""e"
#define MSG_BAD_ARGTYPES    "Argument de type invalide pour %s"
#define MSG_BAD_ARGUMENTS   "Argument not attach\xe9s pour %s"
#define MSG_BAD_ARG_NUM     "Nombre d'arguments invalide %d"
#define MSG_BAD_ARG_TYPE    "Type d'argument %d invalide"
#define MSG_BAD_ARRAY_OPER  "Les tableaux doivent utiliser l'op\xe9rateur IN"
#define MSG_BAD_ARRAY_TYPE  "Type=%d invalide pour un tableau"
#define MSG_BAD_ARRAY_VAL   "Les tableaux doivent avoir le m\xeame nombre de valeurs"
#define MSG_BAD_BIN_FMT     "Format invalide %c pour la colonne BIN %s"
#define MSG_BAD_BLK_ESTIM   "Nombre de blocs sup\xe9rieur \xe0 l'estimation"
#define MSG_BAD_BLK_SIZE    "Taille du bloc %d non conforme"
#define MSG_BAD_BYTE_NUM    "Le nombre d'octets \xe9""crits est faux"
#define MSG_BAD_BYTE_READ   "Le nombre d'octets lus est faux"
#define MSG_BAD_CARDINALITY "Appel invalide de Cardinality pour une table multiple"
#define MSG_BAD_CASE_SPEC   "Min/Maj: sp\xe9""cification %c incorrecte, recommencez: "
#define MSG_BAD_CHAR_SPEC   "Sp\xe9""cification '%s' invalide pour caract\xe8re"
#define MSG_BAD_CHECK_TYPE  "Sous-type %d invalide pour CheckColumn"
#define MSG_BAD_CHECK_VAL   "Valeur pour Check invalide '%s'"
#define MSG_BAD_COLCRT_ARG  "COLCRT: Arg invalide (type=%hd, domain=%hd)"
#define MSG_BAD_COLDEF_TYPE "Coldefs: type ill\xe9gal %d"
#define MSG_BAD_COLIST_ITEM "El\xe9ment invalide dans une Colist"
#define MSG_BAD_COLIST_TYPE "Mauvais type=%d pour une Colist"
#define MSG_BAD_COLSIZE     "Colsize %d trop petit pour cette base de donn\xe9""es"
#define MSG_BAD_COL_ENTRY   "Entr\xe9""e invalide pour la colonne %s"
#define MSG_BAD_COL_FORMAT  "Type de formattage %d invalide pour une colonne"
#define MSG_BAD_COL_IN_FILT "Colonne incorrecte dans un filtre"
#define MSG_BAD_COL_QUALIF  "Qualificateur invalide %s pour la colonne %s"
#define MSG_BAD_COL_TYPE    "Type invalide %s pour la colonne %s"
#define MSG_BAD_COL_XPATH   "Xpath invalide colonne %s de la table HTML %s"
#define MSG_BAD_COMPARE_OP  "Op\xe9rateur de comparaison %d invalide"
#define MSG_BAD_CONST_TYPE  "Type=%d invalide pour une constante"
#define MSG_BAD_CONV_TYPE   "Convertion de type invalide %d"
#define MSG_BAD_CORREL      "Select %s.* corr\xe9lation absente"
#define MSG_BAD_DATETIME    "Valeur date/temps invalide"
#define MSG_BAD_DATE_OPER   "Op\xe9rateur de date inattendu %d"
#define MSG_BAD_DBF_FILE    "Le fichier DBF %s est alt\xe9r\xe9"
#define MSG_BAD_DBF_REC     "Fichier DBF %s alt\xe9r\xe9 enregistrement %d"
#define MSG_BAD_DBF_TYPE    "Type DBF %c non support\xe9"
#define MSG_BAD_DEF_ARG     "Argument invalide pour INDEXDEF (type=%hd, domain=%hd)"
#define MSG_BAD_DEF_READ    "EOF inattendue en lecture diff\xe9r\xe9""e"
#define MSG_BAD_DEF_TYPE    "Type de colonne invalide"
#define MSG_BAD_DIRECTORY   "R\xe9pertoire invalide %s: %s"
#define MSG_BAD_DIST_JN_FIL "Filtre de jointure distincte invalide"
#define MSG_BAD_DIST_JOIN   "Sp\xe9""cification invalide de jointure distincte"
#define MSG_BAD_DOM_COL_DEF "D\xe9""finition de colonnes invalide pour un domaine"
#define MSG_BAD_DOM_VALUE   "La valeur %d n'appartient pas au domaine"
#define MSG_BAD_EDIT_INIT   "Coparm: \xe9""dition %s initialis\xe9""e improprement"
#define MSG_BAD_EVAL_TYPE   "Fonction scalaire de type=%d invalide"
#define MSG_BAD_EXEC_MODE   "Mode d'ex\xe9""cution invalide '%s'"
#define MSG_BAD_EXP_ARGTYPE "Argument de type %d invalide pour une expression"
#define MSG_BAD_EXP_OPER    "Op\xe9rateur=%d invalide pour expression"
#define MSG_BAD_FETCH_RC    "Code retour inattendu de Fetch %d"
#define MSG_BAD_FIELD_FMT   "Format de champ invalide %c pour %s"
#define MSG_BAD_FIELD_RANK  "Rang %d invalide pour la colonne %s"
#define MSG_BAD_FIELD_TYPE  "Mauvais type de champ %s"
#define MSG_BAD_FILE_HANDLE "Handle de fichier invalide: %s"
#define MSG_BAD_FILE_LIST   "La section liste de fichiers est erron\xe9""e"
#define MSG_BAD_FILTER      "Mauvais filtre: Opc=%d B_T=%d %d Type=%d %d"
#define MSG_BAD_FILTER_CONV "Conversion filtre incorrecte, B_T=%d,%d"
#define MSG_BAD_FILTER_LINK "Op\xe9rateur de cha\xeenage ill\xe9gal %d"
#define MSG_BAD_FILTER_OP   "Op\xe9rateur de filtre invalide %d"
#define MSG_BAD_FILTEST_OP  "Op\xe9rateur invalide %d %d pour FilTest"
#define MSG_BAD_FLD_FORMAT  "Format invalide pour le champs %d de %s"
#define MSG_BAD_FLD_LENGTH  "Champs %s trop long (%s --> %d) ligne %d de %s"
#define MSG_BAD_FLOAT_CONV  "Convertion invalide d'un tableau flottant"
#define MSG_BAD_FPARM_NEXT  "Coparm: FPARM avec Next non nul"
#define MSG_BAD_FREQ_SET    "Sp\xe9""cification erronn\xe9""e de Freq pour la colonne %s"
#define MSG_BAD_FUNC_ARG    "Funcarg de type %d non impl\xe9ment\xe9"
#define MSG_BAD_FUNC_ARGTYP "Mauvais type d'argument=%d pour une fonction"
#define MSG_BAD_FUNC_MODE   "%s: mode invalide %d"
#define MSG_BAD_GENRE       "Genre est invalide"
#define MSG_BAD_GETVIEW_RET "GetView: type de retour %d invalide"
#define MSG_BAD_HANDLE_VAL  "Valeur Handle invalide"
#define MSG_BAD_HAV_FILTER  "Filtre Having sur une requ\xeate non group\xe9""e"
#define MSG_BAD_HAV_FILTYPE "Filtre invalide pour clause Having"
#define MSG_BAD_HEADER      "Fichier %s: bloc en-t\xeate alt\xe9r\xe9"
#define MSG_BAD_HEADER_VAL  "Valeur invalide pour Header"
#define MSG_BAD_HEAD_END    "Lecture fin d'en-t\xeate impossible"
#define MSG_BAD_INDEX_COL   "Colonne %s invalide pour index %s"
#define MSG_BAD_INDEX_DEF   "D\xe9""finition invalide pour index %s"
#define MSG_BAD_INDEX_FILE  "Fichier index %s corrompu"
#define MSG_BAD_INDEX_PART  "D\xe9""finition colonne invalide pour index %s"
#define MSG_BAD_INPUT       "Entr\xe9""e incorrecte"
#define MSG_BAD_IN_ARGTYPE  "Argument de type invalide pour l'op\xe9rateur IN"
#define MSG_BAD_IN_ENDING   "Erreur: fin de cha\xeene IN invalide"
#define MSG_BAD_IN_STRING   "La cha\xeene IN commence ou finie par des caract\xe8res invalides %c ... %c"
#define MSG_BAD_JCOL_TYPE   "Erreur logique JCT: disparit\xe9 des types colonnes"
#define MSG_BAD_JOIN_EXP    "Expression invalide pour une jointure"
#define MSG_BAD_JOIN_FILTER "Filtre de jointure invalide"
#define MSG_BAD_JOIN_OP     "Op\xe9rateur de joint invalide %d"
#define MSG_BAD_LANG_SIZE   "Le fichier langage a une mauvaise taille %d"
#define MSG_BAD_LINEFLD_FMT "Format invalide ligne %d champs %d de %s"
#define MSG_BAD_LINE_LEN    "Longueur ligne non \xe9gale \xe0 Lrecl"
#define MSG_BAD_LIST_TYPE   "Type de liste invalide %d"
#define MSG_BAD_LOCALE      "Locale invalide %s"
#define MSG_BAD_LOCDFON_ARG "Mauvais param\xe8tre pour LOCDFON"
#define MSG_BAD_LOCNODE_USE "Usage inattendu de LOCNODE"
#define MSG_BAD_LRECL       "Disparit\xe9 lrecl table/fichier (%d,%hd)"
#define MSG_BAD_MAX_HAVING  "MAXTMP trop petit pour Having"
#define MSG_BAD_MAX_NREC    "MaxRec=%d ne correspond pas \xe0 MaxBlk=%d Nrec=%d"
#define MSG_BAD_MAX_PARAM   "Mauvais param\xe8tres pour sp\xe9""cifier une valeur maximum"
#define MSG_BAD_MAX_SETTING "Mauvaise valeur '%c' pour max"
#define MSG_BAD_MERGE_TYPE  "Le type %d ne pas \xeatre intercall\xe9"
#define MSG_BAD_NODE_TYPE   "Type noeud erron\xe9 pour la table"
#define MSG_BAD_OFFSET_VAL  "Nul offset invalide pour une table CSV"
#define MSG_BAD_OPEN_MODE   "Mode d'ouverture invalide %d"
#define MSG_BAD_OPERATOR    "Op\xe9rateur invalide %s"
#define MSG_BAD_ORDER_MODE  "Mode de tri %c invalide"
#define MSG_BAD_ORDER_TYPE  "Tri sur objet de type=%d invalide"
#define MSG_BAD_OUTER_JOIN  "Jointure externe invalide sur table enfant"
#define MSG_BAD_PAD_ARGTYP  "Argument de type invalide pour Pad ou Justify"
#define MSG_BAD_PARAMETERS  "%.8s: Mauvais param\xe8tres"
#define MSG_BAD_PARAM_TYPE  "%.8s: Param\xe8tre de type=%d invalide"
#define MSG_BAD_PARM_COUNT  "Nombre de param\xe8tres incoh\xe9rent"
#define MSG_BAD_PHASE_NUM   "Num\xe9ro de phrase %d hors limite"
#define MSG_BAD_PHRASE_NB   "num\xe9ro de phrase hors limite %d rc=%d\n"
#define MSG_BAD_POS_CODE    "POS_code invalide %d"
#define MSG_BAD_POS_TYPE    "Type de POS_code invalide %d"
#define MSG_BAD_PROJNUM     "Mauvais projnum %d pour la colonne %s"
#define MSG_BAD_QUERY_OPEN  "Mode invalide %d pour l'ouverture d'une requ\xeate"
#define MSG_BAD_QUERY_TYPE  "Type de requ\xeate %d invalide pour %s"
#define MSG_BAD_QUOTE_FIELD "Quote manquante dans %s champs %d ligne %d"
#define MSG_BAD_READ_NUMBER "Mauvais nombre %d de valeurs lues dans %s"
#define MSG_BAD_RECFM       "Recfm type %d invalide pour DOSCOL"
#define MSG_BAD_RECFM_VAL   "Valeur invalide %d de Recfm"
#define MSG_BAD_RESULT_TYPE "Mauvais type de r\xe9sultat %d pour %s"
#define MSG_BAD_RETURN_TYPE "Type de retour %d incorrect"
#define MSG_BAD_ROW_VALIST  "Liste de valeurs invalide pour ROW"
#define MSG_BAD_ROW_VALNB   "Nombre de valeurs in\xe9gal dans la liste"
#define MSG_BAD_SCF_ARGTYPE "Argument %d de type=%s invalide pour %s"
#define MSG_BAD_SEM_DOMAIN  "Domain .%d invalide"
#define MSG_BAD_SETTINGS    "Certaines sp\xe9""cifications sont incompatibles avec le type de la table"
#define MSG_BAD_SET_CASE    "La casse d'un tableau ne peut pas passer de non respect \xe0 respecter"
#define MSG_BAD_SET_STRING  "SetValue: appel invalide pour STRING"
#define MSG_BAD_SET_TYPE    "Set type %hd invalide"
#define MSG_BAD_SPECIAL_CMD "Commande sp\xe9""ciale invalide"
#define MSG_BAD_SPECIAL_COL "Colonne sp\xe9""ciale invalide %s"
#define MSG_BAD_SPEC_COLUMN "Colonne sp\xe9""ciale invalide pour ce type de table"
#define MSG_BAD_SQL_PARAM   "Param\xe8tre SQL invalide pour FindColblk"
#define MSG_BAD_SUBLST_TYPE "Coparm: type %d de sous-liste invalide"
#define MSG_BAD_SUBSEL_IN_X "Sub-select invalide pour une expression"
#define MSG_BAD_SUBSEL_TYPE "Type %d invalide retourn\xe9 de Sub-Select"
#define MSG_BAD_SUB_RESULT  "R\xe9sultat ind\xe9""fini de fonction Sub-Select"
#define MSG_BAD_SUB_SELECT  "Sub-select invalide comme argument de fonction"
#define MSG_BAD_TABLE_LINE  "Ligne '%s' ill\xe9gale ou tronqu\xe9""e dans la section Tables"
#define MSG_BAD_TABLE_LIST  "Table %s absente de la liste des tables"
#define MSG_BAD_TABLE_TYPE  "Type invalide %s pour la table %s"
#define MSG_BAD_TEST_TYPE   "BlockTest sur tableau: types d\xe9pareill\xe9s %s %s"
#define MSG_BAD_TRIM_ARGTYP "Argument de type invalide pour Trim"
#define MSG_BAD_TYPE_FOR_IN "Types d'argument incompatibles pour la fonction IN"
#define MSG_BAD_TYPE_FOR_S  "Type incorrecte %d pour %s(%d)"
#define MSG_BAD_TYPE_LIKE   "Type(%d)= %d invalide pour LIKE"
#define MSG_BAD_UPD_COR     "Le qualificateur %s de la colonne %s ne se ref\xe8re pas \xe0 la table mise \xe0 jour %s"
#define MSG_BAD_USERBLK_LEN "Mauvaise longueur \xe0 l'\xe9""criture du bloc utilisateur"
#define MSG_BAD_USETEMP     "Usetemp invalide '%s'"
#define MSG_BAD_USETEMP_VAL "Valeur pour Usetemp invalide %d"
#define MSG_BAD_VALBLK_INDX "Valeur hors limites de l'index du bloc de valeurs"
#define MSG_BAD_VALBLK_TYPE "Type=%d invalide pour un bloc de valeurs"
#define MSG_BAD_VALNODE     "Type %d invalide pour le noeud valeur colonne %s"
#define MSG_BAD_VALUE_TYPE  "Type de valeur invalide %d"
#define MSG_BAD_VAL_UPDATE  "Impossible de d\xe9terminer quelle valeur %s doit \xeatre mise \xe0 jour"
#define MSG_BAD_VIEW_OPEN   "Mode invalide %d pour l'ouverture d'une View"
#define MSG_BAD_XMODE_VAL   "Mode d'ex\xe9""cution %d invalide"
#define MSG_BAD_XOBJ_TYPE   "Mauvais type de Xobject %d"
#define MSG_BAS_NS_LIST     "Format invalide de la liste des espace-noms"
#define MSG_BIN_F_TOO_LONG  "Valeur trop longue pour le champ %s (%d --> %d)"
#define MSG_BIN_MODE_FAIL   "Echec mode binaire: %s"
#define MSG_BLKTYPLEN_MISM  "Disparit\xe9 types/longueurs de bloc dans SetValue"
#define MSG_BLK_IS_NULL     "Blk est nul"
#define MSG_BLOCK_NO_MATCH  "Bloc non correspondant"
#define MSG_BREAKPOINT      "Point de contr\xf4le"
#define MSG_BUFF_TOO_SMALL  "GetColData: Buffer trop petit"
#define MSG_BUFSIZE_ERROR   "Erreur en recherchant la taille du buffer"
#define MSG_BUILDING_GROUPS "Formation des groupes"
#define MSG_BUILD_DIST_GRPS "Formation des groupes distinctes"
#define MSG_BUILD_INDEX     "Construction index %s sur %s"
#define MSG_BXP_NULL        "Bxp nul dans PUTFON"
#define MSG_CANNOT_OPEN     "Ouverture impossible de %s"
#define MSG_CD_ONE_STEP     "Count Distinct doit \xeatre ex\xe9""cut\xe9 en une seule \xe9tape"
#define MSG_CD_ORDER_ERROR  "Erreur de tri dans Count Distinct"
#define MSG_CHECKING_ROWS   "Test des lignes \xe0 mettre \xe0 jour"
#define MSG_CHECK_LEVEL     "Niveau de v\xe9rification fix\xe9 \xe0 %u"
#define MSG_CHSIZE_ERROR    "Erreur dans chsize: %s"
#define MSG_CLN_NOT_IN_JOIN "La colonne C%d n'est pas dans le join"
#define MSG_CNTDIS_COL_LOST "Colonne du Count Distinct perdue"
#define MSG_COLIST_BAD_TYPE "Type=%d invalide pour Colist"
#define MSG_COLNAM_TOO_LONG "Nom de colonne trop long"
#define MSG_COLSEC_TOO_BIG  "Section colonne trop grande, table %s (%d)"
#define MSG_COLS_REDUCED    " (r\xe9""duit par Maxcol)"
#define MSG_COLUMN_ERROR    "Erreur de colonne"
#define MSG_COLUMN_MISMATCH "Colonne %s d\xe9pareill\xe9""e"
#define MSG_COLUMN_NOT_KEY  "La colonne jointe R%d.%s n'est pas une cl\xe9"
#define MSG_COL_ALLOC_ERR   "Allocation impossible du noeud colonne"
#define MSG_COL_ALLOC_ERROR "Erreur d'allocation m\xe9moire pour la colonne %d"
#define MSG_COL_HAS_NO_DEF  "La colonne %s n'est pas d\xe9""finie"
#define MSG_COL_INVAL_TABLE "La colonne %s.%s n'existe pas dans la table %s alias %s"
#define MSG_COL_ISNOT_TABLE "La colonne %s n'est pas dans la table %s"
#define MSG_COL_NB_MISM     "Le nombre de colonnes ne correspond pas"
#define MSG_COL_NOTIN_GRPBY "La colonne %s n'est pas dans la liste de Group By"
#define MSG_COL_NOTIN_TABLE "La colonne %s n'est dans aucune table"
#define MSG_COL_NOTIN_UPDT  "%s n'appartient pas \xe0 la table mise \xe0 jour %s"
#define MSG_COL_NOT_CODED   "La colonne %s n'est pas codifi\xe9""e"
#define MSG_COL_NOT_EXIST   "La colonne %s n'existe pas dans %s"
#define MSG_COL_NOT_FOUND   "La colonne %s n'est pas dans la table %s"
#define MSG_COL_NOT_IN_DB   "La colonne %s de la table %s n'est pas dans la base de donn\xe9""es"
#define MSG_COL_NOT_IN_JOIN "La colonne %s n'est pas dans le join"
#define MSG_COL_NOT_SORTED  "La colonne %s de la table %s n'est pas tri\xe9""e"
#define MSG_COL_NUM_MISM    "Disparit\xe9 du nombre de colonnes"
#define MSG_COL_USED_TWICE  "Colonne %s utilis\xe9""e deux fois ???"
#define MSG_COMPUTE_ERROR   "Erreur dans Compute, op=%d"
#define MSG_COMPUTE_NIY     "Compute non impl\xe9ment\xe9 pour TOKEN"
#define MSG_COMPUTING       "Calculs en cours"
#define MSG_COMPUTING_DIST  "Comptage des valeurs distinctes"
#define MSG_COMPUTING_FUNC  "Calcul de(s) fonction(s)"
#define MSG_COM_ERROR       "Erreur Com"
#define MSG_CONCAT_SUBNODE  "Concat\xe9nation de sous-noeuds impossible"
#define MSG_CONNECTED       "Connect\xe9"
#define MSG_CONNECT_CANCEL  "Connection interrompue par l'utilisateur"
#define MSG_CONNECT_ERROR   "Erreur %d se connectant \xe0 %s"
#define MSG_CONN_CLOSED     "%s(%d) ferm\xe9""e"
#define MSG_CONN_CREATED    "Connexion %s cr\xe9""e"
#define MSG_CONN_DROPPED    "Connexion %s supprim\xe9""e"
#define MSG_CONN_OPEN       "%s(%d) ouverte (%s)"
#define MSG_CONN_SUC_OPEN   "%s(%d) ouverte avec succ\xe8s"
#define MSG_CONTROL_C_EXIT  "Exit par Ctrl-C"
#define MSG_COPY_BAD_PHASE  "Copie de liste invalide en phase %d"
#define MSG_COPY_INV_TYPE   "Coparm: type non support\xe9 %d"
#define MSG_CORREL_NO_QRY   "Les sous-requ\xeates corr\xe9l\xe9""es ne peuvent pas \xeatre de type QRY"
#define MSG_CREATED_PLUGDB  " Cr\xe9\xe9 par PlugDB %s "
#define MSG_CURSOR_SET      "Curseur remis \xe0 %d"
#define MSG_DATABASE_ACTIVE "Base de donn\xe9""es %s activ\xe9""e"
#define MSG_DATABASE_LOADED "Base de donn\xe9""es %s charg\xe9""e"
#define MSG_DATA_IS_NULL    "ExecSpecialCmd: data est NULL"
#define MSG_DATA_MISALIGN   "Mauvais alignement pour ce type de donn\xe9""es"
#define MSG_DBASE_FILE      "Fichier dBASE dbf: "
#define MSG_DB_ALREADY_DEF  "Base de donn\xe9""es %s d\xe9j\xe0 d\xe9""finie"
#define MSG_DB_ALTERED      "Base de donn\xe9""es modifi\xe9""e"
#define MSG_DB_CREATED      "Base de donn\xe9""es %s cr\xe9\xe9""e"
#define MSG_DB_NOT_SPEC     "Base de donn\xe9""es non sp\xe9""cifi\xe9""e"
#define MSG_DB_REMOVED      "Base de donn\xe9""es %s retir\xe9""e de la liste"
#define MSG_DB_SORT_ERROR   "Erreur de tri DB"
#define MSG_DB_STOPPED      "Arr\xeat de la base de donn\xe9""es %s"
#define MSG_DEBUG_NOT_ACTIV "Mode Debug inactif"
#define MSG_DEBUG_SET_INV   "Invalide pour Debug: %c"
#define MSG_DEF_ALLOC_ERROR "Erreur d'allocation de la classe DEF %s"
#define MSG_DELETING_ROWS   "Suppression des lignes"
#define MSG_DEL_FILE_ERR    "Erreur \xe0 l'effacement de %s"
#define MSG_DEL_READ_ERROR  "Delete: erreur en lecture req=%d len=%d"
#define MSG_DEL_WRITE_ERROR "Delete: erreur en \xe9""criture: %s"
#define MSG_DEPREC_FLAG     "Option Flag p\xe9rim\xe9""e, utiliser Coltype"
#define MSG_DICTIONARY      "Dictionnaire "
#define MSG_DIRECT_VARTOK   "Acc\xe8s direct aux r\xe8gles du Variable Token non impl\xe9ment\xe9"
#define MSG_DISCONNECTED    "D\xe9""connect\xe9"
#define MSG_DISTINCT_ERROR  "Plus d'un \xe9l\xe9ment fonctionel DISTINCT"
#define MSG_DISTINCT_ROWS   "S\xe9lection des lignes distinctes"
#define MSG_DISTINCT_VALUES "Extraction des valeurs distinctes"
#define MSG_DIS_NOHEAD_JOIN "Jointure distincte sur une table non en t\xeate"
#define MSG_DLL_LOAD_ERROR  "Erreur %d au chargement du module %s"
#define MSG_DOMAIN_EMPTY    "Le domaine %s est vide"
#define MSG_DOMAIN_ERROR    "Colonne %s: disparit\xe9 domaine(%s)/valeur(%s)"
#define MSG_DOMAIN_FULL     "Le domaine %s est plein (max=%d)"
#define MSG_DOM_FILE_ERROR  "Fichier domain %s introuvable"
#define MSG_DOM_NOT_SUPP    "MS-DOM non support\xe9 par cette version"
#define MSG_DOM_OPEN_ERROR  "Erreur d'ouverture du domaine: %s"
#define MSG_DOM_READ_ERROR  "Erreur %d en lecture de domaine: %s"
#define MSG_DOM_READ_ONLY   "La table domaine %s est en lecture seulement"
#define MSG_DOM_WRITE_ERROR "Erreur %d en \xe9""criture de domaine: %s"
#define MSG_DONE            "Effectu\xe9, rc=%d"
#define MSG_DOSALMEM_NOMEM  "Erreur d'allocation, pas assez de m\xe9moire"
#define MSG_DROP_DB_ERR     "Echec du Drop sur le base de donn\xe9""es %s"
#define MSG_DSORT_LOG_ERROR "Kindex: Erreur logique de tri distincte"
#define MSG_DUMMY_NO_COLS   "Les tables DUMMY ne peuvent pas avoir de colonne"
#define MSG_DUPLICAT_COUNT  "Count sur plus d'une colonne"
#define MSG_DUP_COL_NAME    "La colonne %s existe en double"
#define MSG_DUP_PROJNUM     "Non unique projnum %d pour la colonne %s"
#define MSG_DVAL_NOTIN_LIST "Valeur %s non trouv\xe9""e dans la liste des valeurs distinctes de la colonne %s"
#define MSG_EMPTY_DOC       "Document vide"
#define MSG_EMPTY_FILE      "%s du fichier vide %s: "
#define MSG_ENDSTR_MISMATCH "Fins de cha\xeene et de noeud ne correspondent pas"
#define MSG_END_OF_DELETE   "%d ligne(s) enlev\xe9""e(s) en %.2lf sec"
#define MSG_END_OF_INSERT   "%d ligne(s) ins\xe9r\xe9""e(s) en %.2lf sec"
#define MSG_END_OF_QUERY    "%d ligne(s) extraite(s) en %.2lf sec"
#define MSG_END_OF_UPDATE   "%d ligne(s) modifi\xe9""e(s) en %.2lf sec"
#define MSG_EOF_AFTER_LINE  "Fin de fichier apr\xe8s la ligne %d"
#define MSG_EOF_INDEX_FILE  "EOF lisant le fichier index"
#define MSG_ERASED          " et effac\xe9""e"
#define MSG_ERASE_FAILED    " (\xe9""chec de l'effacement)"
#define MSG_ERROR           "Erreur"
#define MSG_ERROR_IN_LSK    "Erreur %d dans lseek64"
#define MSG_ERROR_IN_SFP    "Erreur %d dans SetFilePointer"
#define MSG_ERROR_NO_PARM   "Param\xe8tre absent (valide seulement pour %.8s.1 et %.8s.5)"
#define MSG_ERROR_OPENING   "Erreur \xe0 l'ouverture de : "
#define MSG_ERR_NUM_GT_MAX  "Erreur: Numval (%d) plus grand que Maxnum (%d)"
#define MSG_ERR_READING_REC "Erreur lisant l'enregistrement %d de %s"
#define MSG_ERR_RET_RULE    "Retour erreur, r\xe8gle=%u"
#define MSG_ERR_RET_TYPE    "Retour erreur, type=%d"
#define MSG_EVAL_EXPIRED    "Cette version d'\xe9valuation est expir\xe9""e"
#define MSG_EVAL_ONLY       "L'utilisation de cette Dll est pour \xe9valuation seulement"
#define MSG_EXECUTING       "Ex\xe9""cution"
#define MSG_EXECUTION_ERROR "Erreur d'ex\xe9""cution"
#define MSG_EXEC_MODE_IS    "Le mode d'ex\xe9""cution est %s"
#define MSG_EXEC_MODE_RESET ". Mode remis \xe0 Execute"
#define MSG_EXEC_MODE_SET   "Mode d'ex\xe9""cution fix\xe9 \xe0 %s"
#define MSG_EXIT_EVAL_ERR   "Erreur pendant l'\xe9valuation de Exit"
#define MSG_EXIT_FROM_LANG  "Fin du langage %s version %d.%d"
#define MSG_FAIL_ADD_NODE   "L'ajout du noeud %s dans la table a \xe9""chou\xe9"
#define MSG_FETCHING_DATA   "Recherche des donn\xe9""es"
#define MSG_FETCHING_ROWS   "Recherche des lignes"
#define MSG_FETCH_NO_RES    "Fetch: Pas de R\xe9sultats"
#define MSG_FIELD_TOO_LONG  "Valeur trop longue pour le champs %d ligne %d"
#define MSG_FILELEN_ERROR   "Erreur dans %s pour %s"
#define MSG_FILE_CLOSE_ERR  "Erreur %d \xe0 la fermeture du fichier"
#define MSG_FILE_IS_EMPTY   "Le fichier %s est vide"
#define MSG_FILE_MAP_ERR    "Erreur de File mapping"
#define MSG_FILE_MAP_ERROR  "CreateFileMapping %s erreur rc=%d"
#define MSG_FILE_NOT_FOUND  "Fichier %s introuvable"
#define MSG_FILE_OPEN_YET   "Fichier %s d\xe9j\xe0 ouvert"
#define MSG_FILE_UNFOUND    "Fichier %s non trouv\xe9"
#define MSG_FILGRP_NO_TABLE "Table %d manquante pour groupe filtre"
#define MSG_FILTER_ATTACH   "Filtre pass\xe9 \xe0 Attach"
#define MSG_FILTER_NO_TABLE "Filtre: premi\xe8re table manquante"
#define MSG_FIND_BAD_TYPE   "Recherche dans un tableau: type non conforme %s %s"
#define MSG_FIX_OVFLW_ADD   "D\xe9passement de capacit\xe9 en addition"
#define MSG_FIX_OVFLW_TIMES "D\xe9passement de capacit\xe9 en mutiplication"
#define MSG_FIX_UNFLW_ADD   "Sous d\xe9passement de capacit\xe9 en addition"
#define MSG_FIX_UNFLW_TIMES "Sous d\xe9passement de capacit\xe9 en multiplication"
#define MSG_FLD_TOO_LNG_FOR "Champs %d trop long pour %s ligne %d de %s"
#define MSG_FLTST_NO_CORREL "FilTest ne devrait \xeatre appel\xe9 que pour les sous-requ\xeates corr\xe9l\xe9""es"
#define MSG_FLT_BAD_RESULT  "Virgule flottante: r\xe9sultat inexacte"
#define MSG_FLT_DENORMAL_OP "Op\xe9rande virgule flottante non normalis\xe9"
#define MSG_FLT_INVALID_OP  "Op\xe9ration virgule flottante invalide"
#define MSG_FLT_OVERFLOW    "D\xe9passement de capacit\xe9 virgule flottante"
#define MSG_FLT_STACK_CHECK "Virgule flottante: Erreur de la pile"
#define MSG_FLT_UNDERFLOW   "Sous-d\xe9passement de capacit\xe9 virgule flottante"
#define MSG_FLT_ZERO_DIVIDE "Virgule flottante: division par z\xe9ro"
#define MSG_FMT_WRITE_NIY   "L'\xe9""criture des fichiers %s n'est pas encore impl\xe9ment\xe9""e"
#define MSG_FNC_NOTIN_SLIST "Fonction de tri absente de la liste de s\xe9lection"
#define MSG_FORMAT_ERROR    "Erreur de formattage"
#define MSG_FOXPRO_FILE     "Fichier FoxPro: "
#define MSG_FPUTS_ERROR     "Erreur dans fputs: %s"
#define MSG_FSBPARP_NULL    "PUTFON: fsbparp est nul"
#define MSG_FSEEK_ERROR     "Erreur dans fseek: %s"
#define MSG_FSETPOS_ERROR   "Erreur dans fseek pour i=%d"
#define MSG_FTELL_ERROR     "Erreur dans ftell enregistrement=%d: %s"
#define MSG_FUNCTION_ERROR  "Erreur dans %s: %d"
#define MSG_FUNC_ERRNO      "Erreur %d dans %s"
#define MSG_FUNC_ERROR      "Erreur dans %s"
#define MSG_FUNC_ERR_S      "Erreur dans %s: %s"
#define MSG_FUNC_REF_DEL    "R\xe9""f\xe9rence \xe0 une fonction d\xe9""finie (r\xe8gle %d) qui a \xe9t\xe9 supprim\xe9""e"
#define MSG_FWRITE_ERROR    "Erreur dans fwrite: %s"
#define MSG_GETCWD_ERR_NO   "?getcwd %s errno=%d"
#define MSG_GETFILESIZE_ERR "Erreur %d dans GetFileSize"
#define MSG_GET_DIST_VALS   "R\xe9""cup\xe9ration des valeurs distinctes de "
#define MSG_GET_ERROR       "Erreur dans %s (colonne %d)"
#define MSG_GET_FUNC_ERR    "Erreur en recherche de la fonction %s: %s"
#define MSG_GET_NAME_ERR    "Erreur en retrouvant le nom d'une table SYS"
#define MSG_GLOBAL_ERROR    "Erreur d'allocation de Global (taille=%d)\n"
#define MSG_GRAM_ALLOC_ERR  "Erreur d'allocation dans Grammar Up"
#define MSG_GRAM_MISMATCH   "Avertissement: version de GRAMMAR perim\xe9""e (sauv\xe9 sous GRAMMAR v%u)"
#define MSG_GRAM_SUBSET_ERR "Erreur d'initialisation du dictionnaire de la grammaire"
#define MSG_GRBY_TAB_NOTIMP "Group by avec tables jointes non impl\xe9ment\xe9"
#define MSG_GROUPBY_NOT_ALL "Group By doit inclure toutes les s\xe9lections non-fonctionnelles"
#define MSG_GROUP_ON_FUNC   "Group by invalide sur colonne fonctionnelle"
#define MSG_GRP_COL_MISM    "Disparit\xe9 colonne des groupes"
#define MSG_GRP_LIST_MISMAT "Le groupement ne couvre pas la liste de s\xe9lection"
#define MSG_GUARD_PAGE      "Violation de page de garde"
#define MSG_GZOPEN_ERROR    "gzopen %s: erreur %d sur %s"
#define MSG_GZPUTS_ERROR    "Erreur dans gzputs: %s"
#define MSG_HANDLE_IS_NULL  "%s est NULL: erreur code: %d"
#define MSG_HARRY_COMP_NIY  "Compute non impl\xe9ment\xe9 pour les cha\xeenes cod\xe9""es"
#define MSG_HAVING_FILTER   "Traitement du Filtre Having"
#define MSG_HBUF_TOO_SMALL  "Buffer(%d) trop petit pour ent\xeate(%d)"
#define MSG_HEAD_OPEN_ERROR "Erreur \xe0 l'ouverture du fichier header"
#define MSG_HEAD_READ_ERROR "Erreur en lecture du fichier header %s"
#define MSG_HEAD_WRITE_ERR  "Erreur en \xe9""criture du fichier header"
#define MSG_HI_OFFSET_ERR   "Offset sup\xe9rieur non nul"
#define MSG_HUGE_DEFAULT    "Huge est %d par d\xe9""fault"
#define MSG_HUGE_WARNING_1  "M\xe9moire Huge non compatible 16-bit pour %d\n"
#define MSG_HUGE_WARNING_2  "R\xe9sultats impr\xe9visibles possibles\n"
#define MSG_IDLE            "Au repos"
#define MSG_ILLEGAL_INSTR   "Instruction ill\xe9gale"
#define MSG_ILL_FILTER_CONV "Conversion implicite ill\xe9gale dans un filtre"
#define MSG_INDEX_CREATED   "Index %s cr\xe9\xe9 sur %s"
#define MSG_INDEX_DEF_ERR   "Erreur sauvegardant l'index d\xe9""finition pour %s"
#define MSG_INDEX_DROPPED   "Index %s supprim\xe9 de %s"
#define MSG_INDEX_INIT_ERR  "Echec de l'initialisation de l'index %s"
#define MSG_INDEX_NOT_DEF   "Index %s non d\xe9""fini"
#define MSG_INDEX_NOT_UNIQ  "L'index n'est pas Unique"
#define MSG_INDEX_ONE_SAVE  "Les index sont sauvegard\xe9s dans un fichier unique"
#define MSG_INDEX_SEP_SAVE  "Les index sont sauvegard\xe9s dans des fichiers s\xe9par\xe9s"
#define MSG_INDEX_YET_ON    "L'index %s existe d\xe9j\xe0 sur %s"
#define MSG_INDX_ALL_DROP   "Tous les index de %s supprim\xe9s"
#define MSG_INDX_COL_NOTIN  "La colonne index %s n'existe pas dans la table %s"
#define MSG_INDX_EXIST_YET  "L'entr\xe9""e index existe d\xe9j\xe0"
#define MSG_INIT_ERROR      "Erreur \xe0 l'initialisation de %s"
#define MSG_INIT_FAILED     "L'initialisation de %s a \xe9""chou\xe9"
#define MSG_INPUT           "Entr\xe9""e: "
#define MSG_INPUT_KEYBD_YET "L'entr\xe9""e est d\xe9j\xe0 au clavier"
#define MSG_INSERTING       "Insertion: "
#define MSG_INSERT_ERROR    "Insert erreur: usage multiple du fichier %s"
#define MSG_INSERT_MISMATCH "Les listes colonne et valeur ne correspondent pas"
#define MSG_INTERNAL        "interne"
#define MSG_INT_COL_ERROR   "Erreur interne sur la colonne index %s"
#define MSG_INT_OVERFLOW    "D\xe9passement de capacit\xe9 sur entier"
#define MSG_INT_ZERO_DIVIDE "Division enti\xe8re par z\xe9ro"
#define MSG_INVALID_BIP     "Bip invalide .%d"
#define MSG_INVALID_DISP    "Disposition invalide"
#define MSG_INVALID_FTYPE   "SBV: Ftype %d invalide"
#define MSG_INVALID_HANDLE  "Poign\xe9""e invalide"
#define MSG_INVALID_OPER    "Op\xe9rateur invalide %d pour %s"
#define MSG_INVALID_OPTION  "Option invalide %s"
#define MSG_INV_COLUMN_TYPE "Type %d Invalide pour la colonne %s"
#define MSG_INV_COL_DATATYP "Type de donn\xe9""es %d invalide pour la colonne %d"
#define MSG_INV_COL_NUM     "Colonne invalide %d"
#define MSG_INV_COL_TYPE    "Type de colonne %s invalide"
#define MSG_INV_CONC_BIP    "Bip invalide (seuls valides: %.8s.0  .1 and .5)"
#define MSG_INV_DATA_PATH   "Chemin vers les donn\xe9""es invalide"
#define MSG_INV_DEF_READ    "Lecture diff\xe9r\xe9""e invalide rc=%d"
#define MSG_INV_DIRCOL_OFST "Offset invalide pour une colonne DIR"
#define MSG_INV_DOMAIN_TYPE "Type invalide %d"
#define MSG_INV_FILTER      "Filtre r\xe9siduel dans %s"
#define MSG_INV_FNC_BUFTYPE "FNC: Type %d de l'argument invalide pour %s"
#define MSG_INV_INFO_TYPE   "Type d'info catalog invalide %d"
#define MSG_INV_INIPATH     "Inipath invalide "
#define MSG_INV_MAP_POS     "Position m\xe9moire invalide"
#define MSG_INV_OPERATOR    "op\xe9rateur invalide %d\n"
#define MSG_INV_PARAMETER   "Param\xe8tre invalide %s"
#define MSG_INV_PARM_TYPE   "Type de param\xe8tre invalide"
#define MSG_INV_QUALIFIER   "Qalificateur '%s' invalide"
#define MSG_INV_QUERY_TYPE  "Type de requ\xeate %d invalide"
#define MSG_INV_RAND_ACC    "L'acc\xe8s al\xe9""atoire d'une table non optimis\xe9""e est impossible"
#define MSG_INV_REC_POS     "Position d'enregistrement invalide"
#define MSG_INV_RESULT_TYPE "Type de r\xe9sultat invalide %s"
#define MSG_INV_SET_SUBTYPE "Type de formattage %d invalide"
#define MSG_INV_SPECIAL_CMD "%s: Commande sp\xe9""ciale invalide"
#define MSG_INV_SUBTYPE     "Sous type invalide %s"
#define MSG_INV_TOK_DOMAIN  "Le domaine %s n'existe pas"
#define MSG_INV_TOPSEM_CMD  "Commande TopSem invalide %c"
#define MSG_INV_TRANSF_USE  "Usage invalide en r\xe8gle transformationnelle"
#define MSG_INV_TYPE_SPEC   "Sp\xe9""cification de type invalide (%.8s.%d)"
#define MSG_INV_UPDT_TABLE  "Table %s invalide pour Update"
#define MSG_INV_VALUE_LIST  "Liste de valeurs invalide pour Insert"
#define MSG_INV_WHERE_JOIN  "Clause Where invalide dans une requ\xeate de jointure"
#define MSG_INV_WORK_PATH   "Chemin de travail invalide"
#define MSG_IN_ARGTYPE_MISM "Arguments de types incompatibles pour une expression IN"
#define MSG_IN_USE          " et en activit\xe9"
#define MSG_IN_WITHOUT_SUB  "IN ou EXISTS sans tableau ou subquery"
#define MSG_IS_NOT_CONN     "%s n'est pas une connexion d\xe9""finie"
#define MSG_JCT_MISS_COLS   "Colonnes manquantes pour une table JCT"
#define MSG_JCT_MISS_TABLE  "Table jointe manquante pour JCT"
#define MSG_JCT_NO_FILTER   "Filtrage impossible des tables virtuelles JCT"
#define MSG_JCT_NO_KEY      "Erreur logique JCT: cl\xe9 manquante"
#define MSG_JOIN_KEY_NO_COL "La cl\xe9 de jointure n'est pas une colonne"
#define MSG_KEY_ALLOC_ERR   "Erreur d'allocation d'un bloc offset cl\xe9"
#define MSG_KEY_ALLOC_ERROR "Erreur d'allocation m\xe9moire, Klen=%d n=%d"
#define MSG_LANGUAGE_QUIT   "%s lib\xe9r\xe9"
#define MSG_LANG_ACTIVE     "Langage %s actif"
#define MSG_LANG_ALLOC_FAIL "PlugInitLang: Erreur d'allocation du bloc Lang"
#define MSG_LANG_ALREADY_UP "Langage d\xe9j\xe0 en \xe9""dition"
#define MSG_LANG_BAD_SAVE   "Langage %s peut-\xeatre incorrectement sauvegard\xe9"
#define MSG_LANG_NOT_FREED  "Langage %s non lib\xe9rable (pas dans la cha\xeene principale)"
#define MSG_LANG_SAVED      "Langage %s sauvegard\xe9"
#define MSG_LANG_WR_LEN_ERR "Erreur de longueur \xe0 l'\xe9""criture du bloc Lang"
#define MSG_LDF_ALLOC_ERROR "Erreur d'allocation d'un LdfBlock"
#define MSG_LDF_RN_MISMATCH "LDF: d\xe9""calage des num\xe9ros de r\xe8gle"
#define MSG_LDF_WLEN_ERROR  "Erreur de longueur en \xe9""crivant LdfData"
#define MSG_LDF_W_LEN_ERROR "Erreur de longueur pour LdfData en \xe9""criture"
#define MSG_LIC_NO_MYSQL    "Votre licence actuelle ne permet pas l'utilisation du type MYSQL"
#define MSG_LINEAR_ERROR    "Erreur de lin\xe9""arisation"
#define MSG_LINE_LENGTH     "Largeur d'impression fix\xe9""e \xe0 %d"
#define MSG_LINE_MAXLIN     "Nombre de lignes de travail plafonn\xe9 \xe0 %d"
#define MSG_LINE_MAXRES     "Nombre de lignes de r\xe9sultat plafonn\xe9 \xe0 %d"
#define MSG_LINE_MAXTMP     "Nombre de lignes interm\xe9""diaires plafonn\xe9 \xe0 %d"
#define MSG_LINE_TOO_LONG   "La nouvelle ligne est trop longue"
#define MSG_LINJOINDB_ERROR "Erreur syst\xe8me: appel incorrecte \xe0 LinJoinDB"
#define MSG_LIST            "--Liste--"
#define MSG_LNG_NOT_IN_LIST "Le langage %s n'est pas dans la liste"
#define MSG_LOADING_DB      "Chargement description de la BD"
#define MSG_LOADING_FAILED  "Le chargement de %s a \xe9""chou\xe9"
#define MSG_LOAD_CDLL_ERROR "Erreur au chargement de ConnDll: rc=%d"
#define MSG_LOCSTRG_TOO_BIG "LOCSTRG: n trop grand ? (%d)\n"
#define MSG_LOGICAL_ERROR   "%s: Erreur logique"
#define MSG_LRECL_TOO_SMALL "Lrecl trop petit (longueur en-t\xeate = %d)"
#define MSG_MAC_NO_DELETE   "Pas de suppression de lignes pour les tables MAC"
#define MSG_MAC_NO_INDEX    "Pas d'acc\xe8s direct aux tables MAC"
#define MSG_MAC_READ_ONLY   "Les tables MAC sont en lecture seulement"
#define MSG_MAC_WIN_ONLY    "Les tables MAC sont seulement sous Windows"
#define MSG_MAKE_EMPTY_FILE "G\xe9n\xe9ration du fichier vide %s: %s"
#define MSG_MAKING          "G\xe9n\xe9ration"
#define MSG_MAKING_DISTINCT "Regroupement des valeures distinctes"
#define MSG_MALLOC_ERROR    "Allocation m\xe9moire impossible par %s"
#define MSG_MALLOC_NULL     "malloc retourne Null"
#define MSG_MAP_NO_MORE     "Le type %s n'est plus support\xe9"
#define MSG_MAP_OBJ_ERR     "Erreur %d \xe0 la fermeture du map objet"
#define MSG_MAP_VEC_ONLY    "MAP Insert permis seulement pour les tables VEC Estimate"
#define MSG_MAP_VIEW_ERROR  "MapViewOfFile %s erreur rc=%d"
#define MSG_MAXSIZE_ERROR   "Maxsize incalculable sur table ouverte"
#define MSG_MAXTMP_TRUNCATE "R\xe9sultats interm\xe9""diaires tronqu\xe9s par maxtmp=%d"
#define MSG_MAX_BITMAP      "Taille maxi des bitmaps d'optimisation  fix\xe9""e \xe0 %d"
#define MSG_MEMSIZE_TOO_BIG "Erreur: memsize (%d) trop grand pour Length (%d)"
#define MSG_MEM_ALLOC_ERR   "Erreur d'allocation m\xe9moire, taille %s = %d"
#define MSG_MEM_ALLOC_ERROR "Erreur d'allocation m\xe9moire"
#define MSG_MEM_ALLOC_YET   "M\xe9moire d\xe9j\xe0 allou\xe9""e"
#define MSG_METAFILE_NOTFND "Fichier Meta introuvable"
#define MSG_MISPLACED_QUOTE "Appostrophe mal plac\xe9""e ligne %d"
#define MSG_MISSING         "Manquant: Value=%p Argval=%p Builtin=%d"
#define MSG_MISSING_ARG     "Argument manquant pour l'op\xe9rateur %d"
#define MSG_MISSING_COL_DEF "D\xe9""finition des colonnes manquante"
#define MSG_MISSING_CONNECT "Connection #1 manquante"
#define MSG_MISSING_EOL     "Fin de ligne manquante dans %s"
#define MSG_MISSING_FIELD   "Champs %d manquant dans %s ligne %d"
#define MSG_MISSING_FNAME   "Nom du fichier manquant"
#define MSG_MISSING_NODE    "Noeud %s manquant dans %s"
#define MSG_MISSING_POS     "POS code manquant"
#define MSG_MISSING_ROWNODE "Impossible de trouver le noeud de la ligne %d"
#define MSG_MISSING_SERV_DB "Indication serveur et/ou base de donn\xe9""es manquante"
#define MSG_MISS_LEAD_COL   "Colonne majeure %s manquante"
#define MSG_MISS_NAME_LRECL "Nom du fichier et/ou LRECL manquant"
#define MSG_MISS_TABLE_LIST "Liste des tables manquante"
#define MSG_MISS_VCT_ELMT   "Taille de bloc vectoriel manquante (Elements)"
#define MSG_MIS_TAG_LIST    "Liste des balises colonne manquante"
#define MSG_MKEMPTY_NIY     "MakeEmptyFile: pas encore implement\xe9 pour Huge et Unix"
#define MSG_MOVE_INV_TYPE   "MOVPARM: param\xe8tre de type invalide %d"
#define MSG_MULT_DISTINCT   "Distinct utilis\xe9 plus d'une fois"
#define MSG_MULT_KEY_ERROR  "Erreur sur cl\xe9 multiple k=%d n=%d"
#define MSG_MUL_MAKECOL_ERR "Erreur logique dans TABMUL::MakeCol"
#define MSG_MYSQL_CNC_OFF   "La connexion \xe0 MySQL est ferm\xe9""e"
#define MSG_MYSQL_CNC_ON    "La connexion \xe0 MySQL est \xe9tablie"
#define MSG_MYSQL_NOT_SUP   "Pas de support de MySQL dans cette version"
#define MSG_MY_CNC_ALREADY  "La connexion \xe0 MySQL est d\xe9j\xe0 active"
#define MSG_NAME_CONV_ERR   "Erreur de convertion du nom de noeud"
#define MSG_NAME_IS_USED    "Le nom %s est d\xe9j\xe0 utilis\xe9"
#define MSG_NCOL_GT_MAXCOL  "Trop de colonnes (%d > %d max)"
#define MSG_NEW_CHAR_NULL   "new char(%d) retourne Null"
#define MSG_NEW_DOC_FAILED  "Impossible de cr\xe9""er le nouveau document"
#define MSG_NEW_RETURN_NULL "NULL renvoy\xe9 par New dans PlugEvalLike"
#define MSG_NEW_TABLE_ERR   "La nouvelle table %s ne peut pas \xeatre charg\xe9""e"
#define MSG_NEXT_FILE_ERROR "Erreur en recherche du fichier suivant. rc=%s"
#define MSG_NODEF_FROM_VIEW "Pas de d\xe9""finition de table depuis une view"
#define MSG_NODE_FOR_CHAR   "Noeud %s trouv\xe9 au lieu d'un caract\xe8re"
#define MSG_NODE_SUBSET_ERR "Erreur d'initialisation de la zone Noeud %d"
#define MSG_NONCONT_EXCEPT  "Exception non-continuable"
#define MSG_NON_DUP_HAVING  "Clause Having dans une requ\xeate non fonctionelle"
#define MSG_NON_EVAL_SEM    "Sem non \xe9valu\xe9""e: p_no=%d"
#define MSG_NOP_ZLIB_INDEX  "L'indexage d'une table zlib non optimis\xe9""e est impossible"
#define MSG_NOT_A_DBF_FILE  "Le fichier n'a pas le format dBASE dbf "
#define MSG_NOT_ENOUGH_COLS "Pas assez de colonnes dans %s"
#define MSG_NOT_ENOUGH_MEM  "M\xe9moire insuffisante pour cette op\xe9ration"
#define MSG_NOT_FIXED_LEN   "Fichier %s non fixe, len=%d lrecl=%d"
#define MSG_NOT_IMPLEMENTED "Non implement\xe9: %.8s"
#define MSG_NOT_IMPL_JOIN   "Pas impl\xe9ment\xe9 pour les jointures"
#define MSG_NOT_IMPL_SET    "Pas impl\xe9ment\xe9 pour les op\xe9rateurs d'ensembles"
#define MSG_NOT_IMPL_YET    "Pas encore implement\xe9"
#define MSG_NOT_LINEARIZED  "Arborescence des tables non lin\xe9""aris\xe9""e"
#define MSG_NOT_MODIFIABLE  " (non modifiable)"
#define MSG_NO_0DH_HEAD     "0DH manquant en fin d'en-t\xeate (dbc=%d)"
#define MSG_NO_ACTIVE_APPL  "Pas d'application active"
#define MSG_NO_ACTIVE_DB    "Pas de base de donn\xe9""es active"
#define MSG_NO_ACTIVE_UDIC  "Pas de dictionaire utilisateur actif"
#define MSG_NO_AGGR_FUNC    "Fonction aggr\xe9g\xe9""e %d ill\xe9gale \xe0 cet endroit"
#define MSG_NO_AREA_FILE    "Fichier Area introuvable"
#define MSG_NO_AVAIL_RESULT "Pas de r\xe9sultat disponible"
#define MSG_NO_BIG_DELETE   "D\xe9l\xe9tion Partielle non impl\xe9ment\xe9""e pour les fichiers HUGE"
#define MSG_NO_CHAR_FROM    "Conversion de type %d en caract\xe8res impossible"
#define MSG_NO_CLUSTER_COL  "Pas de colonne optimisable"
#define MSG_NO_COL_ADDING   "Ajouter des colonnes dans une d\xe9""finition existante est impossible"
#define MSG_NO_COL_DEF_AS   "La d\xe9""finitions des colonnes est incompatible avec AS Select"
#define MSG_NO_COL_FOUND    "La section colonne %s est vide"
#define MSG_NO_COL_IN_TABLE "La colonne %d n'est pas dans la table %s"
#define MSG_NO_COL_SECTION  "Section colonne manquante pour la table %s"
#define MSG_NO_CONNECT_ADDR "Adresse de connection non sp\xe9""cifi\xe9""e"
#define MSG_NO_CONST_FILTER "Filtres constants non implement\xe9s"
#define MSG_NO_CURLY_BRKT   "Pas d'accolade de fermeture"
#define MSG_NO_DATABASE     "Base de donn\xe9""es %s introuvable"
#define MSG_NO_DATE_FMT     "Pas de format date pour le valblock de type %d"
#define MSG_NO_DBF_INSERT   "Insert pas encore impl\xe9ment\xe9 pour les fichier DBF"
#define MSG_NO_DEF_FNCCOL   "Colonne fonction par d\xe9""faut introuvable"
#define MSG_NO_DEF_PIVOTCOL "Colonne pivot par d\xe9""faut introuvable"
#define MSG_NO_DIR_INDX_RD  "Pas d'acc\xe8s directe des tables %s"
#define MSG_NO_DMY_DIR_ACC  "Pas d'acc\xe8s direct aux tables virtuelles DUMMY"
#define MSG_NO_DOM_DELETE   "D\xe9l\xe9tion Partielle non impl\xe9ment\xe9""e pour les domaines"
#define MSG_NO_DOM_MATCH    "Cha\xeene %.8s... non touv\xe9""e dans le domaine %s"
#define MSG_NO_EDITED_LANG  "Coparm: Pas de langage en \xe9""dition"
#define MSG_NO_EXP_LINK     "Liaison par expression invalide pour une table JCT"
#define MSG_NO_EXT_FILTER   "Le filtrage ne peut se r\xe9""f\xe9rer \xe0 une autre table"
#define MSG_NO_EXT_UPDATE   "Pas de mise \xe0 jour en r\xe9""f\xe9rence \xe0 une autre table"
#define MSG_NO_FEAT_SUPPORT "%s non support\xe9 dans cette version"
#define MSG_NO_FILE_LIST    "La table %s n'a pas de liste de fichiers"
#define MSG_NO_FLD_FORMAT   "Format absent pour le champs %d de %s"
#define MSG_NO_FORMAT_COL   "Type COLUMN informattable"
#define MSG_NO_FORMAT_TYPE  "Le format ne peut pas \xeatre d\xe9""fini \xe0 partir du type %d"
#define MSG_NO_FULL_JOIN    "Jointures autoris\xe9""es seulement \xe0 \xe9galit\xe9 sur cl\xe9(s)"
#define MSG_NO_FUL_OUT_JOIN "Jointures externes compl\xe8tes non support\xe9""es"
#define MSG_NO_FUNC_ORDER   "Tri non support\xe9 sur \xe9l\xe9ment fonctionnel"
#define MSG_NO_HEAD_JOIN    "Jointure sur une table non en t\xeate"
#define MSG_NO_HQL_CONV     "Conversion en HQL non disponible"
#define MSG_NO_INDEX        "La table %s n'a pas d'index"
#define MSG_NO_INDEX_GBX    "Pas ou mauvais index pour SQLGBX"
#define MSG_NO_INDEX_IN     "Pas d'index dans %s"
#define MSG_NO_INDEX_READ   "Pas d'acc\xe8s directe des tables multiples"
#define MSG_NO_INIT_LANG    "Pas de langage initial"
#define MSG_NO_JOIN_TO_EXP  "Jointure vers une expression impossible"
#define MSG_NO_JOIN_UPDEL   "Pas de jointure avec Update/Delete"
#define MSG_NO_KEY_COL      "Pas de colonne cl\xe9 trouv\xe9""e"
#define MSG_NO_KEY_UPDATE   "Le nom des cl\xe9s ne peut pas \xeatre modifi\xe9"
#define MSG_NO_LANGUAGE     "Pas de langage op\xe9rationnel\n"
#define MSG_NO_LANG_TO_QUIT "Pas de langage \xe0 quitter"
#define MSG_NO_LISTVAL_HERE "LSTBLK: Liste de valeurs utilis\xe9""e hors contexte"
#define MSG_NO_MAP_INSERT   "MAP incompatible avec Insert"
#define MSG_NO_MATCHING_COL "Pas de colonne correspondant \xe0 %s dans %s"
#define MSG_NO_MATCH_COL    "Colonne correspondante introuvable"
#define MSG_NO_MEMORY       "M\xe9moire pleine"
#define MSG_NO_MEM_CORR_SUB "Subquery corr\xe9l\xe9""e en m\xe9moire non encore impl\xe9ment\xe9""e"
#define MSG_NO_MODE_PADDED  "Mode non support\xe9 pour les fichiers 'padded'"
#define MSG_NO_MORE_COL     "La colonne %s n'est plus dans la table pivot"
#define MSG_NO_MORE_LANG    "Plus de langage, exit de %s\n"
#define MSG_NO_MORE_VAR     "Les fichiers VAR ne sont plus support\xe9s"
#define MSG_NO_MULCOL_JOIN  "Jointure vers un index multi-colonne pas encore possible"
#define MSG_NO_MULT_HAVING  "Clauses Having multiples non impl\xe9ment\xe9""es"
#define MSG_NO_MUL_DIR_ACC  "Acc\xe8s direct des tables multiples pas encore impl\xe9ment\xe9"
#define MSG_NO_MUL_VCT      "Les tables VCT ne peuvent pas \xeatre multiples"
#define MSG_NO_MYSQL_CONN   "Aucune connexion MySQL ouverte"
#define MSG_NO_MYSQL_DELETE "Pas de Delete pour les tables MySQL"
#define MSG_NO_NBCOL        "Pas de NBcol"
#define MSG_NO_NBLIN        "Pas de NBlin, MaxSize ou Continued"
#define MSG_NO_NBLIN_CONT   "Fetch: Pas de NBlin ou Continued"
#define MSG_NO_NULL_CONST   "Les constantes <null> ne sont pas prises en charge"
#define MSG_NO_ODBC_COL     "Colonnes ODBC automatiques non support\xe9""es par cette version"
#define MSG_NO_ODBC_DELETE  "Delete ne devrait pas \xeatre appel\xe9 pour les tables ODBC"
#define MSG_NO_ODBC_DIRECT  "Acc\xe8s directe des tables ODBC non encore impl\xe9ment\xe9"
#define MSG_NO_ODBC_MUL     "Multiple(2) non support\xe9 pour les tables ODBC"
#define MSG_NO_ODBC_SPECOL  "Pas de colonne sp\xe9""ciale ODBC"
#define MSG_NO_OPT_COLUMN   "Pas optimisable ou pas de colonne optimis\xe9""es"
#define MSG_NO_OP_MODIF     "Les modificateurs ne s'appliquent pas \xe0 %s"
#define MSG_NO_PARAMETER    "Pas de param\xe8tre"
#define MSG_NO_PART_DEL     "Delete partiel des fichier %s impossible"
#define MSG_NO_PART_MAP     "Mapping partiel non impl\xe9ment\xe9 pour cet OS"
#define MSG_NO_PAR_BLK_INS  "Insertion de bloc partiel impossible"
#define MSG_NO_PIV_DIR_ACC  "Pas d'acc\xe8s directe aux tables PIVOT"
#define MSG_NO_POS_ADDED    "Pos_code non ajout\xe9"
#define MSG_NO_PROMPTING    "Relance impossible pour les tables distribu\xe9""es"
#define MSG_NO_QRY_DELETE   "Delete n'est pas utilisable pour les views QRY"
#define MSG_NO_QUERY_ARRAY  "Tableaux avec QUERY non encore impl\xe9ment\xe9s"
#define MSG_NO_RCUR_DSK_YET "Usage recursif de DISK non encore implement\xe9"
#define MSG_NO_READ_32      "Lecture de 32 octets impossible"
#define MSG_NO_RECOV_SPACE  "Espace non recouvrable dans le fichier index"
#define MSG_NO_REF_DELETE   "Pas de suppression en r\xe9""f\xe9rence \xe0 une autre table"
#define MSG_NO_REF_UPDATE   "Pas de mise \xe0 jour en r\xe9""f\xe9rence \xe0 une autre table"
#define MSG_NO_REMOTE_FNC   "Certaines fonctions ne peuvent pas \xeatre ex\xe9""cut\xe9""es \xe0 distance"
#define MSG_NO_ROWID_FOR_AM "Acc\xe8s direct impossible de ROWID pour les tables de type %s"
#define MSG_NO_ROW_NODE     "Le nom du Rownode n'est pas d\xe9""fini"
#define MSG_NO_SECTION_NAME "Nom de section manquant"
#define MSG_NO_SEC_UPDATE   "Les noms de section ne peuvent pas \xeatre modifi\xe9s"
#define MSG_NO_SELECTED_DB  "Aucune base de donn\xe9""es s\xe9lect\xe9""e"
#define MSG_NO_SELF_PIVOT   "Une table ne peut se pivoter elle-m\xeame !"
#define MSG_NO_SERVER_FOUND "Serveur introuvable"
#define MSG_NO_SETPOS_YET   "SetPos pas encore impl\xe9ment\xe9 pour les fichier %s"
#define MSG_NO_SFEXIT_UNIX  "Fonction %s non disponible sur Unix"
#define MSG_NO_SOURCE       " (pas de source)"
#define MSG_NO_SPEC_COL     "Pas de colonne sp\xe9""ciales MYSQL"
#define MSG_NO_SQL_DELETE   "Delete n'est pas utilisable actuellement pour les views SQL"
#define MSG_NO_SUB_VAL      "Pas de sous-value d'un tableau de type %d"
#define MSG_NO_SUCH_INDEX   "La table %s n'a pas l'index %s"
#define MSG_NO_SUCH_SERVER  "Serveur %s introuvable"
#define MSG_NO_SUCH_TABLE   "Table %s pas dans la base de donn\xe9""es"
#define MSG_NO_TABCOL_DATA  "Pas de donn\xe9""es pour la table %s colonne %s"
#define MSG_NO_TABLE_COL    "Aucune colonne trouv\xe9""e pour %s"
#define MSG_NO_TABLE_DEL    "Delete non autoris\xe9 pour les tables %s   "
#define MSG_NO_TABLE_DESC   "Pas de bloc descriptif de table"
#define MSG_NO_TABLE_INDEX  "La table %s n'a pas d'index"
#define MSG_NO_TABLE_LIST   "Pas de liste de tables"
#define MSG_NO_TAB_DATA     "Pas de donn\xe9""es pour la table %s"
#define MSG_NO_TERM_IN_TOK  "Les non-terminaux ne sont pas utilisables dans les r\xe8gles de Token"
#define MSG_NO_TOKEN_DB     "DB introuvable pour la colonne TOKEN %s"
#define MSG_NO_UNIX_CATINFO "Pas d'info catalogue sous Unix"
#define MSG_NO_UPDEL_JOIN   "Pas de jointure de tables ODBC pour Update/Delete"
#define MSG_NO_VCT_DELETE   "D\xe9l\xe9tion Partielle non impl\xe9ment\xe9""e pour les fichiers VCT"
#define MSG_NO_VIEW_COLDEF  "Colonne d\xe9""finition impossible pour les views"
#define MSG_NO_VIEW_SORT    "La View fonctionnelle %s ne peut pas \xeatre tri\xe9""e ou jointe"
#define MSG_NO_ZIP_DELETE   "Delete sur fichier Zip non encore implement\xe9"
#define MSG_NO_ZIP_DIR_ACC  "Acc\xe8s directe des tables ZDOS non encore implement\xe9"
#define MSG_NULL_COL_VALUE  "La colonne n'a pas de valeur"
#define MSG_NULL_ENTRY      "InitLang, entr\xe9""e nulle %d %s"
#define MSG_NULL_QUERY      "Requ\xeate vide"
#define MSG_NUMVAL_NOMATCH  "Disparit\xe9 de Numval pour %s"
#define MSG_N_FULL_PARSES   "%d significations"
#define MSG_ODBC_READ_ONLY  "ODBC est actuellement en lecture seulement"
#define MSG_OFFSET_NOT_SUPP "Offset non support\xe9 pour ce type de sous requ\xeate"
#define MSG_ONE_LANG_YET    "Un langage est d\xe9j\xe0 en \xe9""dition"
#define MSG_ONE_PARAM_ONLY  "Un seul param\xe8tre autoris\xe9"
#define MSG_ONLY_LOG10_IMPL "Seul Log10 est implement\xe9"
#define MSG_ON_LANGUAGE     "Langage %.8s version %d niveau %d \xe9""ditable"
#define MSG_OPENING         "Ouverture"
#define MSG_OPENING_QUERY   "Ouverture de la requ\xeate"
#define MSG_OPEN_EMPTY_FILE "Ouverture du fichier vide %s: %s"
#define MSG_OPEN_ERROR      "Erreur d'ouverture %d en mode %d sur %s: "
#define MSG_OPEN_ERROR_IS   "Erreur \xe0 l'ouverture de %s: %s"
#define MSG_OPEN_ERROR_ON   "Erreur d'ouverture sur %s"
#define MSG_OPEN_MODE_ERROR "Erreur d'ouverture(%s) %d sur %s"
#define MSG_OPEN_SORT_ERROR "Erreur logique de tri dans QUERY Open"
#define MSG_OPEN_STRERROR   "Erreur \xe0 l'ouverture: %s"
#define MSG_OPEN_W_ERROR    "Erreur \xe0 l'ouverture de %s en \xe9""criture"
#define MSG_OPTBLK_RD_ERR   "Erreur \xe0 la lecture d'un bloc optimisation: %s"
#define MSG_OPTBLK_WR_ERR   "Erreur \xe0 l'\xe9""criture d'un bloc optimisation: %s"
#define MSG_OPTIMIZING      "Optimisation de "
#define MSG_OPT_BMAP_RD_ERR "Erreur en lecture des bitmaps d'optimisation: %s"
#define MSG_OPT_BMAP_WR_ERR "Erreur en \xe9""criture des bitmaps d'optimisation: %s"
#define MSG_OPT_CANCELLED   "Optimisation interrompue par l'utilisateur"
#define MSG_OPT_DVAL_RD_ERR "Erreur en lecture des valeurs distinctes: %s"
#define MSG_OPT_DVAL_WR_ERR "Erreur en \xe9""criture des valeurs distinctes: %s"
#define MSG_OPT_HEAD_RD_ERR "Erreur en lecture de l'ent\xeate du fichier opt: %s"
#define MSG_OPT_HEAD_WR_ERR "Erreur en \xe9""criture de l'ent\xeate du fichier opt: %s"
#define MSG_OPT_INIT        "Optimisation initialis\xe9""e"
#define MSG_OPT_LOGIC_ERR   "Erreur logique dans SetBitmap, i=%d"
#define MSG_OPT_MAX_RD_ERR  "Erreur en lecture des valeurs maxi: %s"
#define MSG_OPT_MAX_WR_ERR  "Erreur en \xe9""criture des valeurs maxi: %s"
#define MSG_OPT_MIN_RD_ERR  "Erreur en lecture des valeurs mini: %s"
#define MSG_OPT_MIN_WR_ERR  "Erreur en \xe9""criture des valeurs mini: %s"
#define MSG_OPT_NOT_MATCH   "Le fichier opt %s n'est pas \xe0 jour"
#define MSG_OP_RES_TOO_LONG "R\xe9sultat trop long pour l'op\xe9rateur=%d"
#define MSG_ORDER_OUT_RANGE "Tri: Order %d hors limite"
#define MSG_ORDER_TWICE     "Un m\xeame \xe9l\xe9ment est tri\xe9 deux fois"
#define MSG_PAGE_ERROR      "Erreur de pagination"
#define MSG_PARM_CNT_MISS   "Disparit\xe9 du nombre de Param\xe8tres"
#define MSG_PARSE_NULL_SEM  "S\xe9mantique nulle"
#define MSG_PARSING_QUERY   "Analyse de la requ\xeate"
#define MSG_PIX_ERROR       "Pix %s erreur r\xe8gle no=%u\n"
#define MSG_PIX_TEST_ERROR  "R\xe8gle=%u: pix-TEST pas dans le premier noeud\n"
#define MSG_PLG_READ_ONLY   "PLG est actuellement en lecture seulement"
#define MSG_PLM_NULL_SFP    "TABPLM ReadDB: Sfp est NULL"
#define MSG_PLUG_NOT_INIT   "Plug n'est pas initialis\xe9\n"
#define MSG_PLUG_NOT_RUN    "Plug n'est pas en marche"
#define MSG_PNODE_RULE      "(Noeud %d r\xe8gle %d) "
#define MSG_POS_TOO_LONG    "%s trop long (>%d)"
#define MSG_PREC_VBLP_NULL  "ARRAY SetPrecision: Vblp est NULL"
#define MSG_PRIV_INSTR      "Instruction privil\xe9gi\xe9""e"
#define MSG_PROCADD_ERROR   "Erreur %d sur l'adresse de %s"
#define MSG_PROCESS_SUBQRY  "Sub-Query en cours de traitement"
#define MSG_PROC_WOULD_LOOP "Bouclage du traitement (maxres=%d maxlin=%d)"
#define MSG_PROGRESS_INFO   "Informations sur le traitement en cours"
#define MSG_PROMPT_CANCEL   "Relance annul\xe9""e"
#define MSG_PROMPT_NIY      "Prompt non impl\xe9ment\xe9 pour cette configuration"
#define MSG_PTR_NOT_FOUND   "Pointeur introuvable Num=%d ti1=%d"
#define MSG_PXDEF_IS_NULL   "Pxdef est NULL"
#define MSG_QRY_READ_ONLY   "Les views QRY sont en lecture seulement"
#define MSG_QUERY_CANCELLED "Requ\xeate interrompue par l'utilisateur"
#define MSG_QUERY_NOT_EXEC  "Requ\xeate non ex\xe9""cut\xe9""e"
#define MSG_QUERY_SAVED     "Requ\xeate %s sauvegard\xe9""e"
#define MSG_QUOTE_IN_QUOTE  "Appostrophe dans un champ entre appostrophe ligne %d"
#define MSG_RANGE_NIY       "Range pas encore impl\xe9ment\xe9 pour %s"
#define MSG_RANGE_NO_JOIN   "Range non compatible avec les index de jointure"
#define MSG_RC_READING      "rc=%d en lecture de la table %s"
#define MSG_READB_BAD_INIT  "%s ReadDB appel\xe9 avec Init=0"
#define MSG_READCOL_ERROR   "SQLCOL: erreur dans ReadColumn"
#define MSG_READING         "Lecture"
#define MSG_READING_FROM    "Lecture de %s"
#define MSG_READING_RECORD  "Erreur en lecture de l'enregistrement %d de %s"
#define MSG_READY           "Pr\xeat"
#define MSG_READ_ERROR      "Erreur en lecture sur %s: %s"
#define MSG_READ_ERROR_RC   "Erreur en lecture, rc=%d"
#define MSG_READ_MEM_ERROR  "Lecture m\xe9moire %d: taille=%d"
#define MSG_READ_ONLY       "Cette table prot\xe9g\xe9""e en lecture seule ne peut \xeatre modifi\xe9""e"
#define MSG_READ_SEEK_ERROR "Erreur de recherche en lecture: %s"
#define MSG_READ_SEG_ERROR  "Lecture segment %d: taille=%d"
#define MSG_RECEIVED        "Re\xe7u %c\n"
#define MSG_RECORD_ERROR    "Erreur \xe0 la lecture de l'enregistrement %d de %s"
#define MSG_RECORD_NO_SEP   "Enregistrement sans s\xe9parateur"
#define MSG_REC_SKIPPED     " (%d lignes erronn\xe9""es saut\xe9""es par l'option MaxErr)"
#define MSG_REDUCE_INDEX    "R\xe9""duction de l'index"
#define MSG_REGISTER_ERR    "Enregistrement NS impossible, pr\xe9""fix='%s' et href='%s'"
#define MSG_REMOTE_CONN_ERR "La connection \xe9loign\xe9""e a \xe9""chou\xe9"
#define MSG_REMOVE_ERROR    "Erreur en supprimant %s: %s"
#define MSG_REMOVE_NOT_IMPL "Remove non impl\xe9ment\xe9 pour TDB non Table"
#define MSG_RENAME_ERROR    "Erreur renommant %s en %s: %s"
#define MSG_RENUM_RULES     "Renum\xe9rotez les r\xe8gles et r\xe9""entrez ADD (r\xe8gle sauvegard\xe9""e dans la zone tampon)"
#define MSG_REORDER_INDEX   "Reclassement de l'index"
#define MSG_REQU_ARG_NUM    "La fonction %s doit avoir %d arguments"
#define MSG_RESET_TO        "%s remis \xe0 %d"
#define MSG_RES_NOT_UNIQUE  "Le r\xe9sultat n'est pas unique"
#define MSG_RET_FROM_LANG   "Retour au language %s version %d.%d du language %s version %d.%d"
#define MSG_ROWID_NOT_IMPL  "RowNumber non impl\xe9ment\xe9 pour les tables de type %s"
#define MSG_ROWS_SELECTED   "%d lignes s\xe9lectionn\xe9""es en %.2lf sec"
#define MSG_ROWS_TRUNCATED  " (tronqu\xe9 par MAXRES, LIMIT, FREQ ou AreaSize)"
#define MSG_ROW_ARGNB_ERR   "ROW: disparit\xe9 du nombre d'arguments (%d,%d)"
#define MSG_RPC_SERVER_ERR  "Erreur logique dans TABMUL::MakeCol"
#define MSG_RSC_ALLOC_ERROR "Erreur d'allocation m\xe9moire dans Rescol %s"
#define MSG_RULE_ENTERED    "R\xe8gle %d entr\xe9""e"
#define MSG_RULE_SUBSET_ERR "Erreur d'initialisation de la zone R\xe8gles"
#define MSG_SAVING_INDEX    "Sauvegarde du fichier index"
#define MSG_SCAN_NOT_IMP    "Scan non impl\xe9ment\xe9"
#define MSG_SEC_KEY_FIRST   "Les sections et cl\xe9s doivent \xeatre ins\xe9r\xe9""es en premier"
#define MSG_SEC_NAME_FIRST  "Le nom de section doit \xeatre en t\xeate de liste en insertion"
#define MSG_SEC_NOT_FOUND   "Section %s absente de %s"
#define MSG_SEEK_ERROR      "Seek erreur dans CopyHeader"
#define MSG_SEMANTIC_TREE   "Arbre s\xe9mantique"
#define MSG_SEM_BAD_REF     "Sem @%d r\xe9""f\xe9rence un argument de type non 0 ou 1"
#define MSG_SEM_UNKNOWN     "inconnue, rc=%d"
#define MSG_SEP_IN_FIELD    "Le champ %d contient le caract\xe8re s\xe9parateur"
#define MSG_SEQUENCE_ERROR  "HSTMT: Allocation hors s\xe9quence"
#define MSG_SETEOF_ERROR    "Erreur %d dans SetEndOfFile"
#define MSG_SETRECPOS_NIY   "SetRecpos non impl\xe9ment\xe9 pour ce type de table"
#define MSG_SET_LOCALE      "Locale fix\xe9""e \xe0 %s"
#define MSG_SET_NULL_DOM    "Valeur %d donn\xe9""e \xe0 un domaine nul"
#define MSG_SET_OP_NOT_IMPL "Op\xe9rateurs ensemblistes non implement\xe9s"
#define MSG_SET_STR_TRUNC   "SetValue: Cha\xeene de caract\xe8res tronqu\xe9""e"
#define MSG_SEVERAL_TREES   "Jointure non sp\xe9""cifi\xe9""e pour certaines tables"
#define MSG_SFP_ERROR       "Erreur sur SetFilePointer: %s"
#define MSG_SFUNC_NOT_IMPL  "Fonction scalaire %s non impl\xe9ment\xe9""e"
#define MSG_SHARED_LIB_ERR  "Erreur au chargement de la librairie partag\xe9""e %s: %s"
#define MSG_SINGLE_STEP     "Pas \xe0 pas"
#define MSG_SLEEP           "J'ai dormi %d milliseconds"
#define MSG_SMART_SORTING   "R\xe9""cup\xe9ration des lignes tri\xe9""es (passage %d de %d)"
#define MSG_SMART_SORT_ERR  "Erreur logique 1 dans Smart Sort"
#define MSG_SORTING         "Tri en cours"
#define MSG_SORTING_INDEX   "Tri de l'index"
#define MSG_SORTING_VAL     "Tri de %d valeurs"
#define MSG_SORT_JOIN_INDEX "Tri de l'index de jointure"
#define MSG_SPCOL_READONLY  "La colonne sp\xe9""ciale %s est en lecture seulement"
#define MSG_SPEC_CMD_SEP    "Les commandes sp\xe9""ciales doivent \xeatre ex\xe9""cut\xe9""es s\xe9par\xe9ment"
#define MSG_SQL_BAD_TYPE    "RephraseSQL: type %d non support\xe9"
#define MSG_SQL_BLOCK_MISM  "CheckColumn: bloc SQL courant non correspondant"
#define MSG_SQL_CONF_ERROR  "Erreur SQL: SQL_CONFORMANCE"
#define MSG_SQL_READ_ONLY   "Les views SQL sont actuellement en lecture seulement"
#define MSG_SRCH_CLOSE_ERR  "Erreur \xe0 la fermeture de l'Handle de recherche"
#define MSG_SRC_TABLE_UNDEF "La table source n'est pas d\xe9""finie"
#define MSG_STACK_ERROR     "Erreur sur la pile, i=%d\n"
#define MSG_STACK_OVERFLOW  "Parser: D\xe9""bordement de la pile\n"
#define MSG_STRG_NOT_FOUND  "Cha\xeene introuvable"
#define MSG_STRING_INV_LIST "Liste invalide pour SemString"
#define MSG_STRING_TOO_BIG  "Cha\xeene trop grande pour le domaine %s"
#define MSG_SUBALLOC_ERROR  "Pas assez de m\xe9moire en zone %p pour allouer %d (utilis\xe9=%d libre=%d)"
#define MSG_SUBAL_HUGE_ERR  "Pas assez de m\xe9moire en zone huge %p pour allouer %d"
#define MSG_SUBARG_NOSEM    "Argument @ ou sous-phrase de niveau %d pointe sur un noeud sans Sem"
#define MSG_SUBARG_OUTRANGE "Argument @ ou sous-phrase de niveau %d hors limite"
#define MSG_SUBQRY_ONEITEM  "Une Sub-Query ne doit avoir qu'une s\xe9lection"
#define MSG_SUBSET_ERROR    "SubSet erreur dans LoadDB"
#define MSG_SUB_OPEN_YET    "Subquery d\xe9j\xe0 ouverte"
#define MSG_SUB_RES_TOO_LNG "R\xe9sultat trop long pour SUBSTR"
#define MSG_SYNTAX_ERROR    "Erreur de syntaxe"
#define MSG_SYSTEM_ERROR    "Erreur syst\xe8me %d"
#define MSG_S_ACCESS_DENIED "%s: acc\xe8s non autoris\xe9"
#define MSG_S_ERROR         "%s erreur"
#define MSG_S_ERROR_NUM     "%s: erreur=%d"
#define MSG_S_INTRUPT_ERROR "%s: erreur interruption"
#define MSG_S_INVALID_PARM  "%s: param\xe8tre invalide"
#define MSG_S_INV_ADDRESS   "%s: adresse invalide"
#define MSG_S_UNKNOWN_ERROR "%s: erreur de code %u inconnu"
#define MSG_TABDIR_READONLY "Les tables DIR sont en lecture seulement"
#define MSG_TABLE_ALREADY   "La table %s existe d\xe9j\xe0"
#define MSG_TABLE_ALTERED   "Table %s %s alt\xe9r\xe9""e"
#define MSG_TABLE_CREATED   "%s table %s cr\xe9\xe9""e"
#define MSG_TABLE_DROPPED   "Table %s supprim\xe9""e"
#define MSG_TABLE_MULT_JOIN "Utilisation multiple de la table %s pour jointure"
#define MSG_TABLE_NOT_IN_DB "La table %s n'existe pas dans %s"
#define MSG_TABLE_NOT_OPT   "Table non optimisable"
#define MSG_TABLE_NO_INDEX  "La table %s n'est pas indexable"
#define MSG_TABLE_NO_OPT    "La table %s n'existe pas ou de type non optimisable"
#define MSG_TABLE_READ_ONLY "Les tables %s sont en lecture seulement   "
#define MSG_TABMUL_READONLY "Les tables multiples sont en lecture seulement"
#define MSG_TAB_NOT_LOADED  " (certaines tables n'ont put \xeatre charg\xe9""es)"
#define MSG_TAB_NOT_SPEC    "Table non specifi\xe9""e"
#define MSG_TB_VW_NOTIN_DB  "Table ou view %s pas dans la base de donn\xe9""es"
#define MSG_TDB_NXT_NOT_NUL "Tdb.Next non NULL"
#define MSG_TDB_USE_ERROR   "Erreur, Tdbp->Use=%d"
#define MSG_TOO_MANY_COLS   "Trop de colonnes"
#define MSG_TOO_MANY_COLTAB "Trop de colonnes dans %s (%d)"
#define MSG_TOO_MANY_FIELDS "Trop de champs ligne %d de %s"
#define MSG_TOO_MANY_JUMPS  "Trop de niveaux de saut"
#define MSG_TOO_MANY_KEYS   "Trop de cl\xe9s (%d)"
#define MSG_TOO_MANY_POS    "Trop de pos_codes"
#define MSG_TOO_MANY_TABLES "Trop de tables (%d)"
#define MSG_TOPSEM_ERROR    "Erreur inconnue dans TopSem"
#define MSG_TO_BLK_IS_NULL  "To Blk est nul"
#define MSG_TO_FTR_NOT_NULL "Set.To_Ftr n'est pas nul"
#define MSG_TO_PIX_NOT_NULL "Set.To_Pix n'est pas nul"
#define MSG_TO_SEM_NOT_NULL "Set.To_Sem n'est pas nul"
#define MSG_TRUNCATE_ERROR  "Erreur en troncation: %s"
#define MSG_TRUNC_BY_ESTIM  "Tronqu\xe9 par l'option Estimate"
#define MSG_TYPES_ERROR     "Erreur sur Types(%d)"
#define MSG_TYPE_CONV_ERROR "Type non convertible dans une expression"
#define MSG_TYPE_DEF_MISM   "Disparit\xe9 entre type et d\xe9""finition"
#define MSG_TYPE_MISMATCH   "Cl\xe9 et source ne sont pas du m\xeame type"
#define MSG_TYPE_RECFM_MISM "Disparit\xe9 entre Type et Recfm"
#define MSG_TYPE_TO_VERIFY  "Type \xe0 v\xe9rifier: %d"
#define MSG_TYPE_VALUE_ERR  "Colonne %s: disparit\xe9 type(%s)/valeur(%s)"
#define MSG_UNBALANCE_QUOTE "Appostrophe en trop ligne %d"
#define MSG_UNDEFINED_AM    "COLBLK %s: m\xe9thode d'acc\xe8s ind\xe9""finie"
#define MSG_UNDEFINED_PATH  "Chemin d'acc\xe8s ind\xe9""fini pour Plgcnx.ini"
#define MSG_UNDEF_COL_COUNT "Count sur colonne non d\xe9""finie"
#define MSG_UNKNOWN_DOMAIN  "Domaine inconnu %s"
#define MSG_UNKNOWN_ERROR   "Erreur inconnue"
#define MSG_UNKNOWN_EXCPT   "Exception non r\xe9pertori\xe9""e"
#define MSG_UNKNOWN_NAME    "Nom inconnu: %.8s"
#define MSG_UNKNOWN_PATH    "Chemin d'acc\xe8s inconnu pour Plgcnx.ini"
#define MSG_UNKNOWN_POS     "Nom pos_code inconnu: %s"
#define MSG_UNKNOWN_SEM     "Sem %.8s inconnue, rc=%d"
#define MSG_UNKNOWN_SYNONYM "Synonyme inconnu"
#define MSG_UNKNW_QRY_TYPE  "ReadDB: type de requ\xeate inconnu"
#define MSG_UNKN_ERR_CODE   "Erreur de code %d inconnu"
#define MSG_UNLOADABLE      " inchargeable: "
#define MSG_UNLOADABLE_PRM  "%s inchargeable: %s"
#define MSG_UNMATCH_FIL_ARG "Argument de filtre d\xe9pareill\xe9"
#define MSG_UNQ_COL_SEV_TAB "La colonne %s non qualifi\xe9""e est dans plusieurs tables"
#define MSG_UNRESOLVED_ARG  "?Argument manquant: %s non r\xe9solu en %d ligne %d"
#define MSG_UPDATE_ERROR    "Erreur en Update sur %s"
#define MSG_UPDATING_ROWS   "Mise \xe0 jour des lignes"
#define MSG_UPD_ZIP_NOT_IMP "Mise \xe0 jour des tables ZDOS non encore implement\xe9"
#define MSG_UP_LANGUAGE     "Bloc langage %.8s version %d niveau %d charg\xe9"
#define MSG_USED_FREE_MEM   "Sarea: utilis\xe9 %d, libre %d"
#define MSG_USETEMP_IS      "Usetemp est : %s"
#define MSG_USETEMP_RESET   ". Usetemp remis \xe0 Auto"
#define MSG_USETEMP_SET     "Usetemp fix\xe9 \xe0 %s"
#define MSG_USE_NO_MATCH    "Use non correspondant : Use=%d, ti2=%d, ti3=%d"
#define MSG_USING_INDEX     " (Index\xe9 par"
#define MSG_VALIST_MISMATCH "Disparit\xe9 des listes de valeurs"
#define MSG_VALSTR_TOO_LONG "Valeur %s trop longue pour une cha\xeene de longueur %d"
#define MSG_VALTYPE_NOMATCH "Disparit\xe9 types de valeur"
#define MSG_VALUE_ERROR     "Colonne %s: bloc valeur nul"
#define MSG_VALUE_NOT_ALLOC "Valeur non allou\xe9""e pour la colonne R%d %s"
#define MSG_VALUE_TOO_BIG   "Valeur %lld trop grande pour la colonne %s"
#define MSG_VALUE_TOO_LONG  "Valeur %s trop longue pour la colonne %s de longueur %d"
#define MSG_VAL_ALLOC_ERR   "Allocation impossible du noeud valeur"
#define MSG_VAL_TOO_LONG    "Valeur %s trop longue pour le champ %s"
#define MSG_VIEW_ALREADY    "La VIEW %s existe d\xe9j\xe0"
#define MSG_VIEW_CREATED    "%s view %s cr\xe9\xe9""e"
#define MSG_VIEW_DROPPED    "View %s supprim\xe9""e"
#define MSG_VIEW_NOT_IN_DB  "%s n'est pas une View de %s"
#define MSG_VIR_NO_DELETE   "Delete impossible sur les tables %s"
#define MSG_VIR_READ_ONLY   "Les tables virtuelles %s sont en lecture seulement"
#define MSG_VM_LANG         "Langage au format VM, non support\xe9"
#define MSG_VOID_FIRST_ARG  "Le premier argument ne doit pas \xeatre vide"
#define MSG_VOID_IN_STRING  "Erreur: cha\xeene IN vide"
#define MSG_VOID_ORDER_LIST "Liste de tri vide, erreur syst\xe8me ?"
#define MSG_VOID_POS_DICT   "Dictionnaire interne du langage vide"
#define MSG_VOID_QUERY      "Requ\xeate vide %s"
#define MSG_WORK_AREA       "Espace de travail: %s"
#define MSG_WORK_TOO_SMALL  "Zone de travail trop petite, accro\xeetre AreaSize"
#define MSG_WRITE_ERROR     "Erreur \xe0 l'\xe9""criture de %s"
#define MSG_WRITE_SEEK_ERR  "Erreur de recherche en \xe9""criture: %s"
#define MSG_WRITE_STRERROR  "Erreur en \xe9""criture sur %s: %s"
#define MSG_WRITING         "Ecriture"
#define MSG_WRITING_ERROR   "Erreur \xe0 l'\xe9""criture de %s: %s"
#define MSG_WRITING_QUERY   "Erreur \xe0 l'\xe9""criture de la requ\xeate: "
#define MSG_WRONG_ARG_NUM   "La fonction %s ne prend pas %d arguments"
#define MSG_WRONG_COL_NUM   "Num\xe9ro de colonne %d trop grand pour %s"
#define MSG_WRONG_DB_LIST   "Liste des bases de donn\xe9""es incorrecte ou vide"
#define MSG_WRONG_FUNCTION  "Mauvaise fonction %d"
#define MSG_WRONG_OP_PARM   "Mauvais op\xe9rateur ou param\xe8tres pour %s"
#define MSG_WRONG_PARMS     "Mauvais param\xe8tres pour %s"
#define MSG_WRONG_PASSWORD  "Mot de passe ill\xe9gal pour %s"
#define MSG_WRONG_TYPE      "type non support\xe9"
#define MSG_WRONG_USERFILE  "La Userfile a une mauvaise taille %d"
#define MSG_WS_CONV_ERR     "Erreur de convertion de %s en WS"
#define MSG_XCOL_MISMATCH   "La colonne %s ne correspond pas \xe0 l'index"
#define MSG_XDB_DEL_ERROR   "Erreur en supprimant des entr\xe9""es du fichier XDB"
#define MSG_XFILE_READERR   "Erreur %d en lisant le fichier index"
#define MSG_XFILE_TOO_SMALL "Le fichier index est plus petit que la taille de l'index"
#define MSG_XFILE_WRITERR   "Erreur en \xe9""crivant le fichier index: %s"
#define MSG_XMLTAB_INIT_ERR "Erreur d'initialisation de la table XML"
#define MSG_XML_INIT_ERROR  "Erreur d'initialisation du nouveau fichier XML"
#define MSG_XPATH_CNTX_ERR  "Le nouveau contexte XPath ne peut \xeatre cr\xe9\xe9"
#define MSG_XPATH_EVAL_ERR  "Impossible d'\xe9valuer l'emplacement xpath '%s'"
#define MSG_XPATH_NOT_SUPP  "Xpath non support\xe9 colonne %s"
#define MSG_X_ARG_ADDED     "%d arguments ajout\xe9s"
#define MSG_X_ARG_SET       "%d arguments ont \xe9t\xe9 initialis\xe9s"
#define MSG_X_ON_TAB        " %s sur %s("
#define MSG_ZERO_DIVIDE     "Division par z\xe9ro dans une expression"
