/* The non-ASCII literal strings in this file are encoded in the iso-8859-1 / latin-1 character set
 * (https://en.wikipedia.org/wiki/ISO/IEC_8859-1) */
#define MSG_ACCESS_VIOLATN  "Violation acc\xe8s m\xe9moire"
#define MSG_ADD_BAD_TYPE    "Ajout d'une valeur de type %s non conforme dans un tableau %s"
#define MSG_ALLOC_ERROR     "Erreur d'allocation de %s"
#define MSG_ANSWER_TYPE     "R\xe9ponse de type"
#define MSG_API_CONF_ERROR  "Erreur SQL: API_CONFORMANCE"
#define MSG_APPL_NOT_INIT   "Application non initialis\xe9""e"
#define MSG_ARRAY_BNDS_EXCD "Hors limite de tableau"
#define MSG_BAD_ARRAY_OPER  "Les tableaux doivent utiliser l'op\xe9rateur IN"
#define MSG_BAD_ARRAY_TYPE  "Type=%d invalide pour un tableau"
#define MSG_BAD_ARRAY_VAL   "Les tableaux doivent avoir le m\xeame nombre de valeurs"
#define MSG_BAD_BIN_FMT     "Format invalide %c pour la colonne BIN %s"
#define MSG_BAD_BLK_ESTIM   "Nombre de blocs sup\xe9rieur \xe0 l'estimation"
#define MSG_BAD_BLK_SIZE    "Taille du bloc %d non conforme"
#define MSG_BAD_BYTE_NUM    "Le nombre d'octets \xe9""crits est faux"
#define MSG_BAD_BYTE_READ   "Le nombre d'octets lus est faux"
#define MSG_BAD_COL_TYPE    "Type invalide %s pour la colonne %s"
#define MSG_BAD_COL_XPATH   "Xpath invalide colonne %s de la table HTML %s"
#define MSG_BAD_CONST_TYPE  "Type=%d invalide pour une constante"
#define MSG_BAD_CONV_TYPE   "Convertion de type invalide %d"
#define MSG_BAD_DATETIME    "Valeur date/temps invalide"
#define MSG_BAD_DBF_FILE    "Le fichier DBF %s est alt\xe9r\xe9"
#define MSG_BAD_DBF_REC     "Fichier DBF %s alt\xe9r\xe9 enregistrement %d"
#define MSG_BAD_DBF_TYPE    "Type DBF %c non support\xe9 colonne %s"
#define MSG_BAD_DIRECTORY   "R\xe9pertoire invalide %s: %s"
#define MSG_BAD_FIELD_RANK  "Rang %d invalide pour la colonne %s"
#define MSG_BAD_FIELD_TYPE  "Mauvais type de champ %s"
#define MSG_BAD_FILE_HANDLE "Handle de fichier invalide: %s"
#define MSG_BAD_FILTER      "Mauvais filtre: Opc=%d B_T=%d %d Type=%d %d"
#define MSG_BAD_FILTER_CONV "Conversion filtre incorrecte, B_T=%d,%d"
#define MSG_BAD_FILTER_OP   "Op\xe9rateur de filtre invalide %d"
#define MSG_BAD_FLD_FORMAT  "Format invalide pour le champs %d de %s"
#define MSG_BAD_FLD_LENGTH  "Champs %s trop long (%s --> %d) ligne %d de %s"
#define MSG_BAD_FREQ_SET    "Sp\xe9""cification erronn\xe9""e de Freq pour la colonne %s"
#define MSG_BAD_FUNC_MODE   "%s: mode invalide %d"
#define MSG_BAD_HANDLE_VAL  "Valeur Handle invalide"
#define MSG_BAD_HEADER      "Fichier %s: bloc en-t\xeate alt\xe9r\xe9"
#define MSG_BAD_HEAD_END    "Lecture fin d'en-t\xeate impossible"
#define MSG_BAD_INDEX_FILE  "Fichier index %s corrompu"
#define MSG_BAD_LINEFLD_FMT "Format invalide ligne %d champs %d de %s"
#define MSG_BAD_LINE_LEN    "Longueur ligne non \xe9gale \xe0 Lrecl"
#define MSG_BAD_LRECL       "Disparit\xe9 lrecl table/fichier (%d,%hd)"
#define MSG_BAD_NODE_TYPE   "Type noeud erron\xe9 pour la table"
#define MSG_BAD_OFFSET_VAL  "Nul offset invalide pour une table CSV"
#define MSG_BAD_OPEN_MODE   "Mode d'ouverture invalide %d"
#define MSG_BAD_PARAM_TYPE  "%.8s: Param\xe8tre de type=%d invalide"
#define MSG_BAD_PARM_COUNT  "Nombre de param\xe8tres incoh\xe9rent"
#define MSG_BAD_QUOTE_FIELD "Quote manquante dans %s champs %d ligne %d"
#define MSG_BAD_READ_NUMBER "Mauvais nombre %d de valeurs lues dans %s"
#define MSG_BAD_RECFM       "Recfm type %d invalide pour DOSCOL"
#define MSG_BAD_RECFM_VAL   "Valeur invalide %d de Recfm"
#define MSG_BAD_SET_CASE    "La casse d'un tableau ne peut pas passer de non respect \xe0 respecter"
#define MSG_BAD_SET_STRING  "SetValue: appel invalide pour STRING"
#define MSG_BAD_SPECIAL_COL "Colonne sp\xe9""ciale invalide %s"
#define MSG_BAD_SPEC_COLUMN "Colonne sp\xe9""ciale invalide pour ce type de table"
#define MSG_BAD_TABLE_TYPE  "Type invalide %s pour la table %s"
#define MSG_BAD_TYPE_LIKE   "Type(%d)= %d invalide pour LIKE"
#define MSG_BAD_VALBLK_INDX "Valeur hors limites de l'index du bloc de valeurs"
#define MSG_BAD_VALBLK_TYPE "Type=%d invalide pour un bloc de valeurs"
#define MSG_BAD_VALNODE     "Type %d invalide pour le noeud valeur colonne %s"
#define MSG_BAD_VALUE_TYPE  "Type de valeur invalide %d"
#define MSG_BAD_VAL_UPDATE  "Impossible de d\xe9terminer quelle valeur %s doit \xeatre mise \xe0 jour"
#define MSG_BAS_NS_LIST     "Format invalide de la liste des espace-noms"
#define MSG_BIN_F_TOO_LONG  "Valeur trop longue pour le champ %s (%d --> %d)"
#define MSG_BIN_MODE_FAIL   "Echec mode binaire: %s"
#define MSG_BLKTYPLEN_MISM  "Disparit\xe9 types/longueurs de bloc dans SetValue"
#define MSG_BLK_IS_NULL     "Blk est nul"
#define MSG_BREAKPOINT      "Point de contr\xf4le"
#define MSG_BUILD_INDEX     "Construction index %s sur %s"
#define MSG_CANNOT_OPEN     "Ouverture impossible de %s"
#define MSG_CHSIZE_ERROR    "Erreur dans chsize: %s"
#define MSG_COL_ALLOC_ERR   "Allocation impossible du noeud colonne"
#define MSG_COL_ISNOT_TABLE "La colonne %s n'est pas dans la table %s"
#define MSG_COL_NOT_SORTED  "La colonne %s de la table %s n'est pas tri\xe9""e"
#define MSG_COL_NUM_MISM    "Disparit\xe9 du nombre de colonnes"
#define MSG_COM_ERROR       "Erreur Com"
#define MSG_CONCAT_SUBNODE  "Concat\xe9nation de sous-noeuds impossible"
#define MSG_CONNECT_CANCEL  "Connection interrompue par l'utilisateur"
#define MSG_CONTROL_C_EXIT  "Exit par Ctrl-C"
#define MSG_DATABASE_LOADED "Base de donn\xe9""es %s charg\xe9""e"
#define MSG_DATA_MISALIGN   "Mauvais alignement pour ce type de donn\xe9""es"
#define MSG_DBASE_FILE      "Fichier dBASE dbf: "
#define MSG_DEF_ALLOC_ERROR "Erreur d'allocation de la classe DEF %s"
#define MSG_DEL_FILE_ERR    "Erreur \xe0 l'effacement de %s"
#define MSG_DEL_READ_ERROR  "Delete: erreur en lecture req=%d len=%d"
#define MSG_DEL_WRITE_ERROR "Delete: erreur en \xe9""criture: %s"
#define MSG_DEPREC_FLAG     "Option Flag p\xe9rim\xe9""e, utiliser Coltype"
#define MSG_DLL_LOAD_ERROR  "Erreur %d au chargement du module %s"
#define MSG_DOM_NOT_SUPP    "MS-DOM non support\xe9 par cette version"
#define MSG_DVAL_NOTIN_LIST "Valeur %s non trouv\xe9""e dans la liste des valeurs distinctes de la colonne %s"
#define MSG_EMPTY_DOC       "Document vide"
#define MSG_EMPTY_FILE      "%s du fichier vide %s: "
#define MSG_EOF_AFTER_LINE  "Fin de fichier apr\xe8s la ligne %d"
#define MSG_EOF_INDEX_FILE  "EOF lisant le fichier index"
#define MSG_ERROR_IN_LSK    "Erreur %d dans lseek64"
#define MSG_ERROR_IN_SFP    "Erreur %d dans SetFilePointer"
#define MSG_ERR_READING_REC "Erreur lisant l'enregistrement %d de %s"
#define MSG_FAIL_ADD_NODE   "L'ajout du noeud %s dans la table a \xe9""chou\xe9"
#define MSG_FETCH_NO_RES    "Fetch: Pas de R\xe9sultats"
#define MSG_FIELD_TOO_LONG  "Valeur trop longue pour le champs %d ligne %d"
#define MSG_FILELEN_ERROR   "Erreur dans %s pour %s"
#define MSG_FILE_IS_EMPTY   "Le fichier %s est vide"
#define MSG_FILE_MAP_ERR    "Erreur de File mapping"
#define MSG_FILE_MAP_ERROR  "CreateFileMapping %s erreur rc=%d"
#define MSG_FILE_OPEN_YET   "Fichier %s d\xe9j\xe0 ouvert"
#define MSG_FILE_UNFOUND    "Fichier %s non trouv\xe9"
#define MSG_FLD_TOO_LNG_FOR "Champs %d trop long pour %s ligne %d de %s"
#define MSG_FLT_BAD_RESULT  "Virgule flottante: r\xe9sultat inexacte"
#define MSG_FLT_DENORMAL_OP "Op\xe9rande virgule flottante non normalis\xe9"
#define MSG_FLT_INVALID_OP  "Op\xe9ration virgule flottante invalide"
#define MSG_FLT_OVERFLOW    "D\xe9passement de capacit\xe9 virgule flottante"
#define MSG_FLT_STACK_CHECK "Virgule flottante: Erreur de la pile"
#define MSG_FLT_UNDERFLOW   "Sous-d\xe9passement de capacit\xe9 virgule flottante"
#define MSG_FLT_ZERO_DIVIDE "Virgule flottante: division par z\xe9ro"
#define MSG_FMT_WRITE_NIY   "L'\xe9""criture des fichiers %s n'est pas encore impl\xe9ment\xe9""e"
#define MSG_FOXPRO_FILE     "Fichier FoxPro: "
#define MSG_FPUTS_ERROR     "Erreur dans fputs: %s"
#define MSG_FSEEK_ERROR     "Erreur dans fseek: %s"
#define MSG_FSETPOS_ERROR   "Erreur dans fseek pour i=%d"
#define MSG_FTELL_ERROR     "Erreur dans ftell enregistrement=%d: %s"
#define MSG_FUNCTION_ERROR  "Erreur dans %s: %d"
#define MSG_FUNC_ERRNO      "Erreur %d dans %s"
#define MSG_FUNC_ERROR      "Erreur dans %s"
#define MSG_FUNC_ERR_S      "Erreur dans %s: %s"
#define MSG_FWRITE_ERROR    "Erreur dans fwrite: %s"
#define MSG_GET_DIST_VALS   "R\xe9""cup\xe9ration des valeurs distinctes de "
#define MSG_GET_FUNC_ERR    "Erreur en recherche de la fonction %s: %s"
#define MSG_GLOBAL_ERROR    "Erreur d'allocation de Global (taille=%d)\n"
#define MSG_GUARD_PAGE      "Violation de page de garde"
#define MSG_GZOPEN_ERROR    "gzopen %s: erreur %d sur %s"
#define MSG_ILLEGAL_INSTR   "Instruction ill\xe9gale"
#define MSG_ILL_FILTER_CONV "Conversion implicite ill\xe9gale dans un filtre"
#define MSG_INDEX_NOT_UNIQ  "L'index n'est pas Unique"
#define MSG_INDEX_YET_ON    "L'index %s existe d\xe9j\xe0 sur %s"
#define MSG_INDX_COL_NOTIN  "La colonne index %s n'existe pas dans la table %s"
#define MSG_INDX_EXIST_YET  "L'entr\xe9""e index existe d\xe9j\xe0"
#define MSG_INIT_FAILED     "L'initialisation de %s a \xe9""chou\xe9"
#define MSG_INT_COL_ERROR   "Erreur interne sur la colonne index %s"
#define MSG_INT_OVERFLOW    "D\xe9passement de capacit\xe9 sur entier"
#define MSG_INT_ZERO_DIVIDE "Division enti\xe8re par z\xe9ro"
#define MSG_INVALID_DISP    "Disposition invalide"
#define MSG_INVALID_FTYPE   "SBV: Ftype %d invalide"
#define MSG_INVALID_HANDLE  "Poign\xe9""e invalide"
#define MSG_INVALID_OPER    "Op\xe9rateur invalide %d pour %s"
#define MSG_INV_COLUMN_TYPE "Type %d Invalide pour la colonne %s"
#define MSG_INV_COL_TYPE    "Type de colonne %s invalide"
#define MSG_INV_DEF_READ    "Lecture diff\xe9r\xe9""e invalide rc=%d"
#define MSG_INV_DIRCOL_OFST "Offset invalide pour une colonne DIR"
#define MSG_INV_MAP_POS     "Position m\xe9moire invalide"
#define MSG_INV_RAND_ACC    "L'acc\xe8s al\xe9""atoire d'une table non optimis\xe9""e est impossible"
#define MSG_INV_REC_POS     "Position d'enregistrement invalide"
#define MSG_INV_RESULT_TYPE "Type de r\xe9sultat invalide %s"
#define MSG_INV_UPDT_TABLE  "Table %s invalide pour Update"
#define MSG_IN_WITHOUT_SUB  "IN ou EXISTS sans tableau ou subquery"
#define MSG_KEY_ALLOC_ERR   "Erreur d'allocation d'un bloc offset cl\xe9"
#define MSG_KEY_ALLOC_ERROR "Erreur d'allocation m\xe9moire, Klen=%d n=%d"
#define MSG_LINE_TOO_LONG   "La nouvelle ligne est trop longue"
#define MSG_LIST            "--Liste--"
#define MSG_LOADING_FAILED  "Le chargement de %s a \xe9""chou\xe9"
#define MSG_LRECL_TOO_SMALL "Lrecl trop petit (longueur en-t\xeate = %d)"
#define MSG_MAKE_EMPTY_FILE "G\xe9n\xe9ration du fichier vide %s: %s"
#define MSG_MAKING          "G\xe9n\xe9ration"
#define MSG_MALLOC_ERROR    "Allocation m\xe9moire impossible par %s"
#define MSG_MAP_VIEW_ERROR  "MapViewOfFile %s erreur rc=%d"
#define MSG_MAXSIZE_ERROR   "Maxsize incalculable sur table ouverte"
#define MSG_MEM_ALLOC_ERR   "Erreur d'allocation m\xe9moire, taille %s = %d"
#define MSG_MEM_ALLOC_ERROR "Erreur d'allocation m\xe9moire"
#define MSG_MISPLACED_QUOTE "Appostrophe mal plac\xe9""e ligne %d"
#define MSG_MISSING_ARG     "Argument manquant pour l'op\xe9rateur %d"
#define MSG_MISSING_FIELD   "Champs %d manquant dans %s ligne %d"
#define MSG_MISSING_FNAME   "Nom du fichier manquant"
#define MSG_MISSING_NODE    "Noeud %s manquant dans %s"
#define MSG_MISSING_ROWNODE "Impossible de trouver le noeud de la ligne %d"
#define MSG_MIS_TAG_LIST    "Liste des balises colonne manquante"
#define MSG_MUL_MAKECOL_ERR "Erreur logique dans TABMUL::MakeCol"
#define MSG_NAME_CONV_ERR   "Erreur de convertion du nom de noeud"
#define MSG_NEW_DOC_FAILED  "Impossible de cr\xe9""er le nouveau document"
#define MSG_NEW_RETURN_NULL "NULL renvoy\xe9 par New dans PlugEvalLike"
#define MSG_NEXT_FILE_ERROR "Erreur en recherche du fichier suivant. rc=%s"
#define MSG_NONCONT_EXCEPT  "Exception non-continuable"
#define MSG_NOP_ZLIB_INDEX  "L'indexage d'une table zlib non optimis\xe9""e est impossible"
#define MSG_NOT_A_DBF_FILE  "Le fichier n'a pas le format dBASE dbf "
#define MSG_NOT_FIXED_LEN   "Fichier %s non fixe, len=%d lrecl=%d"
#define MSG_NO_0DH_HEAD     "0DH manquant en fin d'en-t\xeate (dbc=%d)"
#define MSG_NO_ACTIVE_DB    "Pas de base de donn\xe9""es active"
#define MSG_NO_CHAR_FROM    "Conversion de type %d en caract\xe8res impossible"
#define MSG_NO_DATE_FMT     "Pas de format date pour le valblock de type %d"
#define MSG_NO_DEF_FNCCOL   "Colonne fonction par d\xe9""faut introuvable"
#define MSG_NO_DEF_PIVOTCOL "Colonne pivot par d\xe9""faut introuvable"
#define MSG_NO_DIR_INDX_RD  "Pas d'acc\xe8s directe des tables %s"
#define MSG_NO_FEAT_SUPPORT "%s non support\xe9 dans cette version"
#define MSG_NO_FLD_FORMAT   "Format absent pour le champs %d de %s"
#define MSG_NO_FORMAT_COL   "Type COLUMN informattable"
#define MSG_NO_FORMAT_TYPE  "Le format ne peut pas \xeatre d\xe9""fini \xe0 partir du type %d"
#define MSG_NO_INDEX_READ   "Pas d'acc\xe8s directe des tables multiples"
#define MSG_NO_KEY_COL      "Pas de colonne cl\xe9 trouv\xe9""e"
#define MSG_NO_KEY_UPDATE   "Le nom des cl\xe9s ne peut pas \xeatre modifi\xe9"
#define MSG_NO_MAP_INSERT   "MAP incompatible avec Insert"
#define MSG_NO_MATCHING_COL "Pas de colonne correspondant \xe0 %s dans %s"
#define MSG_NO_MATCH_COL    "Colonne correspondante introuvable"
#define MSG_NO_MEMORY       "M\xe9moire pleine"
#define MSG_NO_MODE_PADDED  "Mode non support\xe9 pour les fichiers 'padded'"
#define MSG_NO_MUL_VCT      "Les tables VCT ne peuvent pas \xeatre multiples"
#define MSG_NO_ODBC_DELETE  "Delete ne devrait pas \xeatre appel\xe9 pour les tables ODBC"
#define MSG_NO_ODBC_DIRECT  "Acc\xe8s directe des tables ODBC non encore impl\xe9ment\xe9"
#define MSG_NO_ODBC_MUL     "Multiple(2) non support\xe9 pour les tables ODBC"
#define MSG_NO_ODBC_SPECOL  "Pas de colonne sp\xe9""ciale ODBC"
#define MSG_NO_PART_DEL     "Delete partiel des fichier %s impossible"
#define MSG_NO_PART_MAP     "Mapping partiel non impl\xe9ment\xe9 pour cet OS"
#define MSG_NO_PAR_BLK_INS  "Insertion de bloc partiel impossible"
#define MSG_NO_PIV_DIR_ACC  "Pas d'acc\xe8s directe aux tables PIVOT"
#define MSG_NO_READ_32      "Lecture de 32 octets impossible"
#define MSG_NO_RECOV_SPACE  "Espace non recouvrable dans le fichier index"
#define MSG_NO_ROWID_FOR_AM "Acc\xe8s direct impossible de ROWID pour les tables de type %s"
#define MSG_NO_ROW_NODE     "Le nom du Rownode n'est pas d\xe9""fini"
#define MSG_NO_SECTION_NAME "Nom de section manquant"
#define MSG_NO_SEC_UPDATE   "Les noms de section ne peuvent pas \xeatre modifi\xe9s"
#define MSG_NO_SETPOS_YET   "SetPos pas encore impl\xe9ment\xe9 pour les fichier %s"
#define MSG_NO_SPEC_COL     "Pas de colonne sp\xe9""ciales MYSQL"
#define MSG_NO_SUB_VAL      "Pas de sous-value d'un tableau de type %d"
#define MSG_NO_TABCOL_DATA  "Pas de donn\xe9""es pour la table %s colonne %s"
#define MSG_NO_TABLE_DEL    "Delete non autoris\xe9 pour les tables %s   "
#define MSG_NO_TAB_DATA     "Pas de donn\xe9""es pour la table %s"
#define MSG_NO_VCT_DELETE   "D\xe9l\xe9tion Partielle non impl\xe9ment\xe9""e pour les fichiers VCT"
#define MSG_NO_ZIP_DELETE   "Delete sur fichier Zip non encore implement\xe9"
#define MSG_OPENING         "Ouverture"
#define MSG_OPEN_EMPTY_FILE "Ouverture du fichier vide %s: %s"
#define MSG_OPEN_ERROR      "Erreur d'ouverture %d en mode %d sur %s: "
#define MSG_OPEN_ERROR_IS   "Erreur \xe0 l'ouverture de %s: %s"
#define MSG_OPEN_MODE_ERROR "Erreur d'ouverture(%s) %d sur %s"
#define MSG_OPEN_STRERROR   "Erreur \xe0 l'ouverture: %s"
#define MSG_OPTBLK_RD_ERR   "Erreur \xe0 la lecture d'un bloc optimisation: %s"
#define MSG_OPTBLK_WR_ERR   "Erreur \xe0 l'\xe9""criture d'un bloc optimisation: %s"
#define MSG_OPTIMIZING      "Optimisation de "
#define MSG_OPT_BMAP_RD_ERR "Erreur en lecture des bitmaps d'optimisation: %s"
#define MSG_OPT_BMAP_WR_ERR "Erreur en \xe9""criture des bitmaps d'optimisation: %s"
#define MSG_OPT_CANCELLED   "Optimisation interrompue par l'utilisateur"
#define MSG_OPT_DVAL_RD_ERR "Erreur en lecture des valeurs distinctes: %s"
#define MSG_OPT_DVAL_WR_ERR "Erreur en \xe9""criture des valeurs distinctes: %s"
#define MSG_OPT_HEAD_RD_ERR "Erreur en lecture de l'ent\xeate du fichier opt: %s"
#define MSG_OPT_HEAD_WR_ERR "Erreur en \xe9""criture de l'ent\xeate du fichier opt: %s"
#define MSG_OPT_LOGIC_ERR   "Erreur logique dans SetBitmap, i=%d"
#define MSG_OPT_MAX_RD_ERR  "Erreur en lecture des valeurs maxi: %s"
#define MSG_OPT_MAX_WR_ERR  "Erreur en \xe9""criture des valeurs maxi: %s"
#define MSG_OPT_MIN_RD_ERR  "Erreur en lecture des valeurs mini: %s"
#define MSG_OPT_MIN_WR_ERR  "Erreur en \xe9""criture des valeurs mini: %s"
#define MSG_OPT_NOT_MATCH   "Le fichier opt %s n'est pas \xe0 jour"
#define MSG_PAGE_ERROR      "Erreur de pagination"
#define MSG_PARM_CNT_MISS   "Disparit\xe9 du nombre de Param\xe8tres"
#define MSG_PREC_VBLP_NULL  "ARRAY SetPrecision: Vblp est NULL"
#define MSG_PRIV_INSTR      "Instruction privil\xe9gi\xe9""e"
#define MSG_PROCADD_ERROR   "Erreur %d sur l'adresse de %s"
#define MSG_QUERY_CANCELLED "Requ\xeate interrompue par l'utilisateur"
#define MSG_RANGE_NO_JOIN   "Range non compatible avec les index de jointure"
#define MSG_RC_READING      "rc=%d en lecture de la table %s"
#define MSG_READY           "Pr\xeat"
#define MSG_READ_ERROR      "Erreur en lecture sur %s: %s"
#define MSG_READ_ONLY       "Cette table prot\xe9g\xe9""e en lecture seule ne peut \xeatre modifi\xe9""e"
#define MSG_READ_SEEK_ERROR "Erreur de recherche en lecture: %s"
#define MSG_REGISTER_ERR    "Enregistrement NS impossible, pr\xe9""fix='%s' et href='%s'"
#define MSG_REMOVE_ERROR    "Erreur en supprimant %s: %s"
#define MSG_RENAME_ERROR    "Erreur renommant %s en %s: %s"
#define MSG_ROWID_NOT_IMPL  "RowNumber non impl\xe9ment\xe9 pour les tables de type %s"
#define MSG_SEC_KEY_FIRST   "Les sections et cl\xe9s doivent \xeatre ins\xe9r\xe9""es en premier"
#define MSG_SEC_NAME_FIRST  "Le nom de section doit \xeatre en t\xeate de liste en insertion"
#define MSG_SEP_IN_FIELD    "Le champ %d contient le caract\xe8re s\xe9parateur"
#define MSG_SEQUENCE_ERROR  "HSTMT: Allocation hors s\xe9quence"
#define MSG_SETEOF_ERROR    "Erreur %d dans SetEndOfFile"
#define MSG_SETRECPOS_NIY   "SetRecpos non impl\xe9ment\xe9 pour ce type de table"
#define MSG_SET_STR_TRUNC   "SetValue: Cha\xeene de caract\xe8res tronqu\xe9""e"
#define MSG_SFP_ERROR       "Erreur sur SetFilePointer: %s"
#define MSG_SHARED_LIB_ERR  "Erreur au chargement de la librairie partag\xe9""e %s: %s"
#define MSG_SINGLE_STEP     "Pas \xe0 pas"
#define MSG_SORTING_VAL     "Tri de %d valeurs"
#define MSG_SPCOL_READONLY  "La colonne sp\xe9""ciale %s est en lecture seulement"
#define MSG_SQL_CONF_ERROR  "Erreur SQL: SQL_CONFORMANCE"
#define MSG_SRCH_CLOSE_ERR  "Erreur \xe0 la fermeture de l'Handle de recherche"
#define MSG_SRC_TABLE_UNDEF "La table source n'est pas d\xe9""finie"
#define MSG_STACK_OVERFLOW  "D\xe9passement de capacit\xe9 de la pile"
#define MSG_TABDIR_READONLY "Les tables DIR sont en lecture seulement"
#define MSG_TABLE_NOT_OPT   "Table non optimisable"
#define MSG_TABLE_NO_INDEX  "La table %s n'est pas indexable"
#define MSG_TABLE_READ_ONLY "Les tables %s sont en lecture seulement   "
#define MSG_TABMUL_READONLY "Les tables multiples sont en lecture seulement"
#define MSG_TOO_MANY_FIELDS "Trop de champs ligne %d de %s"
#define MSG_TOO_MANY_JUMPS  "Trop de niveaux de saut"
#define MSG_TOO_MANY_KEYS   "Trop de cl\xe9s (%d)"
#define MSG_TO_BLK_IS_NULL  "To Blk est nul"
#define MSG_TRUNCATE_ERROR  "Erreur en troncation: %s"
#define MSG_TRUNC_BY_ESTIM  "Tronqu\xe9 par l'option Estimate"
#define MSG_TYPE_MISMATCH   "Cl\xe9 et source ne sont pas du m\xeame type"
#define MSG_TYPE_VALUE_ERR  "Colonne %s: disparit\xe9 type(%s)/valeur(%s)"
#define MSG_UNBALANCE_QUOTE "Appostrophe en trop ligne %d"
#define MSG_UNDEFINED_AM    "COLBLK %s: m\xe9thode d'acc\xe8s ind\xe9""finie"
#define MSG_UNKNOWN_EXCPT   "Exception non r\xe9pertori\xe9""e"
#define MSG_UNMATCH_FIL_ARG "Argument de filtre d\xe9pareill\xe9"
#define MSG_UPDATE_ERROR    "Erreur en Update sur %s"
#define MSG_UPD_ZIP_NOT_IMP "Mise \xe0 jour des tables ZDOS non encore implement\xe9"
#define MSG_VALSTR_TOO_LONG "Valeur %s trop longue pour une cha\xeene de longueur %d"
#define MSG_VALTYPE_NOMATCH "Disparit\xe9 types de valeur"
#define MSG_VALUE_ERROR     "Colonne %s: bloc valeur nul"
#define MSG_VALUE_TOO_BIG   "Valeur %lld trop grande pour la colonne %s"
#define MSG_VALUE_TOO_LONG  "Valeur %s trop longue pour la colonne %s de longueur %d"
#define MSG_VAL_ALLOC_ERR   "Allocation impossible du noeud valeur"
#define MSG_VIR_NO_DELETE   "Delete impossible sur les tables %s"
#define MSG_VIR_READ_ONLY   "Les tables virtuelles %s sont en lecture seulement"
#define MSG_VOID_FIRST_ARG  "Le premier argument ne doit pas \xeatre vide"
#define MSG_WORK_AREA       "Espace de travail: %s"
#define MSG_WRITE_SEEK_ERR  "Erreur de recherche en \xe9""criture: %s"
#define MSG_WRITE_STRERROR  "Erreur en \xe9""criture sur %s: %s"
#define MSG_WRITING         "Ecriture"
#define MSG_WRITING_ERROR   "Erreur \xe0 l'\xe9""criture de %s: %s"
#define MSG_WS_CONV_ERR     "Erreur de convertion de %s en WS"
#define MSG_XCOL_MISMATCH   "La colonne %s ne correspond pas \xe0 l'index"
#define MSG_XFILE_READERR   "Erreur %d en lisant le fichier index"
#define MSG_XFILE_WRITERR   "Erreur en \xe9""crivant le fichier index: %s"
#define MSG_XMLTAB_INIT_ERR "Erreur d'initialisation de la table XML"
#define MSG_XML_INIT_ERROR  "Erreur d'initialisation du nouveau fichier XML"
#define MSG_XPATH_CNTX_ERR  "Le nouveau contexte XPath ne peut \xeatre cr\xe9\xe9"
#define MSG_XPATH_EVAL_ERR  "Impossible d'\xe9valuer l'emplacement xpath '%s'"
#define MSG_XPATH_NOT_SUPP  "Xpath non support\xe9 colonne %s"
