#! /bin/sh
set -x

if [ ! -x "`which libtoolize`" ]; then
  glibtoolize --force --copy
else
  libtoolize --force --copy
fi
#aclocal-1.9
aclocal
#autoheader2.50
autoheader
#add --include-deps if you want to bootstrap with any other compiler than gcc
#automake --add-missing --copy --include-deps
automake --add-missing --force --copy
#autoconf2.50
autoconf
rm -f config.cache
