rm -rf ${MYSQLTEST_VARDIR}/mysqld.1/datadir_1
rm -rf ${MYSQLTEST_VARDIR}/mysqld.2/datadir_2
rm -rf ${MYSQLTEST_VARDIR}/mysqld.1/innodb_data_1
rm -rf ${MYSQLTEST_VARDIR}/mysqld.2/innodb_data_2
rm -rf ${MYSQLTEST_VARDIR}/mysqld.1/innodb_logs_1
rm -rf ${MYSQLTEST_VARDIR}/mysqld.2/innodb_logs_2
rm -rf ${MYSQLTEST_VARDIR}/mysqld.1/innodb_undo_1
rm -rf ${MYSQLTEST_VARDIR}/mysqld.2/innodb_undo_2
rm -rf ${MYSQLTEST_VARDIR}/mysqld.1/logs_1
rm -rf ${MYSQLTEST_VARDIR}/mysqld.2/logs_2
rm -rf ${MYSQLTEST_VARDIR}/mysqld.1/index_1
rm -rf ${MYSQLTEST_VARDIR}/mysqld.2/index_2
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.1/datadir_1
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.2/datadir_2
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.1/innodb_data_1
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.2/innodb_data_2
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.1/innodb_logs_1
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.2/innodb_logs_2
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.1/innodb_undo_1
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.2/innodb_undo_2
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.1/logs_1
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.2/logs_2
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.1/index_1
mkdir -p ${MYSQLTEST_VARDIR}/mysqld.2/index_2
