version: "{build}"
clone_depth: 10
install:
  - cd ..
  - choco install curl 7zip.commandline
  - curl -O http://mirror.jmu.edu/pub/mariadb/mariadb-10.0.16/source/mariadb-10.0.16.tar.gz
  - 7z x mariadb-10.0.16.tar.gz
  - 7z x mariadb-10.0.16.tar > nul
  - cd mariadb-10.0.16
  - rmdir /S /Q storage\mroonga\
  - move ..\mroonga storage\mroonga
  - git clone --quiet --depth 1 https://github.com/groonga/groonga.git ..\groonga
  - rmdir /S /Q ..\groonga\test\
  - mkdir storage\mroonga\vendor
  - move ..\groonga storage\mroonga\vendor\groonga
  - git clone --quiet --depth 1 https://github.com/groonga/groonga-normalizer-mysql.git storage\mroonga\vendor\groonga\vendor\plugins\groonga-normalizer-mysql
build_script:
  - "echo # > win\\packaging\\CMakeLists.txt"
  - cmake . -G "Visual Studio 12 Win64"
      -DCMAKE_BUILD_TYPE=Debug
      -DWITHOUT_ARCHIVE=ON
      -DWITHOUT_BLACKHOLE=ON
      -DWITHOUT_CASSANDRA=ON
      -DWITHOUT_CONNECT=ON
      -DWITHOUT_CSV=ON
      -DWITHOUT_EXAMPLE=ON
      -DWITHOUT_FEDERATED=ON
      -DWITHOUT_FEDERATEDX=ON
      -DWITHOUT_HEAP=ON
      -DWITHOUT_INNOBASE=ON
      -DWITHOUT_MYISAM=ON
      -DWITHOUT_MYISAMMRG=ON
      -DWITHOUT_OQGRAPH=ON
      -DWITHOUT_PERFSCHEMA=OFF
      -DWITHOUT_SEQUENCE=ON
      -DWITHOUT_SPHINX=ON
      -DWITHOUT_SPIDER=ON
      -DWITHOUT_TEST_SQL_DISCOVERY=ON
      -DWITHOUT_TOKUDB=ON
      -DWITHOUT_XTRADB=ON
      -DWITH_UNIT_TESTS=OFF
  - cmake --build . --config Debug

notifications:
  - provider: Email
    to:
      - groonga-mysql-commit@lists.sourceforge.jp
      - kou@clear-code.com
    on_build_status_changed: true

test: off
