/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_MYSQL_DTRACE_H
#define	_PROBES_MYSQL_DTRACE_H

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED
#include <unistd.h>

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */

#ifdef	__cplusplus
extern "C" {
#endif

#define MYSQL_STABILITY "___dtrace_stability$mysql$v1$5_5_5_5_5_5_5_5_5_5_5_5_5_5_5"

#define MYSQL_TYPEDEFS "___dtrace_typedefs$mysql$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	MYSQL_COMMAND_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$command__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_COMMAND_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$command__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_COMMAND_START(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$command__start$v1$756e7369676e6564206c6f6e67$696e74$63686172202a$63686172202a(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_COMMAND_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$command__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_CONNECTION_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$connection__done$v1$696e74$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_CONNECTION_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$connection__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_CONNECTION_START(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$connection__start$v1$756e7369676e6564206c6f6e67$63686172202a$63686172202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_CONNECTION_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$connection__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_DELETE_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$delete__done$v1$696e74$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_DELETE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$delete__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_DELETE_ROW_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$delete__row__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_DELETE_ROW_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$delete__row__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_DELETE_ROW_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$delete__row__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_DELETE_ROW_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$delete__row__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_DELETE_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$delete__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_DELETE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$delete__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_FILESORT_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$filesort__done$v1$696e74$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_FILESORT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$filesort__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_FILESORT_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$filesort__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_FILESORT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$filesort__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_HANDLER_RDLOCK_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$handler__rdlock__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_HANDLER_RDLOCK_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$handler__rdlock__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_HANDLER_RDLOCK_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$handler__rdlock__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_HANDLER_RDLOCK_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$handler__rdlock__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_HANDLER_UNLOCK_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$handler__unlock__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_HANDLER_UNLOCK_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$handler__unlock__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_HANDLER_UNLOCK_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$handler__unlock__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_HANDLER_UNLOCK_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$handler__unlock__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_HANDLER_WRLOCK_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$handler__wrlock__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_HANDLER_WRLOCK_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$handler__wrlock__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_HANDLER_WRLOCK_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$handler__wrlock__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_HANDLER_WRLOCK_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$handler__wrlock__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_INDEX_READ_ROW_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$index__read__row__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_INDEX_READ_ROW_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$index__read__row__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_INDEX_READ_ROW_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$index__read__row__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_INDEX_READ_ROW_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$index__read__row__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_INSERT_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$insert__done$v1$696e74$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_INSERT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$insert__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_INSERT_ROW_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$insert__row__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_INSERT_ROW_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$insert__row__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_INSERT_ROW_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$insert__row__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_INSERT_ROW_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$insert__row__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_INSERT_SELECT_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$insert__select__done$v1$696e74$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_INSERT_SELECT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$insert__select__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_INSERT_SELECT_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$insert__select__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_INSERT_SELECT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$insert__select__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_INSERT_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$insert__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_INSERT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$insert__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_KEYCACHE_READ_BLOCK(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$keycache__read__block$v1$756e7369676e6564206c6f6e67(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_KEYCACHE_READ_BLOCK_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$keycache__read__block$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_KEYCACHE_READ_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$keycache__read__done$v1$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_KEYCACHE_READ_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$keycache__read__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_KEYCACHE_READ_HIT() \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$keycache__read__hit$v1(); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_KEYCACHE_READ_HIT_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$keycache__read__hit$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_KEYCACHE_READ_MISS() \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$keycache__read__miss$v1(); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_KEYCACHE_READ_MISS_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$keycache__read__miss$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_KEYCACHE_READ_START(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$keycache__read__start$v1$63686172202a$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_KEYCACHE_READ_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$keycache__read__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_KEYCACHE_WRITE_BLOCK(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$keycache__write__block$v1$756e7369676e6564206c6f6e67(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_KEYCACHE_WRITE_BLOCK_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$keycache__write__block$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_KEYCACHE_WRITE_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$keycache__write__done$v1$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_KEYCACHE_WRITE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$keycache__write__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_KEYCACHE_WRITE_START(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$keycache__write__start$v1$63686172202a$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_KEYCACHE_WRITE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$keycache__write__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_MULTI_DELETE_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$multi__delete__done$v1$696e74$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_MULTI_DELETE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$multi__delete__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_MULTI_DELETE_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$multi__delete__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_MULTI_DELETE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$multi__delete__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_MULTI_UPDATE_DONE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$multi__update__done$v1$696e74$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(arg0, arg1, arg2); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_MULTI_UPDATE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$multi__update__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_MULTI_UPDATE_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$multi__update__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_MULTI_UPDATE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$multi__update__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_NET_READ_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$net__read__done$v1$696e74$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_NET_READ_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$net__read__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_NET_READ_START() \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$net__read__start$v1(); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_NET_READ_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$net__read__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_NET_WRITE_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$net__write__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_NET_WRITE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$net__write__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_NET_WRITE_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$net__write__start$v1$756e7369676e6564206c6f6e67(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_NET_WRITE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$net__write__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_QUERY_CACHE_HIT(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$query__cache__hit$v1$63686172202a$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_QUERY_CACHE_HIT_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$query__cache__hit$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_QUERY_CACHE_MISS(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$query__cache__miss$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_QUERY_CACHE_MISS_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$query__cache__miss$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_QUERY_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$query__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_QUERY_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$query__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_QUERY_EXEC_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$query__exec__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_QUERY_EXEC_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$query__exec__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_QUERY_EXEC_START(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$query__exec__start$v1$63686172202a$756e7369676e6564206c6f6e67$63686172202a$63686172202a$63686172202a$696e74(arg0, arg1, arg2, arg3, arg4, arg5); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_QUERY_EXEC_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$query__exec__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_QUERY_PARSE_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$query__parse__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_QUERY_PARSE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$query__parse__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_QUERY_PARSE_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$query__parse__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_QUERY_PARSE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$query__parse__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_QUERY_START(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$query__start$v1$63686172202a$756e7369676e6564206c6f6e67$63686172202a$63686172202a$63686172202a(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_QUERY_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$query__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_READ_ROW_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$read__row__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_READ_ROW_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$read__row__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_READ_ROW_START(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$read__row__start$v1$63686172202a$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_READ_ROW_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$read__row__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_SELECT_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$select__done$v1$696e74$756e7369676e6564206c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_SELECT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$select__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_SELECT_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$select__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_SELECT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$select__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_UPDATE_DONE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$update__done$v1$696e74$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(arg0, arg1, arg2); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_UPDATE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$update__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_UPDATE_ROW_DONE(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$update__row__done$v1$696e74(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_UPDATE_ROW_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$update__row__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_UPDATE_ROW_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$update__row__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_UPDATE_ROW_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$update__row__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MYSQL_UPDATE_START(arg0) \
do { \
	__asm__ volatile(".reference " MYSQL_TYPEDEFS); \
	__dtrace_probe$mysql$update__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MYSQL_STABILITY); \
} while (0)
#define	MYSQL_UPDATE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$mysql$update__start$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$mysql$command__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$command__done$v1(void);
extern void __dtrace_probe$mysql$command__start$v1$756e7369676e6564206c6f6e67$696e74$63686172202a$63686172202a(unsigned long, int, const char *, const char *);
extern int __dtrace_isenabled$mysql$command__start$v1(void);
extern void __dtrace_probe$mysql$connection__done$v1$696e74$756e7369676e6564206c6f6e67(int, unsigned long);
extern int __dtrace_isenabled$mysql$connection__done$v1(void);
extern void __dtrace_probe$mysql$connection__start$v1$756e7369676e6564206c6f6e67$63686172202a$63686172202a(unsigned long, const char *, const char *);
extern int __dtrace_isenabled$mysql$connection__start$v1(void);
extern void __dtrace_probe$mysql$delete__done$v1$696e74$756e7369676e6564206c6f6e67(int, unsigned long);
extern int __dtrace_isenabled$mysql$delete__done$v1(void);
extern void __dtrace_probe$mysql$delete__row__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$delete__row__done$v1(void);
extern void __dtrace_probe$mysql$delete__row__start$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$mysql$delete__row__start$v1(void);
extern void __dtrace_probe$mysql$delete__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$delete__start$v1(void);
extern void __dtrace_probe$mysql$filesort__done$v1$696e74$756e7369676e6564206c6f6e67(int, unsigned long);
extern int __dtrace_isenabled$mysql$filesort__done$v1(void);
extern void __dtrace_probe$mysql$filesort__start$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$mysql$filesort__start$v1(void);
extern void __dtrace_probe$mysql$handler__rdlock__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$handler__rdlock__done$v1(void);
extern void __dtrace_probe$mysql$handler__rdlock__start$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$mysql$handler__rdlock__start$v1(void);
extern void __dtrace_probe$mysql$handler__unlock__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$handler__unlock__done$v1(void);
extern void __dtrace_probe$mysql$handler__unlock__start$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$mysql$handler__unlock__start$v1(void);
extern void __dtrace_probe$mysql$handler__wrlock__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$handler__wrlock__done$v1(void);
extern void __dtrace_probe$mysql$handler__wrlock__start$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$mysql$handler__wrlock__start$v1(void);
extern void __dtrace_probe$mysql$index__read__row__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$index__read__row__done$v1(void);
extern void __dtrace_probe$mysql$index__read__row__start$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$mysql$index__read__row__start$v1(void);
extern void __dtrace_probe$mysql$insert__done$v1$696e74$756e7369676e6564206c6f6e67(int, unsigned long);
extern int __dtrace_isenabled$mysql$insert__done$v1(void);
extern void __dtrace_probe$mysql$insert__row__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$insert__row__done$v1(void);
extern void __dtrace_probe$mysql$insert__row__start$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$mysql$insert__row__start$v1(void);
extern void __dtrace_probe$mysql$insert__select__done$v1$696e74$756e7369676e6564206c6f6e67(int, unsigned long);
extern int __dtrace_isenabled$mysql$insert__select__done$v1(void);
extern void __dtrace_probe$mysql$insert__select__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$insert__select__start$v1(void);
extern void __dtrace_probe$mysql$insert__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$insert__start$v1(void);
extern void __dtrace_probe$mysql$keycache__read__block$v1$756e7369676e6564206c6f6e67(unsigned long);
extern int __dtrace_isenabled$mysql$keycache__read__block$v1(void);
extern void __dtrace_probe$mysql$keycache__read__done$v1$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(unsigned long, unsigned long);
extern int __dtrace_isenabled$mysql$keycache__read__done$v1(void);
extern void __dtrace_probe$mysql$keycache__read__hit$v1(void);
extern int __dtrace_isenabled$mysql$keycache__read__hit$v1(void);
extern void __dtrace_probe$mysql$keycache__read__miss$v1(void);
extern int __dtrace_isenabled$mysql$keycache__read__miss$v1(void);
extern void __dtrace_probe$mysql$keycache__read__start$v1$63686172202a$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(const char *, unsigned long, unsigned long, unsigned long);
extern int __dtrace_isenabled$mysql$keycache__read__start$v1(void);
extern void __dtrace_probe$mysql$keycache__write__block$v1$756e7369676e6564206c6f6e67(unsigned long);
extern int __dtrace_isenabled$mysql$keycache__write__block$v1(void);
extern void __dtrace_probe$mysql$keycache__write__done$v1$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(unsigned long, unsigned long);
extern int __dtrace_isenabled$mysql$keycache__write__done$v1(void);
extern void __dtrace_probe$mysql$keycache__write__start$v1$63686172202a$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(const char *, unsigned long, unsigned long, unsigned long);
extern int __dtrace_isenabled$mysql$keycache__write__start$v1(void);
extern void __dtrace_probe$mysql$multi__delete__done$v1$696e74$756e7369676e6564206c6f6e67(int, unsigned long);
extern int __dtrace_isenabled$mysql$multi__delete__done$v1(void);
extern void __dtrace_probe$mysql$multi__delete__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$multi__delete__start$v1(void);
extern void __dtrace_probe$mysql$multi__update__done$v1$696e74$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(int, unsigned long, unsigned long);
extern int __dtrace_isenabled$mysql$multi__update__done$v1(void);
extern void __dtrace_probe$mysql$multi__update__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$multi__update__start$v1(void);
extern void __dtrace_probe$mysql$net__read__done$v1$696e74$756e7369676e6564206c6f6e67(int, unsigned long);
extern int __dtrace_isenabled$mysql$net__read__done$v1(void);
extern void __dtrace_probe$mysql$net__read__start$v1(void);
extern int __dtrace_isenabled$mysql$net__read__start$v1(void);
extern void __dtrace_probe$mysql$net__write__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$net__write__done$v1(void);
extern void __dtrace_probe$mysql$net__write__start$v1$756e7369676e6564206c6f6e67(unsigned long);
extern int __dtrace_isenabled$mysql$net__write__start$v1(void);
extern void __dtrace_probe$mysql$query__cache__hit$v1$63686172202a$756e7369676e6564206c6f6e67(const char *, unsigned long);
extern int __dtrace_isenabled$mysql$query__cache__hit$v1(void);
extern void __dtrace_probe$mysql$query__cache__miss$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$query__cache__miss$v1(void);
extern void __dtrace_probe$mysql$query__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$query__done$v1(void);
extern void __dtrace_probe$mysql$query__exec__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$query__exec__done$v1(void);
extern void __dtrace_probe$mysql$query__exec__start$v1$63686172202a$756e7369676e6564206c6f6e67$63686172202a$63686172202a$63686172202a$696e74(const char *, unsigned long, const char *, const char *, const char *, int);
extern int __dtrace_isenabled$mysql$query__exec__start$v1(void);
extern void __dtrace_probe$mysql$query__parse__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$query__parse__done$v1(void);
extern void __dtrace_probe$mysql$query__parse__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$query__parse__start$v1(void);
extern void __dtrace_probe$mysql$query__start$v1$63686172202a$756e7369676e6564206c6f6e67$63686172202a$63686172202a$63686172202a(const char *, unsigned long, const char *, const char *, const char *);
extern int __dtrace_isenabled$mysql$query__start$v1(void);
extern void __dtrace_probe$mysql$read__row__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$read__row__done$v1(void);
extern void __dtrace_probe$mysql$read__row__start$v1$63686172202a$63686172202a$696e74(const char *, const char *, int);
extern int __dtrace_isenabled$mysql$read__row__start$v1(void);
extern void __dtrace_probe$mysql$select__done$v1$696e74$756e7369676e6564206c6f6e67(int, unsigned long);
extern int __dtrace_isenabled$mysql$select__done$v1(void);
extern void __dtrace_probe$mysql$select__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$select__start$v1(void);
extern void __dtrace_probe$mysql$update__done$v1$696e74$756e7369676e6564206c6f6e67$756e7369676e6564206c6f6e67(int, unsigned long, unsigned long);
extern int __dtrace_isenabled$mysql$update__done$v1(void);
extern void __dtrace_probe$mysql$update__row__done$v1$696e74(int);
extern int __dtrace_isenabled$mysql$update__row__done$v1(void);
extern void __dtrace_probe$mysql$update__row__start$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$mysql$update__row__start$v1(void);
extern void __dtrace_probe$mysql$update__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mysql$update__start$v1(void);

#else

#define	MYSQL_COMMAND_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_COMMAND_DONE_ENABLED() (0)
#define	MYSQL_COMMAND_START(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	MYSQL_COMMAND_START_ENABLED() (0)
#define	MYSQL_CONNECTION_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_CONNECTION_DONE_ENABLED() (0)
#define	MYSQL_CONNECTION_START(arg0, arg1, arg2) \
do { \
	} while (0)
#define	MYSQL_CONNECTION_START_ENABLED() (0)
#define	MYSQL_DELETE_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_DELETE_DONE_ENABLED() (0)
#define	MYSQL_DELETE_ROW_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_DELETE_ROW_DONE_ENABLED() (0)
#define	MYSQL_DELETE_ROW_START(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_DELETE_ROW_START_ENABLED() (0)
#define	MYSQL_DELETE_START(arg0) \
do { \
	} while (0)
#define	MYSQL_DELETE_START_ENABLED() (0)
#define	MYSQL_FILESORT_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_FILESORT_DONE_ENABLED() (0)
#define	MYSQL_FILESORT_START(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_FILESORT_START_ENABLED() (0)
#define	MYSQL_HANDLER_RDLOCK_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_HANDLER_RDLOCK_DONE_ENABLED() (0)
#define	MYSQL_HANDLER_RDLOCK_START(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_HANDLER_RDLOCK_START_ENABLED() (0)
#define	MYSQL_HANDLER_UNLOCK_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_HANDLER_UNLOCK_DONE_ENABLED() (0)
#define	MYSQL_HANDLER_UNLOCK_START(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_HANDLER_UNLOCK_START_ENABLED() (0)
#define	MYSQL_HANDLER_WRLOCK_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_HANDLER_WRLOCK_DONE_ENABLED() (0)
#define	MYSQL_HANDLER_WRLOCK_START(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_HANDLER_WRLOCK_START_ENABLED() (0)
#define	MYSQL_INDEX_READ_ROW_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_INDEX_READ_ROW_DONE_ENABLED() (0)
#define	MYSQL_INDEX_READ_ROW_START(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_INDEX_READ_ROW_START_ENABLED() (0)
#define	MYSQL_INSERT_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_INSERT_DONE_ENABLED() (0)
#define	MYSQL_INSERT_ROW_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_INSERT_ROW_DONE_ENABLED() (0)
#define	MYSQL_INSERT_ROW_START(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_INSERT_ROW_START_ENABLED() (0)
#define	MYSQL_INSERT_SELECT_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_INSERT_SELECT_DONE_ENABLED() (0)
#define	MYSQL_INSERT_SELECT_START(arg0) \
do { \
	} while (0)
#define	MYSQL_INSERT_SELECT_START_ENABLED() (0)
#define	MYSQL_INSERT_START(arg0) \
do { \
	} while (0)
#define	MYSQL_INSERT_START_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_BLOCK(arg0) \
do { \
	} while (0)
#define	MYSQL_KEYCACHE_READ_BLOCK_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_KEYCACHE_READ_DONE_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_HIT() \
do { \
	} while (0)
#define	MYSQL_KEYCACHE_READ_HIT_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_MISS() \
do { \
	} while (0)
#define	MYSQL_KEYCACHE_READ_MISS_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_START(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	MYSQL_KEYCACHE_READ_START_ENABLED() (0)
#define	MYSQL_KEYCACHE_WRITE_BLOCK(arg0) \
do { \
	} while (0)
#define	MYSQL_KEYCACHE_WRITE_BLOCK_ENABLED() (0)
#define	MYSQL_KEYCACHE_WRITE_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_KEYCACHE_WRITE_DONE_ENABLED() (0)
#define	MYSQL_KEYCACHE_WRITE_START(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	MYSQL_KEYCACHE_WRITE_START_ENABLED() (0)
#define	MYSQL_MULTI_DELETE_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_MULTI_DELETE_DONE_ENABLED() (0)
#define	MYSQL_MULTI_DELETE_START(arg0) \
do { \
	} while (0)
#define	MYSQL_MULTI_DELETE_START_ENABLED() (0)
#define	MYSQL_MULTI_UPDATE_DONE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	MYSQL_MULTI_UPDATE_DONE_ENABLED() (0)
#define	MYSQL_MULTI_UPDATE_START(arg0) \
do { \
	} while (0)
#define	MYSQL_MULTI_UPDATE_START_ENABLED() (0)
#define	MYSQL_NET_READ_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_NET_READ_DONE_ENABLED() (0)
#define	MYSQL_NET_READ_START() \
do { \
	} while (0)
#define	MYSQL_NET_READ_START_ENABLED() (0)
#define	MYSQL_NET_WRITE_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_NET_WRITE_DONE_ENABLED() (0)
#define	MYSQL_NET_WRITE_START(arg0) \
do { \
	} while (0)
#define	MYSQL_NET_WRITE_START_ENABLED() (0)
#define	MYSQL_QUERY_CACHE_HIT(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_QUERY_CACHE_HIT_ENABLED() (0)
#define	MYSQL_QUERY_CACHE_MISS(arg0) \
do { \
	} while (0)
#define	MYSQL_QUERY_CACHE_MISS_ENABLED() (0)
#define	MYSQL_QUERY_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_QUERY_DONE_ENABLED() (0)
#define	MYSQL_QUERY_EXEC_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_QUERY_EXEC_DONE_ENABLED() (0)
#define	MYSQL_QUERY_EXEC_START(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	} while (0)
#define	MYSQL_QUERY_EXEC_START_ENABLED() (0)
#define	MYSQL_QUERY_PARSE_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_QUERY_PARSE_DONE_ENABLED() (0)
#define	MYSQL_QUERY_PARSE_START(arg0) \
do { \
	} while (0)
#define	MYSQL_QUERY_PARSE_START_ENABLED() (0)
#define	MYSQL_QUERY_START(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	MYSQL_QUERY_START_ENABLED() (0)
#define	MYSQL_READ_ROW_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_READ_ROW_DONE_ENABLED() (0)
#define	MYSQL_READ_ROW_START(arg0, arg1, arg2) \
do { \
	} while (0)
#define	MYSQL_READ_ROW_START_ENABLED() (0)
#define	MYSQL_SELECT_DONE(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_SELECT_DONE_ENABLED() (0)
#define	MYSQL_SELECT_START(arg0) \
do { \
	} while (0)
#define	MYSQL_SELECT_START_ENABLED() (0)
#define	MYSQL_UPDATE_DONE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	MYSQL_UPDATE_DONE_ENABLED() (0)
#define	MYSQL_UPDATE_ROW_DONE(arg0) \
do { \
	} while (0)
#define	MYSQL_UPDATE_ROW_DONE_ENABLED() (0)
#define	MYSQL_UPDATE_ROW_START(arg0, arg1) \
do { \
	} while (0)
#define	MYSQL_UPDATE_ROW_START_ENABLED() (0)
#define	MYSQL_UPDATE_START(arg0) \
do { \
	} while (0)
#define	MYSQL_UPDATE_START_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_MYSQL_DTRACE_H */
