# Define our crates within a workspace

[workspace]
resolver = "2"
members = [
    "bindings",
    "mariadb",
    "macros",
    "examples/keymgt-basic",
    "examples/keymgt-debug",
    "examples/encryption",
    "plugins/keymgt-clevis",
    "plugins/encryption-chacha",
    "test-runner",
]
