/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cassandra_constants.h"

namespace org { namespace apache { namespace cassandra {

const cassandraConstants g_cassandra_constants;

cassandraConstants::cassandraConstants() {
  cassandra_const_VERSION = (char *)"19.32.0";
}

}}} // namespace

