IF(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|AARCH64")
    include(CheckCXXSourceCompiles)

    CHECK_C_COMPILER_FLAG(-march=armv8-a+crc+crypto HAVE_ARMV8_CRC_CRYPTO_INTRINSICS)
    IF(HAVE_ARMV8_CRC_CRYPTO_INTRINSICS)
      SET(ARMV8_NEON_COMPILE_FLAGS "${ARMV8_NEON_COMPILE_FLAGS} -march=armv8-a+crc+crypto")
    ENDIF()
ENDIF()
