if(PMEM_LIBRARIES)
  set(PMEM_FOUND TRUE)
  return()
endif()
if(DEFINED PMEM_LIBRARIES)
  set(PMEM_FOUND FALSE)
  return()
endif()

find_path(PMEM_INCLUDE_DIRS NAMES libpmem.h)
find_library(PMEM_LIBRARIES NAMES pmem)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    PMEM DEFAULT_MSG
    PMEM_LIBRARIES PMEM_INCLUDE_DIRS)

mark_as_advanced(PMEM_INCLUDE_DIRS PMEM_LIBRARIES)
