find_path(LIBURING_INCLUDE_DIR NAMES liburing.h)
find_library(LIBURING_LIBRARIES NAMES uring)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    URING DEFAULT_MSG
    LIBURING_LIBRARIES LIBURING_INCLUDE_DIR)

mark_as_advanced(LIBURING_INCLUDE_DIR LIBURING_LIBRARIES)
