find_path(LIBAIO_INCLUDE_DIRS NAMES libaio.h)
find_library(LIBAIO_LIBRARIES NAMES aio)

include(FindPackageHandleStandardArgs)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    LIBAIO DEFAULT_MSG
    LIBAIO_LIBRARIES LIBAIO_INCLUDE_DIRS)
