if(GIT_EXECUTABLE)
  set(GIT_FOUND TRUE)
  return()
endif()
if(DEFINED GIT_EXECUTABLE)
  set(GIT_FOUND FALSE)
  return()
endif()

set(orig_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})
unset(CMAKE_MODULE_PATH)
include(FindGit)
set(CMAKE_MODULE_PATH ${orig_CMAKE_MODULE_PATH})
