IF(DEFINED BISON_EXECUTABLE)
  SET(bison_quiet QUIET)
ENDIF()

set(orig_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})
unset(CMAKE_MODULE_PATH)
find_package(BISON ${BISON_FIND_VERSION} ${bison_quiet} ${BISON_FIND_REQUIRED})
set(CMAKE_MODULE_PATH ${orig_CMAKE_MODULE_PATH})
