find_path(LIBPMEM_INCLUDE_DIR NAMES libpmem.h)
find_library(LIBPMEM_LIBRARIES NAMES pmem)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    PMEM DEFAULT_MSG
    LIBPMEM_LIBRARIES LIBPMEM_INCLUDE_DIR)

mark_as_advanced(LIBPMEM_INCLUDE_DIR LIBPMEM_LIBRARIES)
