[package]
name = "mariadb-server"
version = "0.1.0"
edition = '2021'


[dependencies]
mariadb-server-sys = { path = "../bindings" }
mariadb-server-macros = { path = "../macros" }
cstr = "0.2.11"
concat-idents = "1.1.4"
