name: Generate Plugin API Docs

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mariadb/mariadb-doc-gen:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Generate documentation
        shell: bash
        run: |
          set -euo pipefail
          target_dir=$(pwd)/bld/docs/plugin-api
          mkdir -p "$target_dir"
          cd include/mysql
          bash -x generate_plugin_api_docs.sh "$target_dir"
