name: npm-publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # npm provenance

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Init required submodules
        run: git submodule update --init extra/wolfssl/wolfssl libmariadb

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Build WASM package
        run: ./wasm/build.sh

      - name: Test
        run: npm test
        working-directory: wasm

      - name: Publish to npm
        run: npm publish --provenance --access public
        working-directory: wasm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
