---

# Main "useful" actions config file
# Cache config comes from https://github.com/actions/cache/blob/main/examples.md#rust---cargo
# actions-rs/toolchain configures rustup
# actions-rs/cargo actually runs cargo

on:
  push:
    branches:
    - rust
  # pull_request:

name: Rust Validation

env:
  RUST_BACKTRACE: "1"
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  clippy:
    name: "Clippy (cargo clippy)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install cmake
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --manifest-path rust/Cargo.toml -- -D warnings

  test:
    strategy:
        fail-fast: true
        matrix:
          os: [ubuntu-latest] #, windows-latest, macos-latest]
          include:
            - os: ubuntu-latest
              name: linux
            - os: windows-latest
              name: windows
            # - os: macos-latest
            #   name: mac

    name: "Test on ${{ matrix.name }} (cargo test)"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --manifest-path rust/Cargo.toml

  mtr:
    name: "Run mtr integration tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache-docker
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Cache Docker Output
        id: cache-docker-out
        uses: actions/cache@v3
        with:
          path: docker_obj
          key: ${{ runner.os }}-primes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: mdb-test-build:latest
          file: rust/scripts/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Start docker
        run: >
          docker run --rm
          --volume $(pwd):/checkout:ro
          --volume $(pwd)/docker_obj:/obj
          mdb-test-build
          /bin/bash -c
          'rust/scripts/launch/build_maria.sh && rust/scripts/launch/run_mtr.sh'

  fmt:
    name: "Format (cargo fmt)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --manifest-path rust/Cargo.toml --all -- --check

  doc:
    name: "Docs (cargo doc) & Pub"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install cmake
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      # test docs for everything
      - name: Test build all docs
        run: cargo doc --manifest-path rust/Cargo.toml --no-deps
      # create docs for the crate we care about
      - name: Build docs for publish
        run: |
          rm -rf target/doc/ rust/target/doc/
          cargo doc --manifest-path rust/mariadb/Cargo.toml --no-deps
          cargo doc --manifest-path rust/bindings/Cargo.toml --no-deps
      - run: |
          echo `pwd`/rust/target/doc >> $GITHUB_PATH
          # fake index.html so github likes us
          echo "<meta http-equiv=\"refresh\" content=\"0; url=mariadb\">" > rust/target/doc/index.html
      - name: Deploy GitHub Pages
        run: |
          git worktree add gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../rust/target/doc/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force --set-upstream origin gh-pages
