---

# Main "useful" actions config file
# Cache config comes from https://github.com/actions/cache/blob/main/examples.md#rust---cargo
# actions-rs/toolchain configures rustup
# actions-rs/cargo actually runs cargo

on:
  push:
    branches:
    - rust
  # pull_request:

name: Rust Validation

jobs:
  check:
    name: "Check (cargo check)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            rust/target/
            CMakeFiles/
            CMakeCache.txt
            CPackConfig.cmake
            CPackSourceConfig.cmake
            CTestTestfile.cmake
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt-get update && sudo apt-get install cmake
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path rust/Cargo.toml

  test:
    strategy:
        fail-fast: true
        matrix:
          os: [ubuntu-latest] #, windows-latest, macos-latest]
          include:
            - os: ubuntu-latest
              name: linux
            # - os: windows-latest
            #   name: windows
            # - os: macos-latest
            #   name: mac

    name: "Test on ${{ matrix.name }} (cargo test)"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            rust/target/
            CMakeFiles/
            CMakeCache.txt
            CPackConfig.cmake
            CPackSourceConfig.cmake
            CTestTestfile.cmake
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt-get update && sudo apt-get install cmake
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUST_BACKTRACE: "1"
        with:
          command: test
          args: --manifest-path rust/Cargo.toml

  fmt:
    name: "Format (cargo fmt)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            rust/target/
            CMakeFiles/
            CMakeCache.txt
            CPackConfig.cmake
            CPackSourceConfig.cmake
            CTestTestfile.cmake
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path rust/Cargo.toml -- --check

  clippy:
    name: "Clippy (cargo clippy)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            rust/target/
            CMakeFiles/
            CMakeCache.txt
            CPackConfig.cmake
            CPackSourceConfig.cmake
            CTestTestfile.cmake
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt-get update && sudo apt-get install cmake
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Some nice checks are only nightly
          toolchain: nightly
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path rust/Cargo.toml -- -D warnings

  doc:
    name: "Docs (cargo doc) & Pub"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            rust/target/
            CMakeFiles/
            CMakeCache.txt
            CPackConfig.cmake
            CPackSourceConfig.cmake
            CTestTestfile.cmake
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt-get update && sudo apt-get install cmake
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --manifest-path rust/Cargo.toml --no-deps
      - run: |
          echo `pwd`/rust/target/doc >> $GITHUB_PATH
          # fake index.html so github likes us
          echo "<meta http-equiv=\"refresh\" content=\"0; url=mariadb_server\">" > rust/target/doc/index.html
      - name: Deploy GitHub Pages
        run: |
          git worktree add gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../rust/target/doc/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force --set-upstream origin gh-pages
